package classic

import (
	"time"

	"github.com/wowsims/forever/sim/common/shared"
	"github.com/wowsims/forever/sim/core"
)

// A damage shield: "When struck in combat inflicts $s1 <school> damage to the attacker", off every
// melee hit the wearer takes. The damage neither crits nor partially resists.
func newDamageShieldEffect(name string, itemID int32, spellID int32, school core.SpellSchool, damage float64) {
	shared.NewProcDamageEffect(shared.ProcDamageEffect{
		ItemID:      itemID,
		SpellID:     spellID,
		School:      school,
		DefenseType: core.DefenseTypeMagic,
		MinDmg:      damage,
		MaxDmg:      damage,
		CannotCrit:  true,
		Flags:       core.SpellFlagBinary | core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell | core.SpellFlagProc,
		Trigger: core.ProcTrigger{
			Name:     name,
			Callback: core.CallbackOnSpellHitTaken,
			ProcMask: core.ProcMaskMelee,
			Outcome:  core.OutcomeLanded,
		},
	})
}

func init() {
	// Force Reactive Disk
	core.NewItemEffect(18168, func(agent core.Agent) {
		character := agent.GetCharacter()

		spell := character.RegisterSpell(core.SpellConfig{
			ActionID:    core.ActionID{ItemID: 18168},
			SpellSchool: core.SpellSchoolNature,
			DefenseType: core.DefenseTypeMagic, // Force Reactive Disk (22618)
			ProcMask:    core.ProcMaskEmpty,
			Flags:       core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell,

			DamageMultiplier: 1,
			ThreatMultiplier: 1,

			ApplyEffects: func(sim *core.Simulation, _ *core.Unit, spell *core.Spell) {
				spell.CalcAndDealAoeDamage(sim, 25, spell.OutcomeMagicHitAndCrit)
			},
		})

		aura := character.MakeProcTriggerAura(core.ProcTrigger{
			Name:     "Force Reactive Disk",
			ProcMask: core.ProcMaskMelee,
			ICD:      time.Second,
			Outcome:  core.OutcomeBlock,
			Callback: core.CallbackOnSpellHitTaken,
			Handler: func(sim *core.Simulation, _ *core.Spell, result *core.SpellResult) {
				spell.Cast(sim, result.Target)
			},
		})

		character.ItemSwap.RegisterProc(18168, aura)
	})

	// Naglering and Drillborer Disk: 3 Arcane (15438).
	newDamageShieldEffect("Naglering", 11669, 15438, core.SpellSchoolArcane, 3)
	newDamageShieldEffect("Drillborer Disk", 17066, 15438, core.SpellSchoolArcane, 3)

	// Razor Gauntlets: 7 Nature (1302193), where master had Era's 3 Arcane.
	newDamageShieldEffect("Razor Gauntlets", 18326, 1302193, core.SpellSchoolNature, 7)

	// Omokk's Girth Restrainer
	// Equip: Decreases all threat generated by 1% (1298501).
	core.NewItemEffect(13959, func(agent core.Agent) {
		character := agent.GetCharacter()
		aura := core.MakePermanent(character.RegisterAura(core.Aura{
			Label:    "Omokk's Girth Restrainer",
			ActionID: core.ActionID{ItemID: 13959},
		})).AttachMultiplicativePseudoStatBuff(&character.PseudoStats.ThreatMultiplier, 0.99)

		character.ItemSwap.RegisterProc(13959, aura)
	})
}
