package warlock

import (
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

var ItemSetDeathmistRaiment = core.NewItemSet(core.ItemSet{
	Name: "Deathmist Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		// +8 All Resistances.
		2: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(8)
		},
		// Restores 8 mana per 5 sec.
		3: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.MP5, 8)
		},
		// Your spellcasts have a 5% chance to heal you for 270 to 330. Classic put the fear proc
		// here, which the sim left unimplemented.
		4: func(agent core.Agent) {
			c := agent.GetCharacter()
			actionID := core.ActionID{SpellID: 450585}
			healthMetrics := c.NewHealthMetrics(actionID)

			core.MakeProcTriggerAura(&c.Unit, core.ProcTrigger{
				ActionID:   actionID,
				Name:       "Dark Reward",
				Callback:   core.CallbackOnCastComplete,
				ProcMask:   core.ProcMaskSpellDamage | core.ProcMaskSpellHealing,
				ProcChance: 0.05,
				Handler: func(sim *core.Simulation, _ *core.Spell, _ *core.SpellResult) {
					c.GainHealth(sim, sim.Roll(270, 331), healthMetrics)
				},
			})
		},
		// Corrupted Fear: the attacker flees when you are struck.
		5: func(_ core.Agent) {},
		// Increases damage and healing done by magical spells and effects by up to 23.
		6: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddStat(stats.SpellPower, 23)
		},
	},
})

var ItemSetFelheartRaiment = core.NewItemSet(core.ItemSet{
	Name: "Felheart Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		// 3 pieces: Health or Mana gained from Drain Life and Drain Mana increased by 15%.
		// 5 pieces: Your pet gains 15 stamina and 100 spell resistance against all schools of magic.
		// 8 pieces: Mana cost of Shadow spells reduced by 15%.
		8: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Shadow Cost Reduction (Felheart Raiment)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Spellbook {
						if spell.SpellSchool.Matches(core.SpellSchoolShadow) && spell.Cost != nil {
							spell.Cost.Multiplier -= 15
						}
					}
				},
			})
		},
	},
})

var ItemSetNemesisRaiment = core.NewItemSet(core.ItemSet{
	Name: "Nemesis Raiment",
	Bonuses: map[int32]core.ApplyEffect{
		// 3 pieces: Increases damage and healing done by magical spells and effects by up to 23.
		3: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.SpellPower, 23)
		},
		// 5 pieces: Your pet gains 20 stamina and 130 spell resistance against all schools of magic.
		// 8 pieces: Reduces the threat generated by your Destruction spells by 20%.
		8: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Decreased Destruction Threat (Nemesis Raiment)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Spellbook {
						if spell.Flags.Matches(WarlockFlagDestruction) {
							spell.ThreatMultiplier *= 0.80
						}
					}
				},
			})
		},
	},
})

var ItemSetDemoniacsThreads = core.NewItemSet(core.ItemSet{
	Name: "Demoniac's Threads",
	Bonuses: map[int32]core.ApplyEffect{
		// Increases damage and healing done by magical spells and effects by up to 12.
		2: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.AddStat(stats.SpellPower, 12)
		},
		// 3 pieces: Increases the damage of Corruption by 2%.
		3: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Improved Corruption (Demoniac's Threads)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Corruption {
						spell.DamageMultiplierAdditive += 0.02
					}
				},
			})
		},
		// 5 pieces: Decreases the cooldown of Death Coil by 15%.
		5: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Improved Death Coil (Demoniac's Threads)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.DeathCoil {
						spell.CD.Duration = time.Duration(float64(spell.CD.Duration) * 0.85)
					}
				},
			})
		},
	},
})

var ItemSetDoomcallersAttire = core.NewItemSet(core.ItemSet{
	Name: "Doomcaller's Attire",
	Bonuses: map[int32]core.ApplyEffect{
		// 3 pieces: 5% increased damage on your Immolate spell.
		3: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Doomcaller Immolate Bonus",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.Immolate {
						spell.BaseDamageMultiplierAdditive += 0.05
					}
				},
			})
		},
		// 5 pieces: Reduces the mana cost of Shadow Bolt by 15%.
		5: func(agent core.Agent) {
			warlock := agent.(WarlockAgent).GetWarlock()
			warlock.RegisterAura(core.Aura{
				Label: "Doomcaller Reduced Shadow Bolt Cost",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warlock.ShadowBolt {
						spell.Cost.Multiplier -= 15
					}
				},
			})
		},
	},
})
