package buffmanifest

import "github.com/wowsims/forever/sim/core/proto"

// Manifest holds one row per proto field of RaidBuffs, PartyBuffs, IndividualBuffs
// and Debuffs. Rows follow the UI registry order: PARTY_BUFFS_CONFIG, then
// BUFFS_CONFIG, then DEBUFFS_CONFIG, with the fields of a scope that have no UI
// input appended after that scope's last input in proto declaration order. The two
// quadstate companion fields sit next to the row whose input renders them.
var Manifest = []BuffSpec{
	{
		Field: "blood_pact", Number: 2, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "BloodPact", Name: "Blood Pact", Owner: proto.Class_ClassWarlock,
		Stats: []proto.Stat{proto.Stat_StatStamina},
		Notes: "Improved Imp (18694) modifies Firebolt and Fire Shield, not Blood Pact, so the improved state has no source in warlock tree 1116.",
	},
	{
		Field: "commanding_shout", Number: 33, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "CommandingShout", Name: "Commanding Shout", Owner: proto.Class_ClassWarrior,
		Category: "CommandingShout", SingleAura: true, Driver: true,
		Stats: []proto.Stat{proto.Stat_StatStamina},
		Notes: "SkillLineAbility resolves the name to the single rankless spell 403215; no improving talent in warrior tree 1117.",
	},
	{
		Field: "battle_shout", Number: 28, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "BattleShout", Name: "Battle Shout", Owner: proto.Class_ClassWarrior,
		Category: "BattleShout", SingleAura: true, Driver: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "Booming Voice (12321) is in warrior tree 1117 but modifies radius only (misc 6), so there is no improved state. The single A_MOD_ATTACK_POWER effect is melee attack power, which is why the row tags that alone.",
	},
	{
		Field: "devotion_aura", Number: 6, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "DevotionAura", Name: "Devotion Aura", Owner: proto.Class_ClassPaladin,
		Category: "DevotionAura", SharedCategory: "PaladinAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatArmor},
		Notes: "no Improved Devotion Aura node in paladin tree 1100.",
	},
	{
		Field: "leader_of_the_pack", Number: 4, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "LeaderOfThePack", Name: "Leader of the Pack", AuraName: "Leader of the Pack",
		Owner: proto.Class_ClassDruid, Pet: PetCapAtRegular,
		StatOverride: []string{"PhysicalCritPercent"},
		Stats:        []proto.Stat{proto.Stat_StatAttackPower, proto.Stat_StatMeleeCritRating},
		Notes:        "SkillLineAbility resolves the name to the talent passive 17007; the party aura is the second spell of the same name, 24932. Neither carries a rank subtext, so the aura-family rule cannot separate them: the generator must prefer the party aura 24932 or this row needs an explicit Anchor. No improving talent in druid tree 1089. Spell 24932 reads \"Increases critical strike chance by $s1%\" and 17007 calls it \"exclusive with Moonkin Aura\": the client never says melee, so StatOverride does.",
	},
	{
		Field: "mana_spring_totem", Number: 18, Scope: ScopeParty, Proto: ProtoTristate, Kind: KindStatFlat,
		Go: "ManaSpringTotem", Name: "Mana Spring Totem", AuraName: "Mana Spring",
		Owner:    proto.Class_ClassShaman,
		Talent:   &TalentMod{Name: "Restorative Totems", Effect: 0, Applies: TalentScalesValue},
		Category: "ManaSpringTotem",
		Stats:    []proto.Stat{proto.Stat_StatMP5},
		Notes:    "Restorative Totems (16187, TraitDefinition 134191) effect 0 scales the Mana Spring aura family (class mask 16384), not the totem cast.",
	},
	{
		Field: "mana_tide_totems", Number: 19, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindExternalCD,
		Go: "ManaTideTotems", Name: "Mana Tide Totem", AuraName: "Mana Tide",
		Owner: proto.Class_ClassShaman, Category: "ManaTideTotem",
		Stats: []proto.Stat{proto.Stat_StatMP5}, Label: "Mana Tide Totem",
		Notes: "the totem cast 17359 states the 13 s life and the 5 min cooldown; the aura 17360 states the mana.",
	},
	{
		Field: "shadow_priest_dps", Number: 6, Scope: ScopeIndividual, Proto: ProtoInt32, Kind: KindManual,
		Go: "ShadowPriestDps", Name: "Vampiric Touch", Owner: proto.Class_ClassPriest,
		Pet:   PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatMP5}, Label: "Vampiric Touch",
		Notes: "mana returned to the party is entered by hand and stays a hand-written driver; SkillLineAbility resolves Vampiric Touch to 402668.",
	},
	{
		Field: "moonkin_aura", Number: 3, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "MoonkinAura", Name: "Moonkin Aura", Owner: proto.Class_ClassDruid, Pet: PetCapAtRegular,
		StatOverride: []string{"SpellCritPercent"},
		Stats:        []proto.Stat{proto.Stat_StatSpellCritRating},
		Notes:        "A_MOD_CRIT_PCT does not distinguish melee from spell crit, so StatOverride names the stat spell 24907 means; no improving talent in druid tree 1089.",
	},
	{
		Field: "retribution_aura", Number: 7, Scope: ScopeParty, Proto: ProtoBool, Kind: KindDamageShield,
		Go: "RetributionAura", Name: "Retribution Aura", Owner: proto.Class_ClassPaladin,
		Category: "RetributionAura", SharedCategory: "PaladinAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatResilienceRating, proto.Stat_StatArmor, proto.Stat_StatDefenseRating},
		Notes: "the only paladin trait matching Retribution Aura is Benediction (20101), which modifies cost (misc 14).",
	},
	{
		Field: "concentration_aura", Number: 45, Scope: ScopeParty, Proto: ProtoBool, Kind: KindPseudoMult,
		Go: "ConcentrationAura", Name: "Concentration Aura", Owner: proto.Class_ClassPaladin,
		Category: "ConcentrationAura", SharedCategory: "PaladinAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatDefenseRating},
		Notes: "no Improved Concentration Aura node in paladin tree 1100.",
	},
	{
		Field: "trueshot_aura", Number: 8, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "TrueshotAura", Name: "Trueshot Aura", Owner: proto.Class_ClassHunter,
		Stats: []proto.Stat{proto.Stat_StatRangedAttackPower},
		Notes: "the rank ladder is non-monotonic: rank 5 (20906) states 50 ranged attack power where rank 4 (20905) states 75, and the resolver takes the top rank. The single A_MOD_RANGED_ATTACK_POWER effect is why the row tags ranged attack power alone.",
	},
	{
		Field: "atiesh_mage", Number: 12, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		Go: "AtieshMage", Anchor: 28142, Owner: proto.Class_ClassMage,
		Stats: []proto.Stat{proto.Stat_StatSpellDamage, proto.Stat_StatHealingPower}, Label: "Atiesh - Mage",
		Notes: "aura-only spell; 28142 is named Power of the Guardian.",
	},
	{
		Field: "atiesh_warlock", Number: 13, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		Go: "AtieshWarlock", Anchor: 28143, Owner: proto.Class_ClassWarlock,
		Stats: []proto.Stat{proto.Stat_StatSpellDamage, proto.Stat_StatHealingPower}, Label: "Atiesh - Warlock",
		Notes: "aura-only spell; 28143 is named Power of the Guardian.",
	},
	{
		Field: "strength_of_earth_totem", Number: 24, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "StrengthOfEarthTotem", Name: "Strength of Earth Totem", AuraName: "Strength of Earth",
		Owner: proto.Class_ClassShaman, Category: "StrengthOfEarthTotem",
		Stats: []proto.Stat{proto.Stat_StatStrength},
		Notes: "Enhancing Totems (16295) exists as a spell but has no node in shaman tree 1082.",
	},
	{
		Field: "grace_of_air_totem", Number: 23, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "GraceOfAirTotem", Name: "Grace of Air Totem", AuraName: "Grace of Air",
		Owner: proto.Class_ClassShaman, Category: "GraceOfAirTotem", Driver: true,
		Stats: []proto.Stat{proto.Stat_StatAgility},
		Notes: "Enhancing Totems (16295) exists as a spell but has no node in shaman tree 1082. Driven because totem_twisting shortens the aura to the 9 s of every 10 a twisting shaman keeps it up.",
	},
	{
		Field: "windfury_totem", Number: 27, Scope: ScopeParty, Proto: ProtoBool, Kind: KindProc,
		Go: "WindfuryTotem", Name: "Windfury Totem", AuraName: "Windfury Totem",
		Owner: proto.Class_ClassShaman, Category: "WindfuryTotem", Pet: PetStrip,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "the cast family (8512/10613/10614) and the aura family (8516/10608/10610) share the name; the aura carries the proc. Improved Weapon Totems (29193) has no node in shaman tree 1082.",
	},
	{
		Field: "frost_resistance_totem", Number: 39, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "FrostResistanceTotem", Name: "Frost Resistance Totem", AuraName: "Frost Resistance",
		Owner: proto.Class_ClassShaman, Category: "ResistanceFrost",
		Stats: []proto.Stat{proto.Stat_StatFrostResistance},
	},
	{
		Field: "nature_resistance_totem", Number: 40, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "NatureResistanceTotem", Name: "Nature Resistance Totem", AuraName: "Nature Resistance",
		Owner: proto.Class_ClassShaman, Category: "ResistanceNature",
		Stats: []proto.Stat{proto.Stat_StatNatureResistance},
	},
	{
		Field: "fire_resistance_totem", Number: 41, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "FireResistanceTotem", Name: "Fire Resistance Totem", AuraName: "Fire Resistance",
		Owner: proto.Class_ClassShaman, Category: "ResistanceFire",
		Stats: []proto.Stat{proto.Stat_StatFireResistance},
	},
	{
		Field: "frost_resistance_aura", Number: 38, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "FrostResistanceAura", Name: "Frost Resistance Aura", Owner: proto.Class_ClassPaladin,
		Category: "FrostResistanceAura", SharedCategory: "PaladinAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatFrostResistance},
	},
	{
		Field: "fire_resistance_aura", Number: 42, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "FireResistanceAura", Name: "Fire Resistance Aura", Owner: proto.Class_ClassPaladin,
		Category: "FireResistanceAura", SharedCategory: "PaladinAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatFireResistance},
	},
	{
		Field: "shadow_resistance_aura", Number: 43, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "ShadowResistanceAura", Name: "Shadow Resistance Aura", Owner: proto.Class_ClassPaladin,
		Category: "ShadowResistanceAura", SharedCategory: "PaladinAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatShadowResistance},
	},
	{
		Field: "aspect_of_the_wild", Number: 44, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		Go: "AspectOfTheWild", Name: "Aspect of the Wild", Owner: proto.Class_ClassHunter,
		Category: "ResistanceNature",
		Stats:    []proto.Stat{proto.Stat_StatNatureResistance},
	},
	{
		Field: "atiesh_druid", Number: 35, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		Go: "AtieshDruid", Anchor: 28145, Owner: proto.Class_ClassDruid, Label: "Atiesh - Druid",
		Notes: "no UI input today; aura-only spell 28145 is named Power of the Guardian.",
	},
	{
		Field: "atiesh_priest", Number: 36, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		Go: "AtieshPriest", Anchor: 28144, Owner: proto.Class_ClassPriest, Label: "Atiesh - Priest",
		Notes: "no UI input today; aura-only spell 28144 is named Power of the Guardian.",
	},
	{
		Field: "totem_twisting", Number: 34, Scope: ScopeParty, Proto: ProtoBool, Kind: KindFlag,
		Go:    "TotemTwisting",
		Notes: "sim behaviour toggle with no spell source; rendered under Other Inputs.",
	},
	{
		Field: "arcane_brilliance", Number: 1, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "ArcaneBrilliance", Name: "Arcane Brilliance", Owner: proto.Class_ClassMage,
		Category: "StatBuff", Pet: PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatIntellect},
		Notes: "the ungranted twin 364161 has no SkillLineAbility row.",
	},
	{
		Field: "blessing_of_kings", Number: 1, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindStatPct,
		Go: "BlessingOfKings", Name: "Blessing of Kings", Owner: proto.Class_ClassPaladin,
		Pet:   PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatAgility, proto.Stat_StatIntellect, proto.Stat_StatSpirit, proto.Stat_StatStamina, proto.Stat_StatStrength},
		Notes: "SkillLineAbility resolves the name to 20217 and Greater Blessing of Kings to 25898; the ungranted twin 1213408 has no SkillLineAbility row.",
	},
	{
		Field: "bloodlust", Number: 7, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindManual,
		Go: "Bloodlust", Name: "Bloodlust", Owner: proto.Class_ClassShaman, Pet: PetStrip,
		Notes: "no SkillLineAbility row for 1245940 / 1222564 / 468408; keeps registerBloodlustCD.",
	},
	{
		Field: "divine_spirit", Number: 4, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "DivineSpirit", Name: "Divine Spirit", Owner: proto.Class_ClassPriest,
		Category: "StatBuff", Pet: PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatSpirit, proto.Stat_StatSpellDamage},
		Notes: "no Improved Divine Spirit node in priest tree 1114.",
	},
	{
		Field: "gift_of_the_wild", Number: 5, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "GiftOfTheWild", Name: "Gift of the Wild", Owner: proto.Class_ClassDruid,
		Pet:   PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatArmor, proto.Stat_StatStrength, proto.Stat_StatAgility, proto.Stat_StatIntellect, proto.Stat_StatSpirit, proto.Stat_StatStamina},
		Notes: "no Improved Mark of the Wild node in druid tree 1089; the ungranted twins 1291335/1310503 have no SkillLineAbility row. The per-school resistance categories this aura joins are derived from the effect school mask by KindResistance, not carried in the manifest.",
	},
	{
		Field: "thorns", Number: 6, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindDamageShield,
		Go: "Thorns", Name: "Thorns", Owner: proto.Class_ClassDruid, Pet: PetStrip,
		Stats: []proto.Stat{proto.Stat_StatResilienceRating, proto.Stat_StatDefenseRating, proto.Stat_StatStamina},
		Notes: "no Brambles node in druid tree 1089; the only matching trait is Moonglow (16845), which modifies cost (misc 14).",
	},
	{
		Field: "power_word_fortitude", Number: 2, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "PowerWordFortitude", Name: "Power Word: Fortitude", Owner: proto.Class_ClassPriest,
		Pet:   PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatStamina},
		Notes: "no Improved Power Word: Fortitude node in priest tree 1114.",
	},
	{
		Field: "blessing_of_might", Number: 5, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "BlessingOfMight", Name: "Blessing of Might", Owner: proto.Class_ClassPaladin,
		Pet:   PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "no Improved Blessing of Might node in paladin tree 1100; Benediction (20101) modifies cost (misc 14).",
	},
	{
		Field: "blessing_of_wisdom", Number: 4, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindStatFlat,
		Go: "BlessingOfWisdom", Name: "Blessing of Wisdom", Owner: proto.Class_ClassPaladin,
		Pet:   PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatMP5},
		Notes: "no Improved Blessing of Wisdom node in paladin tree 1100; Benediction (20101) modifies cost (misc 14).",
	},
	{
		Field: "blessing_of_salvation", Number: 2, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindPseudoMult,
		Go: "BlessingOfSalvation", Name: "Blessing of Salvation", Owner: proto.Class_ClassPaladin,
		Pet: PetStripWhenSummonedLate,
	},
	{
		Field: "shadow_protection", Number: 3, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		Go: "ShadowProtection", Name: "Shadow Protection", Owner: proto.Class_ClassPriest,
		Category: "ResistanceShadow", Pet: PetStripWhenSummonedLate,
		Stats: []proto.Stat{proto.Stat_StatShadowResistance, proto.Stat_StatStamina},
	},
	{
		Field: "innervates", Number: 8, Scope: ScopeIndividual, Proto: ProtoInt32, Kind: KindExternalCD,
		Go: "Innervates", Name: "Innervate", Owner: proto.Class_ClassDruid, Pet: PetStrip,
		Category: "Innervate",
		Stats:    []proto.Stat{proto.Stat_StatMP5}, Label: "Innervates",
		Notes: "auras 134 and 110 of spell 29166 are the spirit regen the driver applies; no Improved Innervate node in druid tree 1089.",
	},
	{
		Field: "power_infusions", Number: 9, Scope: ScopeIndividual, Proto: ProtoInt32, Kind: KindExternalCD,
		Go: "PowerInfusions", Name: "Power Infusion", Owner: proto.Class_ClassPriest, Pet: PetStrip,
		Category: "PowerInfusion",
		Stats:    []proto.Stat{proto.Stat_StatSpellHasteRating}, Label: "Power Infusions",
		Notes: "Power Infusion (10060) grants +20% damage and healing done for 15 s.",
	},
	{
		Field: "hunters_mark", Number: 17, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "HuntersMark", Name: "Hunter's Mark", Owner: proto.Class_ClassHunter,
		Category: "HuntersMark", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatRangedAttackPower, proto.Stat_StatAttackPower},
		Notes: "no Improved Hunter's Mark node in hunter tree 1091; CumulativeAura is 0, so rank 4 (14325) is a flat value.",
	},
	{
		Field: "improved_seal_of_the_crusader", Number: 3, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "ImprovedSealOfTheCrusader", Name: "Judgement of the Crusader", Owner: proto.Class_ClassPaladin,
		Category: "Improved Seal of the Crusader", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatMeleeCritRating, proto.Stat_StatSpellCritRating},
		Label: "Seal of the Crusader",
		Notes: "Improved Seal of the Crusader (20337) exists as a spell but has no node in paladin tree 1100.",
	},
	{
		Field: "judgement_of_light", Number: 2, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindProc,
		Go: "JudgementOfLight", Name: "Judgement of Light", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatResilienceRating},
	},
	{
		Field: "judgement_of_wisdom", Number: 1, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindProc,
		Go: "JudgementOfWisdom", Name: "Judgement of Wisdom", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatMP5},
	},
	{
		Field: "mangle", Number: 12, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffDamageTaken,
		Go: "Mangle", Name: "Mangle", Owner: proto.Class_ClassDruid,
		Category: "Mangle", SingleAura: true,
		Notes: "SkillLineAbility resolves the name to ranks 407995/1238069/1238070/1238073, so the top rank is 1238073.",
	},
	{
		Field: "curse_of_elements", Number: 5, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffDamageTaken,
		Go: "CurseOfElements", Name: "Curse of the Elements", Owner: proto.Class_ClassWarlock,
		Category: "CurseOfElements", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatSpellDamage},
		Notes: "Malediction (1225177) is in warlock tree 1116 but its modifier masks do not cover Curse of the Elements (mask 4194304); the only overlapping trait is Amplify Curse (18288), an ability with a 3 minute cooldown, so there is no passive improved state. The ungranted ranks 11723/11724 have no SkillLineAbility row.",
	},
	{
		Field: "curse_of_recklessness", Number: 16, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "CurseOfRecklessness", Name: "Curse of Recklessness", Owner: proto.Class_ClassWarlock,
		Category: "CurseOfRecklessness", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
	},
	{
		Field: "faerie_fire", Number: 14, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "FaerieFire", Name: "Faerie Fire", Owner: proto.Class_ClassDruid,
		Category: "FaerieFireAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower, proto.Stat_StatMeleeHitRating},
		Notes: "no Improved Faerie Fire node in druid tree 1089; the ungranted twins 1288561/1289452 have no SkillLineAbility row.",
	},
	{
		Field: "expose_armor", Number: 13, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "ExposeArmor", Name: "Expose Armor", Owner: proto.Class_ClassRogue,
		Category: "MajorArmorReduction", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "effect 0 states 0 and -450 per combo point, so the row is resolved as the five-point finisher, which is what the raid config applies; a rogue casting it for fewer combo points needs a driver that prices the aura, and there is none. Improved Expose Armor (14168) is in rogue tree 1111 but its only 107/108 effect is misc 14 (cost); effects 1 and 2 are dummy auras.",
	},
	{
		Field: "sunder_armor", Number: 15, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStacking,
		Go: "SunderArmor", Name: "Sunder Armor", Owner: proto.Class_ClassWarrior,
		Category: "MajorArmorReduction", SingleAura: true, Driver: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "CumulativeAura is 5, and a stack is worth nothing until it is there, so the raid's copy is ramped by a driver; Improved Sunder Armor (12308) modifies cost only (misc 14).",
	},
	{
		Field: "gift_of_arthas", Number: 11, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffDamageTaken,
		Go: "GiftOfArthas", Anchor: 11374, Category: "GiftOfArthasAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower, proto.Stat_StatResilienceRating},
		Notes: "applied by an elixir, so 11374 has no SkillLineAbility row and the anchor is explicit.",
	},
	{
		Field: "demoralizing_roar", Number: 20, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "DemoralizingRoar", Name: "Demoralizing Roar", Owner: proto.Class_ClassDruid,
		Category: "Demoralizing", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatResilienceRating},
		Notes: "no Feral Aggression node in druid tree 1089.",
	},
	{
		Field: "demoralizing_shout", Number: 21, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "DemoralizingShout", Name: "Demoralizing Shout", Owner: proto.Class_ClassWarrior,
		Category: "Demoralizing", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatResilienceRating},
		Notes: "no Improved Demoralizing Shout node in warrior tree 1117.",
	},
	{
		Field: "thunder_clap", Number: 22, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffAtkSpeed,
		Go: "ThunderClap", Name: "Thunder Clap", Owner: proto.Class_ClassWarrior,
		Category: "AtkSpdReduction",
		Stats:    []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatResilienceRating},
		Notes:    "Improved Thunder Clap (12287) is in warrior tree 1117 but its only 107/108 effect is misc 14 (cost).",
	},
	{
		Field: "insect_swarm", Number: 23, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "InsectSwarm", Name: "Insect Swarm", Owner: proto.Class_ClassDruid,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatResilienceRating},
		Notes: "Nature's Splendor (1223083) effect 2 extends the duration (misc 1); the field is a plain bool, so the talent is not carried.",
	},
	{
		Field: "scorpid_sting", Number: 24, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		Go: "ScorpidSting", Name: "Scorpid Sting", Owner: proto.Class_ClassHunter,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatResilienceRating},
		Notes: "Improved Stings (1310661) effect 2 extends the duration (misc 1); the field is a plain bool, so the talent is not carried.",
	},
}
