// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package core

import (
	"time"

	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/stats"
)

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var PaladinAuraCategory = "PaladinAura"

// Blood Pact - https://www.wowhead.com/forever/spell=11767
func BloodPactValue(talentPoints int32) float64 {
	return 54.0
}
func BloodPactDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func BloodPactAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Blood Pact (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 11767}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: BloodPactDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Stamina, BloodPactValue(talentPoints), false},
		},
	})
}

// Commanding Shout - https://www.wowhead.com/forever/spell=403215
var CommandingShoutCategory = "CommandingShout"

func CommandingShoutValue(talentPoints int32) float64 {
	return 42.0
}
func CommandingShoutDuration(talentPoints int32) time.Duration {
	return 300000 * time.Millisecond
}
func CommandingShoutAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:      "Commanding Shout (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   ActionID{SpellID: 403215}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:   CommandingShoutDuration(talentPoints),
		Category:   CommandingShoutCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []StatConfig{
			{stats.Stamina, CommandingShoutValue(talentPoints), false},
		},
	})
}

// Battle Shout - https://www.wowhead.com/forever/spell=25289
var BattleShoutCategory = "BattleShout"

func BattleShoutValue(talentPoints int32) float64 {
	return 139.0
}
func BattleShoutDuration(talentPoints int32) time.Duration {
	return 180000 * time.Millisecond
}
func BattleShoutAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:      "Battle Shout (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   ActionID{SpellID: 25289}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:   BattleShoutDuration(talentPoints),
		Category:   BattleShoutCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []StatConfig{
			{stats.AttackPower, BattleShoutValue(talentPoints), false},
		},
	})
}

// func SnapshotBsT2Aura(unit *Unit, isPlayer bool, talentPoints int32) *Aura // snapshot_bs_t2, KindFlag: says the warrior who shouted for the party wears three pieces of Battlegear of Wrath, whose ItemSetSpell at three is 23563: +30 on every effect of the Battle Shout family. The resolver does not read ItemSetSpell, so driveBattleShout adds the amount; the UI input for it is hand-written next to Battle Shout.

// Devotion Aura - https://www.wowhead.com/forever/spell=10293
var DevotionAuraCategory = "DevotionAura"

func DevotionAuraValue(talentPoints int32) float64 {
	return 735.0
}
func DevotionAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func DevotionAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:          "Devotion Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       ActionID{SpellID: 10293}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:       DevotionAuraDuration(talentPoints),
		Category:       DevotionAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []StatConfig{
			{stats.Armor, DevotionAuraValue(talentPoints), false},
		},
	})
}

// Leader of the Pack - https://www.wowhead.com/forever/spell=24932
var LeaderOfThePackCategory = "DruidCritAura"

func LeaderOfThePackValue(talentPoints int32) float64 {
	return 3.0
}
func LeaderOfThePackDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func LeaderOfThePackAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:      "Leader of the Pack (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   ActionID{SpellID: 24932}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:   LeaderOfThePackDuration(talentPoints),
		Category:   LeaderOfThePackCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []StatConfig{
			{stats.PhysicalCritPercent, LeaderOfThePackValue(talentPoints), false},
			{stats.SpellCritPercent, 3.0, false},
		},
	})
}

// Mana Spring Totem - https://www.wowhead.com/forever/spell=10494
var ManaSpringTotemCategory = "ManaSpringTotem"

func ManaSpringTotemValue(talentPoints int32) float64 {
	return []float64{25.0, 25.0, 27.5, 27.5, 30.0, 30.0}[talentPoints]
}
func ManaSpringTotemDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func ManaSpringTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Mana Spring Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10494}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: ManaSpringTotemDuration(talentPoints),
		Category: ManaSpringTotemCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.MP5, ManaSpringTotemValue(talentPoints), false},
		},
	})
}

// Mana Tide Totem - https://www.wowhead.com/forever/spell=17360
var ManaTideTotemsCategory = "ManaTideTotem"

func ManaTideTotemsValue(talentPoints int32) float64 {
	return 483.3333333333333
}
func ManaTideTotemsDuration(talentPoints int32) time.Duration {
	return 13000 * time.Millisecond
}
func ManaTideTotemsCooldown() time.Duration {
	return 300000 * time.Millisecond
}
func ManaTideTotemsAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Mana Tide Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 17360}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: ManaTideTotemsDuration(talentPoints),
		Category: ManaTideTotemsCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.MP5, ManaTideTotemsValue(talentPoints), false},
		},
	})
}

// Vampiric Touch - https://www.wowhead.com/forever/spell=402668
func ShadowPriestDpsDuration(talentPoints int32) time.Duration {
	return 15000 * time.Millisecond
}
func ShadowPriestDpsAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Vampiric Touch (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 402668}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: ShadowPriestDpsDuration(talentPoints),
		IsPlayer: isPlayer,
	})
}

// Moonkin Aura - https://www.wowhead.com/forever/spell=24907
var MoonkinAuraCategory = "DruidCritAura"

func MoonkinAuraValue(talentPoints int32) float64 {
	return 3.0
}
func MoonkinAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func MoonkinAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:      "Moonkin Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   ActionID{SpellID: 24907}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:   MoonkinAuraDuration(talentPoints),
		Category:   MoonkinAuraCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []StatConfig{
			{stats.PhysicalCritPercent, MoonkinAuraValue(talentPoints), false},
			{stats.SpellCritPercent, 3.0, false},
		},
	})
}

// Retribution Aura - https://www.wowhead.com/forever/spell=10301
var RetributionAuraCategory = "RetributionAura"

func RetributionAuraValue(talentPoints int32) float64 {
	return 30.0
}
func RetributionAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func RetributionAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedDamageShield(unit, GeneratedBuff{
		Label:          "Retribution Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       ActionID{SpellID: 10301}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:       RetributionAuraDuration(talentPoints),
		Category:       RetributionAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
	}, SpellSchoolHoly, RetributionAuraValue(talentPoints))
}

// Concentration Aura - https://www.wowhead.com/forever/spell=19746
var ConcentrationAuraCategory = "ConcentrationAura"

func ConcentrationAuraValue(talentPoints int32) float64 {
	return -0.35
}
func ConcentrationAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func ConcentrationAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:          "Concentration Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       ActionID{SpellID: 19746}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:       ConcentrationAuraDuration(talentPoints),
		Category:       ConcentrationAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Pseudo: []PseudoConfig{
			{PseudoStatPushbackChance, ConcentrationAuraValue(talentPoints), false, 0},
		},
	})
}

// Trueshot Aura - https://www.wowhead.com/forever/spell=20906
// the rank ladder is not monotonic: rank 5 (20906) is worth 50 where rank 4 (20905) is worth 75, and the top rank is what the constructor states
func TrueshotAuraValue(talentPoints int32) float64 {
	return 50.0
}
func TrueshotAuraDuration(talentPoints int32) time.Duration {
	return 1800000 * time.Millisecond
}
func TrueshotAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Trueshot Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 20906}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: TrueshotAuraDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.RangedAttackPower, TrueshotAuraValue(talentPoints), false},
		},
	})
}

// Atiesh - Mage - https://www.wowhead.com/forever/spell=28142
func AtieshMageValue(talentPoints int32) float64 {
	return 2.0
}
func AtieshMageDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func AtieshMageAura(unit *Unit, isPlayer bool, talentPoints int32, count float64) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Atiesh - Mage (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 28142}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshMageDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.SpellCritPercent, AtieshMageValue(talentPoints) * count, false},
		},
	})
}

// Atiesh - Warlock - https://www.wowhead.com/forever/spell=28143
func AtieshWarlockValue(talentPoints int32) float64 {
	return 33.0
}
func AtieshWarlockDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func AtieshWarlockAura(unit *Unit, isPlayer bool, talentPoints int32, count float64) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Atiesh - Warlock (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 28143}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshWarlockDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.SpellDamage, AtieshWarlockValue(talentPoints) * count, false},
			{stats.HealingPower, 33.0 * count, false},
		},
	})
}

// Strength of Earth Totem - https://www.wowhead.com/forever/spell=25362
var StrengthOfEarthTotemCategory = "StrengthOfEarthTotem"

func StrengthOfEarthTotemValue(talentPoints int32) float64 {
	return 53.0
}
func StrengthOfEarthTotemDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func StrengthOfEarthTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Strength of Earth Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 25362}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: StrengthOfEarthTotemDuration(talentPoints),
		Category: StrengthOfEarthTotemCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Strength, StrengthOfEarthTotemValue(talentPoints), false},
		},
	})
}

// Grace of Air Totem - https://www.wowhead.com/forever/spell=25360
var GraceOfAirTotemCategory = "GraceOfAirTotem"

func GraceOfAirTotemValue(talentPoints int32) float64 {
	return 89.0
}
func GraceOfAirTotemDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func GraceOfAirTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Grace of Air Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 25360}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: GraceOfAirTotemDuration(talentPoints),
		Category: GraceOfAirTotemCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Agility, GraceOfAirTotemValue(talentPoints), false},
		},
	})
}

// Windfury Totem - https://www.wowhead.com/forever/spell=10610
var WindfuryTotemCategory = "WindfuryTotem"

func WindfuryTotemValue(talentPoints int32) float64 {
	return 246.0
}
func WindfuryTotemDuration(talentPoints int32) time.Duration {
	return 1000 * time.Millisecond
}
func WindfuryTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Windfury Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10610}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: WindfuryTotemDuration(talentPoints),
		Category: WindfuryTotemCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.AttackPower, WindfuryTotemValue(talentPoints), false},
		},
	})
}

// Frost Resistance Totem - https://www.wowhead.com/forever/spell=10477
func FrostResistanceTotemValue(talentPoints int32) float64 {
	return 60.0
}
func FrostResistanceTotemDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func FrostResistanceTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Frost Resistance Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10477}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: FrostResistanceTotemDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.FrostResistance, FrostResistanceTotemValue(talentPoints), false},
		},
	})
}

// Nature Resistance Totem - https://www.wowhead.com/forever/spell=10599
func NatureResistanceTotemValue(talentPoints int32) float64 {
	return 60.0
}
func NatureResistanceTotemDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func NatureResistanceTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Nature Resistance Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10599}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: NatureResistanceTotemDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.NatureResistance, NatureResistanceTotemValue(talentPoints), false},
		},
	})
}

// Fire Resistance Totem - https://www.wowhead.com/forever/spell=10535
func FireResistanceTotemValue(talentPoints int32) float64 {
	return 60.0
}
func FireResistanceTotemDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func FireResistanceTotemAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Fire Resistance Totem (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10535}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: FireResistanceTotemDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.FireResistance, FireResistanceTotemValue(talentPoints), false},
		},
	})
}

// Frost Resistance Aura - https://www.wowhead.com/forever/spell=19898
var FrostResistanceAuraCategory = "FrostResistanceAura"

func FrostResistanceAuraValue(talentPoints int32) float64 {
	return 60.0
}
func FrostResistanceAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func FrostResistanceAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:          "Frost Resistance Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       ActionID{SpellID: 19898}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:       FrostResistanceAuraDuration(talentPoints),
		Category:       FrostResistanceAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []StatConfig{
			{stats.FrostResistance, FrostResistanceAuraValue(talentPoints), false},
		},
	})
}

// Fire Resistance Aura - https://www.wowhead.com/forever/spell=19900
var FireResistanceAuraCategory = "FireResistanceAura"

func FireResistanceAuraValue(talentPoints int32) float64 {
	return 60.0
}
func FireResistanceAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func FireResistanceAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:          "Fire Resistance Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       ActionID{SpellID: 19900}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:       FireResistanceAuraDuration(talentPoints),
		Category:       FireResistanceAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []StatConfig{
			{stats.FireResistance, FireResistanceAuraValue(talentPoints), false},
		},
	})
}

// Shadow Resistance Aura - https://www.wowhead.com/forever/spell=19896
var ShadowResistanceAuraCategory = "ShadowResistanceAura"

func ShadowResistanceAuraValue(talentPoints int32) float64 {
	return 60.0
}
func ShadowResistanceAuraDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func ShadowResistanceAuraAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:          "Shadow Resistance Aura (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       ActionID{SpellID: 19896}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:       ShadowResistanceAuraDuration(talentPoints),
		Category:       ShadowResistanceAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []StatConfig{
			{stats.ShadowResistance, ShadowResistanceAuraValue(talentPoints), false},
		},
	})
}

// Aspect of the Wild - https://www.wowhead.com/forever/spell=20190
func AspectOfTheWildValue(talentPoints int32) float64 {
	return 60.0
}
func AspectOfTheWildDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func AspectOfTheWildAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Aspect of the Wild (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 20190}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: AspectOfTheWildDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.NatureResistance, AspectOfTheWildValue(talentPoints), false},
		},
	})
}

// Atiesh - Druid - https://www.wowhead.com/forever/spell=28145
func AtieshDruidValue(talentPoints int32) float64 {
	return 11.0
}
func AtieshDruidDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func AtieshDruidAura(unit *Unit, isPlayer bool, talentPoints int32, count float64) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Atiesh - Druid (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 28145}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshDruidDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.MP5, AtieshDruidValue(talentPoints) * count, false},
		},
	})
}

// Atiesh - Priest - https://www.wowhead.com/forever/spell=28144
func AtieshPriestValue(talentPoints int32) float64 {
	return 62.0
}
func AtieshPriestDuration(talentPoints int32) time.Duration {
	return NeverExpires
}
func AtieshPriestAura(unit *Unit, isPlayer bool, talentPoints int32, count float64) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Atiesh - Priest (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 28144}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshPriestDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.HealingPower, AtieshPriestValue(talentPoints) * count, false},
		},
	})
}

// func TotemTwistingAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura // totem_twisting, KindFlag: sim behaviour toggle with no spell source; rendered under Other Inputs.

// Arcane Brilliance - https://www.wowhead.com/forever/spell=23028
var ArcaneBrillianceCategory = "StatBuff"

func ArcaneBrillianceValue(talentPoints int32) float64 {
	return 31.0
}
func ArcaneBrillianceDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func ArcaneBrillianceAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Arcane Brilliance (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 23028}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: ArcaneBrillianceDuration(talentPoints),
		Category: ArcaneBrillianceCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Intellect, ArcaneBrillianceValue(talentPoints), false},
		},
	})
}

// Blessing of Kings - https://www.wowhead.com/forever/spell=20217
func BlessingOfKingsValue(talentPoints int32) float64 {
	return 1.1
}
func BlessingOfKingsDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func BlessingOfKingsAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Blessing of Kings (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 20217}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: BlessingOfKingsDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Strength, BlessingOfKingsValue(talentPoints), true},
			{stats.Agility, 1.1, true},
			{stats.Stamina, 1.1, true},
			{stats.Intellect, 1.1, true},
			{stats.Spirit, 1.1, true},
		},
	})
}

// Divine Spirit - https://www.wowhead.com/forever/spell=27841
var DivineSpiritCategory = "StatBuff"

func DivineSpiritValue(talentPoints int32) float64 {
	return 40.0
}
func DivineSpiritDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func DivineSpiritAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Divine Spirit (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 27841}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: DivineSpiritDuration(talentPoints),
		Category: DivineSpiritCategory,
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Spirit, DivineSpiritValue(talentPoints), false},
		},
	})
}

// Gift of the Wild - https://www.wowhead.com/forever/spell=21850
func GiftOfTheWildValue(talentPoints int32) float64 {
	return 385.0
}
func GiftOfTheWildDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GiftOfTheWildAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Gift of the Wild (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 21850}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: GiftOfTheWildDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Armor, GiftOfTheWildValue(talentPoints), false},
			{stats.Strength, 16.0, false},
			{stats.Agility, 16.0, false},
			{stats.Stamina, 16.0, false},
			{stats.Intellect, 16.0, false},
			{stats.Spirit, 16.0, false},
			{stats.FireResistance, 27.0, false},
			{stats.NatureResistance, 27.0, false},
			{stats.FrostResistance, 27.0, false},
			{stats.ShadowResistance, 27.0, false},
			{stats.ArcaneResistance, 27.0, false},
		},
	})
}

// Thorns - https://www.wowhead.com/forever/spell=9910
var ThornsCategory = "Thorns"

func ThornsValue(talentPoints int32) float64 {
	return 22.0
}
func ThornsDuration(talentPoints int32) time.Duration {
	return 600000 * time.Millisecond
}
func ThornsAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedDamageShield(unit, GeneratedBuff{
		Label:      "Thorns (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   ActionID{SpellID: 9910}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration:   ThornsDuration(talentPoints),
		Category:   ThornsCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
	}, SpellSchoolNature, ThornsValue(talentPoints))
}

// Power Word: Fortitude - https://www.wowhead.com/forever/spell=10938
func PowerWordFortitudeValue(talentPoints int32) float64 {
	return 70.0
}
func PowerWordFortitudeDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func PowerWordFortitudeAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Power Word: Fortitude (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10938}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: PowerWordFortitudeDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.Stamina, PowerWordFortitudeValue(talentPoints), false},
		},
	})
}

// Blessing of Might - https://www.wowhead.com/forever/spell=25291
func BlessingOfMightValue(talentPoints int32) float64 {
	return 133.0
}
func BlessingOfMightDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func BlessingOfMightAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Blessing of Might (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 25291}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: BlessingOfMightDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.AttackPower, BlessingOfMightValue(talentPoints), false},
		},
	})
}

// Blessing of Wisdom - https://www.wowhead.com/forever/spell=25290
func BlessingOfWisdomValue(talentPoints int32) float64 {
	return 40.0
}
func BlessingOfWisdomDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func BlessingOfWisdomAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Blessing of Wisdom (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 25290}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: BlessingOfWisdomDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.MP5, BlessingOfWisdomValue(talentPoints), false},
		},
	})
}

// Blessing of Salvation - https://www.wowhead.com/forever/spell=1038
func BlessingOfSalvationValue(talentPoints int32) float64 {
	return 0.7
}
func BlessingOfSalvationDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func BlessingOfSalvationAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Blessing of Salvation (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 1038}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: BlessingOfSalvationDuration(talentPoints),
		IsPlayer: isPlayer,
		Pseudo: []PseudoConfig{
			{PseudoStatThreatMultiplier, BlessingOfSalvationValue(talentPoints), true, 0},
		},
	})
}

// Shadow Protection - https://www.wowhead.com/forever/spell=10958
func ShadowProtectionValue(talentPoints int32) float64 {
	return 60.0
}
func ShadowProtectionDuration(talentPoints int32) time.Duration {
	return 600000 * time.Millisecond
}
func ShadowProtectionAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Shadow Protection (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10958}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: ShadowProtectionDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []StatConfig{
			{stats.ShadowResistance, ShadowProtectionValue(talentPoints), false},
		},
	})
}

// Innervates - https://www.wowhead.com/forever/spell=29166
var InnervatesCategory = "Innervate"

func InnervatesDuration(talentPoints int32) time.Duration {
	return 20000 * time.Millisecond
}
func InnervatesCooldown() time.Duration {
	return 360000 * time.Millisecond
}
func InnervatesAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Innervates (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 29166}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: InnervatesDuration(talentPoints),
		Category: InnervatesCategory,
		IsPlayer: isPlayer,
	})
}

// Power Infusions - https://www.wowhead.com/forever/spell=10060
var PowerInfusionsCategory = "PowerInfusion"

func PowerInfusionsValue(talentPoints int32) float64 {
	return 1.2
}
func PowerInfusionsDuration(talentPoints int32) time.Duration {
	return 15000 * time.Millisecond
}
func PowerInfusionsCooldown() time.Duration {
	return 180000 * time.Millisecond
}
func PowerInfusionsAura(unit *Unit, isPlayer bool, talentPoints int32) *Aura {
	return newGeneratedStatAura(unit, GeneratedBuff{
		Label:    "Power Infusions (" + Ternary(isPlayer, "Player", "External") + ")",
		ActionID: ActionID{SpellID: 10060}.WithTag(TernaryInt32(isPlayer, 0, -1)),
		Duration: PowerInfusionsDuration(talentPoints),
		Category: PowerInfusionsCategory,
		IsPlayer: isPlayer,
		Pseudo: []PseudoConfig{
			{PseudoStatHealingDealtMultiplier, PowerInfusionsValue(talentPoints), true, 0},
			{PseudoStatSchoolDamageDealtMultiplier, 1.2, true, 126},
		},
	})
}

func applyGeneratedBuffs(char *Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	if party.BloodPact {
		MakePermanent(BloodPactAura(&char.Unit, false, 0))
	}
	if party.CommandingShout {
		driveCommandingShout(char, party)
	}
	if party.BattleShout {
		driveBattleShout(char, party)
	}
	if party.DevotionAura {
		MakePermanent(DevotionAuraAura(&char.Unit, false, 0))
	}
	if party.LeaderOfThePack {
		MakePermanent(LeaderOfThePackAura(&char.Unit, false, 0))
	}
	if party.ManaSpringTotem != proto.TristateEffect_TristateEffectMissing {
		MakePermanent(ManaSpringTotemAura(&char.Unit, false, GetTristateValueInt32(party.ManaSpringTotem, 0, 5)))
	}
	if party.ManaTideTotems > 0 {
		driveManaTideTotems(char, party)
	}
	if individual.ShadowPriestDps > 0 {
		driveShadowPriestDps(char, individual)
	}
	if party.MoonkinAura {
		MakePermanent(MoonkinAuraAura(&char.Unit, false, 0))
	}
	if party.RetributionAura {
		MakePermanent(RetributionAuraAura(&char.Unit, false, 0))
	}
	if party.ConcentrationAura {
		MakePermanent(ConcentrationAuraAura(&char.Unit, false, 0))
	}
	if party.TrueshotAura {
		MakePermanent(TrueshotAuraAura(&char.Unit, false, 0))
	}
	if party.AtieshMage > 0 {
		driveAtieshMage(char, party)
	}
	if party.AtieshWarlock > 0 {
		driveAtieshWarlock(char, party)
	}
	if party.StrengthOfEarthTotem {
		MakePermanent(StrengthOfEarthTotemAura(&char.Unit, false, 0))
	}
	if party.GraceOfAirTotem {
		driveGraceOfAirTotem(char, party)
	}
	if party.WindfuryTotem {
		driveWindfuryTotem(char, party)
	}
	if party.FrostResistanceTotem {
		MakePermanent(FrostResistanceTotemAura(&char.Unit, false, 0))
	}
	if party.NatureResistanceTotem {
		MakePermanent(NatureResistanceTotemAura(&char.Unit, false, 0))
	}
	if party.FireResistanceTotem {
		MakePermanent(FireResistanceTotemAura(&char.Unit, false, 0))
	}
	if party.FrostResistanceAura {
		MakePermanent(FrostResistanceAuraAura(&char.Unit, false, 0))
	}
	if party.FireResistanceAura {
		MakePermanent(FireResistanceAuraAura(&char.Unit, false, 0))
	}
	if party.ShadowResistanceAura {
		MakePermanent(ShadowResistanceAuraAura(&char.Unit, false, 0))
	}
	if party.AspectOfTheWild {
		MakePermanent(AspectOfTheWildAura(&char.Unit, false, 0))
	}
	if party.AtieshDruid > 0 {
		driveAtieshDruid(char, party)
	}
	if party.AtieshPriest > 0 {
		driveAtieshPriest(char, party)
	}
	if raid.ArcaneBrilliance {
		MakePermanent(ArcaneBrillianceAura(&char.Unit, false, 0))
	}
	if individual.BlessingOfKings {
		MakePermanent(BlessingOfKingsAura(&char.Unit, false, 0))
	}
	if raid.DivineSpirit {
		MakePermanent(DivineSpiritAura(&char.Unit, false, 0))
	}
	if raid.GiftOfTheWild {
		MakePermanent(GiftOfTheWildAura(&char.Unit, false, 0))
	}
	if raid.Thorns {
		MakePermanent(ThornsAura(&char.Unit, false, 0))
	}
	if raid.PowerWordFortitude {
		MakePermanent(PowerWordFortitudeAura(&char.Unit, false, 0))
	}
	if individual.BlessingOfMight {
		MakePermanent(BlessingOfMightAura(&char.Unit, false, 0))
	}
	if individual.BlessingOfWisdom {
		MakePermanent(BlessingOfWisdomAura(&char.Unit, false, 0))
	}
	if individual.BlessingOfSalvation {
		MakePermanent(BlessingOfSalvationAura(&char.Unit, false, 0))
	}
	if raid.ShadowProtection {
		MakePermanent(ShadowProtectionAura(&char.Unit, false, 0))
	}
	if individual.Innervates > 0 {
		driveInnervates(char, individual)
	}
	if individual.PowerInfusions > 0 {
		drivePowerInfusions(char, individual)
	}
}

// What a pet is given of its owner's buffs, by the policy each manifest row
// states. A buff the owner's raid casts on the party reaches the pet as well
// unless the row says otherwise: PetStrip is for one the pet cannot use or is
// given during the fight instead, PetInheritOwnerAura for a neck the pet picks
// up by standing next to the wearer, and PetStripWhenSummonedLate for one that
// is cast on whoever is there when the fight starts. PetCapAtRegular says a
// pet's share of the buff is the unimproved amount, which every row that states
// it now grants anyway, so nothing is emitted for it.
func applyGeneratedPetBuffs(pet *Pet, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	party.WindfuryTotem = false
	raid.Thorns = false
	individual.Innervates = 0
	individual.PowerInfusions = 0

	if !pet.enabledOnStart {
		individual.ShadowPriestDps = 0
		raid.ArcaneBrilliance = false
		individual.BlessingOfKings = false
		raid.DivineSpirit = false
		raid.GiftOfTheWild = false
		raid.PowerWordFortitude = false
		individual.BlessingOfMight = false
		individual.BlessingOfWisdom = false
		individual.BlessingOfSalvation = false
		raid.ShadowProtection = false
	}
}
