// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

import { Class, Stat } from '@generated/proto/common';
import { ActionId } from '@sim/proto/action_id';
import {
	makeBooleanDebuffInput,
	makeBooleanIndividualBuffInput,
	makeBooleanPartyBuffInput,
	makeBooleanRaidBuffInput,
	makeMultistateIndividualBuffInput,
	makeMultistatePartyBuffInput,
	makeTristatePartyBuffInput,
} from '@ui-kit/icon_inputs';

import type { RenderableStatOptions } from './stat_options';

// StatOption does not declare ownerClass, so the generated rows widen it here.
export type GeneratedStatOption = RenderableStatOptions & { ownerClass?: Class };

export const BloodPact = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(11767),
	fieldName: 'bloodPact',
	label: 'Blood Pact',
});

export const CommandingShout = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(403215),
	fieldName: 'commandingShout',
	label: 'Commanding Shout',
});

export const BattleShout = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(25289),
	fieldName: 'battleShout',
	label: 'Battle Shout',
});

// bs_solarian_sapphire: second state of the Battle Shout quadstate input; item 30446 has no Item row.

export const DevotionAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10293),
	fieldName: 'devotionAura',
	label: 'Devotion Aura',
});

// ferocious_inspiration: no SpellName row for Ferocious Inspiration.

export const LeaderOfThePack = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(24932),
	fieldName: 'leaderOfThePack',
	label: 'Leader of the Pack',
});

export const ManaSpringTotem = makeTristatePartyBuffInput({
	actionId: ActionId.fromSpellId(10494),
	impId: ActionId.fromSpellId(16187),
	fieldName: 'manaSpringTotem',
	label: 'Mana Spring',
});

export const ManaTideTotems = makeMultistatePartyBuffInput({
	actionId: ActionId.fromSpellId(17360),
	numStates: 5,
	fieldName: 'manaTideTotems',
	label: 'Mana Tide Totem',
});

// shadow_priest_dps: the returned mana is typed in by hand and the input renders in the party registry over an individual-buff field.

export const MoonkinAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(24907),
	fieldName: 'moonkinAura',
	label: 'Moonkin Aura',
});

export const RetributionAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10301),
	fieldName: 'retributionAura',
	label: 'Retribution Aura',
});

export const ConcentrationAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(19746),
	fieldName: 'concentrationAura',
	label: 'Concentration Aura',
});

// sanctity_aura: SpellName 20218 exists but has no SkillLineAbility row and no node in paladin tree 1100.

// totem_of_wrath: no SpellName row for Totem of Wrath.

export const TrueshotAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(20906),
	fieldName: 'trueshotAura',
	label: 'Trueshot Aura',
});

// wrath_of_air_totem: no SpellName row for Wrath of Air Totem.

// unleashed_rage: spells 30802-30811 exist but have no SkillLineAbility row and no node in shaman tree 1082.

export const AtieshMage = makeMultistatePartyBuffInput({
	actionId: ActionId.fromSpellId(28142),
	numStates: 5,
	fieldName: 'atieshMage',
	label: 'Atiesh - Mage',
});

export const AtieshWarlock = makeMultistatePartyBuffInput({
	actionId: ActionId.fromSpellId(28143),
	numStates: 5,
	fieldName: 'atieshWarlock',
	label: 'Atiesh - Warlock',
});

// braided_eternium_chain: spell 31025 has no SpellName row and the neck has no Item row.

// chain_of_the_twilight_owl: spell 31035 has no SpellName row and the neck has no Item row.

// draenei_racial_caster: spell 28878 has no SpellName row.

// draenei_racial_melee: spell 6562 has no SpellName row.

// eye_of_the_night: spell 31033 has no SpellName row and the neck has no Item row.

// jade_pendant_of_blasting: spell 25607 has no SpellName row and the neck has no Item row.

export const StrengthOfEarthTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(25362),
	fieldName: 'strengthOfEarthTotem',
	label: 'Strength of Earth',
});

// soe_enhancement_2pt4: second state of the Strength of Earth quadstate input; set-bonus spell 37223 has no SpellName row.

export const GraceOfAirTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(25360),
	fieldName: 'graceOfAirTotem',
	label: 'Grace of Air',
});

export const WindfuryTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10610),
	fieldName: 'windfuryTotem',
	label: 'Windfury Totem',
});

// drums: the drum items are not in the client; the UI keeps a hand-written swatch row over this field.

export const FrostResistanceTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10477),
	fieldName: 'frostResistanceTotem',
	label: 'Frost Resistance',
});

export const NatureResistanceTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10599),
	fieldName: 'natureResistanceTotem',
	label: 'Nature Resistance',
});

export const FireResistanceTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10535),
	fieldName: 'fireResistanceTotem',
	label: 'Fire Resistance',
});

export const FrostResistanceAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(19898),
	fieldName: 'frostResistanceAura',
	label: 'Frost Resistance Aura',
});

export const FireResistanceAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(19900),
	fieldName: 'fireResistanceAura',
	label: 'Fire Resistance Aura',
});

export const ShadowResistanceAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(19896),
	fieldName: 'shadowResistanceAura',
	label: 'Shadow Resistance Aura',
});

export const AspectOfTheWild = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(20190),
	fieldName: 'aspectOfTheWild',
	label: 'Aspect of the Wild',
});

// atiesh_druid: no settings input over this field.

// atiesh_priest: no settings input over this field.

// snapshot_improved_wrath_of_air_totem: totem-twisting snapshot toggle with no spell source.

// snapshot_improved_strength_of_earth_totem: totem-twisting snapshot toggle with no spell source.

// tranquil_air_totem: the aura Tranquil Air (25909) exists but there is no Tranquil Air Totem cast and no SkillLineAbility row.

// totem_twisting: sim behaviour toggle with no spell source; rendered under Other Inputs.

// snapshot_bs_solarian_sapphire: shout snapshot toggle with no spell source.

// snapshot_bs_t2: shout snapshot toggle with no spell source.

// snapshot_bs_booming_voice_rank: shout snapshot rank counter; Booming Voice (12321) modifies radius only, so the rank has no effect on Battle Shout.

export const ArcaneBrilliance = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(23028),
	fieldName: 'arcaneBrilliance',
	label: 'Arcane Brilliance',
});

export const BlessingOfKings = makeBooleanIndividualBuffInput({
	actionId: ActionId.fromSpellId(20217),
	fieldName: 'blessingOfKings',
	label: 'Blessing of Kings',
});

// bloodlust: the raid cooldown keeps its hand-written input and driver; no SkillLineAbility row anchors the name to a shaman.

export const DivineSpirit = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(27841),
	fieldName: 'divineSpirit',
	label: 'Divine Spirit',
});

export const GiftOfTheWild = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(21850),
	fieldName: 'giftOfTheWild',
	label: 'Gift of the Wild',
});

export const Thorns = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(9910),
	fieldName: 'thorns',
	label: 'Thorns',
});

export const PowerWordFortitude = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(10938),
	fieldName: 'powerWordFortitude',
	label: 'Power Word: Fortitude',
});

export const BlessingOfMight = makeBooleanIndividualBuffInput({
	actionId: ActionId.fromSpellId(25291),
	fieldName: 'blessingOfMight',
	label: 'Blessing of Might',
});

export const BlessingOfWisdom = makeBooleanIndividualBuffInput({
	actionId: ActionId.fromSpellId(25290),
	fieldName: 'blessingOfWisdom',
	label: 'Blessing of Wisdom',
});

// blessing_of_sanctuary: no SpellName row for Blessing of Sanctuary.

// blessing_of_salvation: the hand-written input hides itself for tank and healing specs, a role gate no manifest row carries.

export const ShadowProtection = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(10958),
	fieldName: 'shadowProtection',
	label: 'Shadow Protection',
});

export const Innervates = makeMultistateIndividualBuffInput({
	actionId: ActionId.fromSpellId(29166),
	numStates: 11,
	fieldName: 'innervates',
	label: 'Innervates',
});

export const PowerInfusions = makeMultistateIndividualBuffInput({
	actionId: ActionId.fromSpellId(10060),
	numStates: 11,
	fieldName: 'powerInfusions',
	label: 'Power Infusions',
});

// blood_frenzy: spells 403352/412507/445285/445286 exist but have no SkillLineAbility row and no node in warrior tree 1117.

export const HuntersMark = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(14325),
	fieldName: 'huntersMark',
	label: "Hunter's Mark",
});

// improved_scorch: the debuff 22959 (Fire Vulnerability) is aura 270 A_MOD_SCHOOL_MASK_DAMAGE_FROM_CASTER, so it only benefits the mage that applied it.

export const ImprovedSealOfTheCrusader = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(20303),
	fieldName: 'improvedSealOfTheCrusader',
	label: 'Seal of the Crusader',
});

// joc_retribution_2pt4: second state of the Seal of the Crusader quadstate input; set-bonus spell 37186 has no SpellName row.

export const JudgementOfLight = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(20346),
	fieldName: 'judgementOfLight',
	label: 'Judgement of Light',
});

export const JudgementOfWisdom = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(20355),
	fieldName: 'judgementOfWisdom',
	label: 'Judgement of Wisdom',
});

export const Mangle = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(1238073),
	fieldName: 'mangle',
	label: 'Mangle',
});

// misery: no SpellName row for Misery.

// shadow_weaving: the debuff 15258 is aura 270 A_MOD_SCHOOL_MASK_DAMAGE_FROM_CASTER, so it only benefits the priest that applied it.

export const CurseOfElements = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(1311680),
	fieldName: 'curseOfElements',
	label: 'Curse of the Elements',
});

export const CurseOfRecklessness = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11717),
	fieldName: 'curseOfRecklessness',
	label: 'Curse of Recklessness',
});

export const FaerieFire = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(9907),
	fieldName: 'faerieFire',
	label: 'Faerie Fire',
});

export const ExposeArmor = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11198),
	fieldName: 'exposeArmor',
	label: 'Expose Armor',
});

export const SunderArmor = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11597),
	fieldName: 'sunderArmor',
	label: 'Sunder Armor',
});

// winters_chill: the debuff 12579 is aura 308 A_MOD_CRIT_CHANCE_FOR_CASTER_WITH_ABILITIES, so it only benefits the mage that applied it; the name also resolves
// to the talent 11180 rather than to the debuff.

export const GiftOfArthas = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11374),
	fieldName: 'giftOfArthas',
	label: 'Gift of Arthas',
});

export const DemoralizingRoar = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(9898),
	fieldName: 'demoralizingRoar',
	label: 'Demoralizing Roar',
});

export const DemoralizingShout = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11556),
	fieldName: 'demoralizingShout',
	label: 'Demoralizing Shout',
});

// screech: no SpellName row for Screech.

export const ThunderClap = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11581),
	fieldName: 'thunderClap',
	label: 'Thunder Clap',
});

export const InsectSwarm = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(24977),
	fieldName: 'insectSwarm',
	label: 'Insect Swarm',
});

export const ScorpidSting = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(3043),
	fieldName: 'scorpidSting',
	label: 'Scorpid Sting',
});

// shadow_embrace: no SpellName row for Shadow Embrace.

// isb_uptime: Improved Shadow Bolt (17793) is a single dummy effect with no trigger spell and the debuff 17800 has no SpellName row.

// expose_weakness_uptime: spells 7140/23577/23578 exist but have no SkillLineAbility row and no node in hunter tree 1091.

// expose_weakness_hunter_agility: input for the absent Expose Weakness row; spells 7140/23577/23578 have no SkillLineAbility row.

// hemorrhage_uptime: Hemorrhage (16511) effect 2 is aura 271 A_MOD_SPELL_DAMAGE_FROM_CASTER, so it only benefits the rogue that applied it.

export const GENERATED_RAID_BUFFS_CONFIG: GeneratedStatOption[] = [
	{
		config: ArcaneBrilliance,
		stats: [Stat.StatIntellect],
		ownerClass: Class.ClassMage,
	},
	{
		config: DivineSpirit,
		stats: [Stat.StatSpirit, Stat.StatSpellDamage],
		ownerClass: Class.ClassPriest,
	},
	{
		config: GiftOfTheWild,
		stats: [Stat.StatArmor, Stat.StatStrength, Stat.StatAgility, Stat.StatIntellect, Stat.StatSpirit, Stat.StatStamina],
		ownerClass: Class.ClassDruid,
	},
	{
		config: Thorns,
		stats: [Stat.StatResilienceRating, Stat.StatDefenseRating, Stat.StatStamina],
		ownerClass: Class.ClassDruid,
	},
	{
		config: PowerWordFortitude,
		stats: [Stat.StatStamina],
		ownerClass: Class.ClassPriest,
	},
	{
		config: ShadowProtection,
		stats: [Stat.StatShadowResistance, Stat.StatStamina],
		ownerClass: Class.ClassPriest,
	},
];

export const GENERATED_PARTY_BUFFS_CONFIG: GeneratedStatOption[] = [
	{
		config: BloodPact,
		stats: [Stat.StatStamina],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: CommandingShout,
		stats: [Stat.StatStamina],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: BattleShout,
		stats: [Stat.StatAttackPower, Stat.StatRangedAttackPower],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: DevotionAura,
		stats: [Stat.StatArmor],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: LeaderOfThePack,
		stats: [Stat.StatAttackPower, Stat.StatMeleeCritRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ManaSpringTotem,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassShaman,
	},
	{
		config: ManaTideTotems,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassShaman,
	},
	{
		config: MoonkinAura,
		stats: [Stat.StatSpellCritRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: RetributionAura,
		stats: [Stat.StatResilienceRating, Stat.StatArmor, Stat.StatDefenseRating],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: ConcentrationAura,
		stats: [Stat.StatDefenseRating],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: TrueshotAura,
		stats: [Stat.StatAttackPower, Stat.StatRangedAttackPower],
		ownerClass: Class.ClassHunter,
	},
	{
		config: AtieshMage,
		stats: [Stat.StatSpellDamage, Stat.StatHealingPower],
		ownerClass: Class.ClassMage,
	},
	{
		config: AtieshWarlock,
		stats: [Stat.StatSpellDamage, Stat.StatHealingPower],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: StrengthOfEarthTotem,
		stats: [Stat.StatStrength],
		ownerClass: Class.ClassShaman,
	},
	{
		config: GraceOfAirTotem,
		stats: [Stat.StatAgility],
		ownerClass: Class.ClassShaman,
	},
	{
		config: WindfuryTotem,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassShaman,
	},
	{
		config: FrostResistanceTotem,
		stats: [Stat.StatFrostResistance],
		ownerClass: Class.ClassShaman,
	},
	{
		config: NatureResistanceTotem,
		stats: [Stat.StatNatureResistance],
		ownerClass: Class.ClassShaman,
	},
	{
		config: FireResistanceTotem,
		stats: [Stat.StatFireResistance],
		ownerClass: Class.ClassShaman,
	},
	{
		config: FrostResistanceAura,
		stats: [Stat.StatFrostResistance],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: FireResistanceAura,
		stats: [Stat.StatFireResistance],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: ShadowResistanceAura,
		stats: [Stat.StatShadowResistance],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: AspectOfTheWild,
		stats: [Stat.StatNatureResistance],
		ownerClass: Class.ClassHunter,
	},
];

export const GENERATED_INDIVIDUAL_BUFFS_CONFIG: GeneratedStatOption[] = [
	{
		config: BlessingOfKings,
		stats: [Stat.StatAgility, Stat.StatIntellect, Stat.StatSpirit, Stat.StatStamina, Stat.StatStrength],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: BlessingOfMight,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: BlessingOfWisdom,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: Innervates,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassDruid,
	},
	{
		config: PowerInfusions,
		stats: [Stat.StatSpellHasteRating],
		ownerClass: Class.ClassPriest,
	},
];

export const GENERATED_DEBUFFS_CONFIG: GeneratedStatOption[] = [
	{
		config: HuntersMark,
		stats: [Stat.StatRangedAttackPower, Stat.StatAttackPower],
		ownerClass: Class.ClassHunter,
	},
	{
		config: ImprovedSealOfTheCrusader,
		stats: [Stat.StatMeleeCritRating, Stat.StatSpellCritRating],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: JudgementOfLight,
		stats: [Stat.StatResilienceRating],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: JudgementOfWisdom,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: Mangle,
		stats: [],
		ownerClass: Class.ClassDruid,
	},
	{
		config: CurseOfElements,
		stats: [Stat.StatSpellDamage],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: CurseOfRecklessness,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: FaerieFire,
		stats: [Stat.StatAttackPower, Stat.StatMeleeHitRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ExposeArmor,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassRogue,
	},
	{
		config: SunderArmor,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: GiftOfArthas,
		stats: [Stat.StatAttackPower, Stat.StatResilienceRating],
	},
	{
		config: DemoralizingRoar,
		stats: [Stat.StatStamina, Stat.StatResilienceRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: DemoralizingShout,
		stats: [Stat.StatStamina, Stat.StatResilienceRating],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: ThunderClap,
		stats: [Stat.StatStamina, Stat.StatResilienceRating],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: InsectSwarm,
		stats: [Stat.StatStamina, Stat.StatResilienceRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ScorpidSting,
		stats: [Stat.StatStamina, Stat.StatResilienceRating],
		ownerClass: Class.ClassHunter,
	},
];
