// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/dbcenums"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/spelldata"
	"github.com/wowsims/forever/sim/core/stats"
)

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var SynthPaladinAuraCategory = "SynthPaladinAura"

// Mana Spring Totem
var SynthManaSpringCategory = "ManaSpringTotem"
var synthManaSpringSpell = spelldata.MustFind(10494)
var synthManaSpringTalent = spelldata.Talent(16187, 5)

func SynthManaSpringValue(talentPoints int32) float64 {
	return manaPerFive(synthManaSpringSpell.Effect(dbcenums.A_PERIODIC_ENERGIZE, 0), talentScaled(amount(synthManaSpringSpell.Effect(dbcenums.A_PERIODIC_ENERGIZE, 0)), synthManaSpringTalent.Rank(talentPoints).EffectN(1)))
}
func SynthManaSpringDuration(talentPoints int32) time.Duration {
	return auraDuration(synthManaSpringSpell)
}
func SynthManaSpringAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Mana Spring Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: synthManaSpringSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthManaSpringDuration(talentPoints),
		Category: SynthManaSpringCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.MP5, Amount: SynthManaSpringValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Blessing of Kings
var synthBlessingOfKingsSpell = spelldata.MustFind(20217)

func SynthBlessingOfKingsValue(talentPoints int32) float64 {
	return 1 + amount(synthBlessingOfKingsSpell.Effect(dbcenums.A_MOD_TOTAL_STAT_PERCENTAGE, 0))/100
}
func SynthBlessingOfKingsDuration(talentPoints int32) time.Duration {
	return auraDuration(synthBlessingOfKingsSpell)
}
func SynthBlessingOfKingsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Blessing of Kings (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: synthBlessingOfKingsSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthBlessingOfKingsDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Strength, Amount: SynthBlessingOfKingsValue(talentPoints), IsMultiplicative: true},
			{Stat: stats.Agility, Amount: 1 + amount(synthBlessingOfKingsSpell.Effect(dbcenums.A_MOD_TOTAL_STAT_PERCENTAGE, 1))/100, IsMultiplicative: true},
		},
	})
}

// Battle Shout
var SynthBattleShoutCategory = "SynthBattleShout"
var synthBattleShoutSpell = spelldata.MustFind(25289)

func SynthBattleShoutValue(talentPoints int32) float64 {
	return amount(synthBattleShoutSpell.Effect(dbcenums.A_MOD_ATTACK_POWER, 0))
}
func SynthBattleShoutDuration(talentPoints int32) time.Duration {
	return auraDuration(synthBattleShoutSpell)
}
func SynthBattleShoutAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:      "Battle Shout (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: synthBattleShoutSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   SynthBattleShoutDuration(talentPoints),
		Category:   SynthBattleShoutCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.AttackPower, Amount: SynthBattleShoutValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Devotion Aura
var SynthDevotionAuraCategory = "DevotionAura"
var synthDevotionAuraSpell = spelldata.MustFind(10293)
var synthDevotionAuraTalent = spelldata.Talent(20140, 2)

func SynthDevotionAuraValue(talentPoints int32) float64 {
	return amount(synthDevotionAuraSpell.Effect(dbcenums.A_MOD_RESISTANCE, 1))
}
func SynthDevotionAuraDuration(talentPoints int32) time.Duration {
	return talentScaledDuration(synthDevotionAuraSpell, synthDevotionAuraTalent.Rank(talentPoints).EffectN(2))
}
func SynthDevotionAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Devotion Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: synthDevotionAuraSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       SynthDevotionAuraDuration(talentPoints),
		Category:       SynthDevotionAuraCategory,
		SharedCategory: SynthPaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: SynthDevotionAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Frost Resistance Aura
var SynthFrostResistanceAuraCategory = "FrostResistanceAura"
var synthFrostResistanceAuraSpell = spelldata.MustFind(19898)

func SynthFrostResistanceAuraValue(talentPoints int32) float64 {
	return amount(synthFrostResistanceAuraSpell.Effect(dbcenums.A_MOD_RESISTANCE, 16))
}
func SynthFrostResistanceAuraDuration(talentPoints int32) time.Duration {
	return auraDuration(synthFrostResistanceAuraSpell)
}
func SynthFrostResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Frost Resistance Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: synthFrostResistanceAuraSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       SynthFrostResistanceAuraDuration(talentPoints),
		Category:       SynthFrostResistanceAuraCategory,
		SharedCategory: SynthPaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.FrostResistance, Amount: SynthFrostResistanceAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Innervates
var SynthInnervatesCategory = "Innervate"
var synthInnervatesSpell = spelldata.MustFind(29166)

func SynthInnervatesDuration(talentPoints int32) time.Duration {
	return auraDuration(synthInnervatesSpell)
}
func SynthInnervatesCooldown() time.Duration {
	return cooldown(synthInnervatesSpell)
}
func SynthInnervatesAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Innervates (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: synthInnervatesSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthInnervatesDuration(talentPoints),
		Category: SynthInnervatesCategory,
		IsPlayer: isPlayer,
	})
}

// Power Infusions
var SynthPowerInfusionsCategory = "PowerInfusion"
var synthPowerInfusionsSpell = spelldata.MustFind(10060)

func SynthPowerInfusionsValue(talentPoints int32) float64 {
	return 1 + amount(synthPowerInfusionsSpell.Effect(dbcenums.A_MOD_DAMAGE_PERCENT_DONE, 126))/100
}
func SynthPowerInfusionsDuration(talentPoints int32) time.Duration {
	return auraDuration(synthPowerInfusionsSpell)
}
func SynthPowerInfusionsCooldown() time.Duration {
	return cooldown(synthPowerInfusionsSpell)
}
func SynthPowerInfusionsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Power Infusions (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: synthPowerInfusionsSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthPowerInfusionsDuration(talentPoints),
		Category: SynthPowerInfusionsCategory,
		IsPlayer: isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatSchoolDamageDealtMultiplier, Amount: SynthPowerInfusionsValue(talentPoints), IsMultiplicative: true, SchoolMask: 126},
			{Kind: core.PseudoStatHealingDealtMultiplier, Amount: 1 + amount(synthPowerInfusionsSpell.Effect(dbcenums.A_MOD_HEALING_DONE_PERCENT, 0))/100, IsMultiplicative: true, SchoolMask: 0},
		},
	})
}

// The label a pet looks for on its owner, and the label the buff's own aura
// carries.
var SynthInheritedNeckAuraLabel = "Inherited Neck"

// func SynthInheritedNeckAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // totem_twisting, KindAbsent: the neck has no Item row

// Atiesh - Mage
var synthAtieshMageSpell = spelldata.MustFind(28142)

func SynthAtieshMageValue(talentPoints int32) float64 {
	return amount(synthAtieshMageSpell.Effect(dbcenums.A_MOD_SPELL_CRIT_CHANCE, 0))
}
func SynthAtieshMageDuration(talentPoints int32) time.Duration {
	return auraDuration(synthAtieshMageSpell)
}
func SynthAtieshMageAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Atiesh - Mage (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: synthAtieshMageSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthAtieshMageDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.SpellCritPercent, Amount: SynthAtieshMageValue(talentPoints) * count, IsMultiplicative: false},
		},
	})
}

// Thorns
var SynthThornsCategory = "Thorns"
var synthThornsSpell = spelldata.MustFind(9910)
var synthThornsTalent = spelldata.Talent(16836, 2)

func SynthThornsValue(talentPoints int32) float64 {
	return talentScaled(amount(synthThornsSpell.Effect(dbcenums.A_DAMAGE_SHIELD, 0)), synthThornsTalent.Rank(talentPoints).EffectN(1))
}
func SynthThornsDuration(talentPoints int32) time.Duration {
	return auraDuration(synthThornsSpell)
}
func SynthThornsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDamageShield(unit, core.GeneratedBuff{
		Label:    "Thorns (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: synthThornsSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthThornsDuration(talentPoints),
		Category: SynthThornsCategory,
		IsPlayer: isPlayer,
	}, core.SpellSchoolNature, SynthThornsValue(talentPoints))
}

func applyGeneratedBuffs(char *core.Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	if party.ManaSpringTotem != proto.TristateEffect_TristateEffectMissing {
		core.MakePermanent(SynthManaSpringAura(&char.Unit, false, core.GetTristateValueInt32(party.ManaSpringTotem, 0, 5)))
	}
	if individual.GreaterBlessingOfKings {
		core.MakePermanent(SynthBlessingOfKingsAura(&char.Unit, false, 0))
	}
	if party.BattleShout != proto.TristateEffect_TristateEffectMissing {
		driveSynthBattleShout(char, party)
	}
	if party.DevotionAura {
		core.MakePermanent(SynthDevotionAuraAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceAura {
		core.MakePermanent(SynthFrostResistanceAuraAura(&char.Unit, false, 0))
	}
	if individual.Innervates > 0 {
		driveSynthInnervates(char, individual)
	}
	if individual.PowerInfusions > 0 {
		driveSynthPowerInfusions(char, individual)
	}
	if party.AtieshMage > 0 {
		driveSynthAtieshMage(char, party)
	}
	if raid.Thorns {
		core.MakePermanent(SynthThornsAura(&char.Unit, false, 0))
	}
}

// What a pet is given of its owner's buffs, by the policy each manifest row
// states. A buff the owner's raid casts on the party reaches the pet as well
// unless the row says otherwise: PetStrip is for one the pet cannot use or is
// given during the fight instead, PetInheritOwnerAura for a neck the pet picks
// up by standing next to the wearer, and PetStripWhenSummonedLate for one that
// is cast on whoever is there when the fight starts. PetCapAtRegular says a
// pet's share of the buff is the unimproved amount, which every row that states
// it now grants anyway, so nothing is emitted for it.
func applyGeneratedPetBuffs(pet *core.Pet, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	raid.Thorns = false
	party.TotemTwisting = party.TotemTwisting || pet.Owner.HasAura(SynthInheritedNeckAuraLabel)

	if !pet.EnabledOnStart() {
		individual.GreaterBlessingOfKings = false
	}
}
