// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/stats"
)

// Thunder Clap - https://www.wowhead.com/forever/spell=11581
var SynthThunderClapCategory = "AtkSpdReduction"

func SynthThunderClapValue(talentPoints int32) float64 {
	return []float64{0.8, 0.78, 0.76}[talentPoints]
}
func SynthThunderClapDuration(talentPoints int32) time.Duration {
	return 30000 * time.Millisecond
}
func SynthThunderClapAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:    "Thunder Clap (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 11581}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: SynthThunderClapDuration(talentPoints),
		Category: SynthThunderClapCategory,
		IsPlayer: isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatMeleeSpeedMultiplier, Amount: SynthThunderClapValue(talentPoints), IsMultiplicative: true, SchoolMask: 0},
		},
	})
}

// Sunder Armor - https://www.wowhead.com/forever/spell=11597
var SynthSunderArmorCategory = "MajorArmorReduction"

func SynthSunderArmorValue(talentPoints int32) float64 {
	return -450.0
}
func SynthSunderArmorDuration(talentPoints int32) time.Duration {
	return 30000 * time.Millisecond
}
func SynthSunderArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Sunder Armor (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 11597}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   SynthSunderArmorDuration(talentPoints),
		MaxStacks:  5,
		Category:   SynthSunderArmorCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: SynthSunderArmorValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Expose Armor - https://www.wowhead.com/forever/spell=11198
// Effect 0 is worth -450.0 per combo point; this is the 5-point finisher.
var SynthExposeArmorCategory = "MajorArmorReduction"

func SynthExposeArmorValue(talentPoints int32) float64 {
	return -2250.0
}
func SynthExposeArmorDuration(talentPoints int32) time.Duration {
	return 30000 * time.Millisecond
}
func SynthExposeArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Expose Armor (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 11198}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   SynthExposeArmorDuration(talentPoints),
		Category:   SynthExposeArmorCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: SynthExposeArmorValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Curse of the Elements - https://www.wowhead.com/forever/spell=1311680
var SynthCurseOfElementsCategory = "CurseOfElements"

func SynthCurseOfElementsValue(talentPoints int32) float64 {
	return -75.0
}
func SynthCurseOfElementsDuration(talentPoints int32) time.Duration {
	return 300000 * time.Millisecond
}
func SynthCurseOfElementsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Curse of the Elements (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 1311680}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   SynthCurseOfElementsDuration(talentPoints),
		Category:   SynthCurseOfElementsCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.FireResistance, Amount: SynthCurseOfElementsValue(talentPoints), IsMultiplicative: false},
			{Stat: stats.NatureResistance, Amount: -75.0, IsMultiplicative: false},
			{Stat: stats.FrostResistance, Amount: -75.0, IsMultiplicative: false},
			{Stat: stats.ShadowResistance, Amount: -75.0, IsMultiplicative: false},
			{Stat: stats.ArcaneResistance, Amount: -75.0, IsMultiplicative: false},
		},
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatSchoolDamageTakenMultiplier, Amount: 1.1, IsMultiplicative: true, SchoolMask: 126},
		},
	})
}

func applyGeneratedDebuffs(target *core.Unit, debuffs *proto.Debuffs, raid *proto.Raid) {
	if debuffs.ThunderClap {
		core.MakePermanent(SynthThunderClapAura(target, false, 0))
	}
	if debuffs.SunderArmor {
		driveSynthSunderArmor(target, debuffs, raid)
	}
	if debuffs.ExposeArmor {
		core.MakePermanent(SynthExposeArmorAura(target, false, 0))
	}
	if debuffs.CurseOfElements {
		core.MakePermanent(SynthCurseOfElementsAura(target, false, 0))
	}
}
