package database

// The two generated sim/core/buffs files. A row the generator could not express keeps
// its place as a commented shell naming the reason, the same idiom the on-use
// effects file uses, so a reader of the generated file sees every manifest row.

const tmplStrBuffRows = `
{{- range .SharedCategories}}

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var {{.Var}} = "{{.Name}}"
{{- end}}
{{- range .Rows}}
{{- if .OwnerAuraVar}}

// The label a pet looks for on its owner, and the label the buff's own aura
// carries.
var {{.OwnerAuraVar}} = {{.OwnerAura}}
{{- end}}

{{if .Supported}}
// {{.Label}}
{{- if .Note}}
// {{.Note}}
{{- end}}
{{- if .CategoryVar}}
var {{.CategoryVar}} = "{{.Category}}"
{{- end}}
var {{.SpellVar}} = spelldata.MustFind({{.SpellID}})
{{- if .CastVar}}
var {{.CastVar}} = spelldata.MustFind({{.CastID}})
{{- end}}
{{- if .TalentVar}}
var {{.TalentVar}} = spelldata.Talent({{.TalentID}}, {{.TalentRanks}})
{{- end}}
{{- if .HasValue}}
func {{.Go}}Value(talentPoints int32) float64 {
	return {{.ValueExpr}}
}
{{- end}}
func {{.Go}}Duration(talentPoints int32) time.Duration {
	return {{.Duration}}
}
{{- if .HasCooldown}}
func {{.Go}}Cooldown() time.Duration {
	return {{.Cooldown}}
}
{{- end}}
func {{.Go}}Aura(unit *core.Unit, isPlayer bool, talentPoints int32{{.ExtraParams}}) *core.Aura {
	{{.Constructor}}
}
{{- else}}
{{if .HasSpell}}// {{.Label}}
{{end}}// func {{.Go}}Aura(unit *core.Unit, isPlayer bool, talentPoints int32{{.ExtraParams}}) *core.Aura // {{.Field}}, {{.Kind}}: {{.Reason}}
{{- end}}
{{- end}}
`

const TmplStrBuffs = `// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
{{- if .NeedsTime}}
	"time"

{{ end }}
	"github.com/wowsims/forever/sim/core"
{{- if .NeedsEnums}}
	"github.com/wowsims/forever/sim/core/dbcenums"
{{- end}}
	"github.com/wowsims/forever/sim/core/proto"
{{- if .NeedsTime}}
	"github.com/wowsims/forever/sim/core/spelldata"
{{- end}}
{{- if .NeedsStats}}
	"github.com/wowsims/forever/sim/core/stats"
{{- end}}
)
` + tmplStrBuffRows + `
func applyGeneratedBuffs(char *core.Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
{{- range .Rows}}
{{- if and .Supported .HasApply}}
	if {{.ApplyIf}} {
		{{.ApplyBody}}
	}
{{- end}}
{{- end}}
}

// What a pet is given of its owner's buffs, by the policy each manifest row
// states. A buff the owner's raid casts on the party reaches the pet as well
// unless the row says otherwise: PetStrip is for one the pet cannot use or is
// given during the fight instead, PetInheritOwnerAura for a neck the pet picks
// up by standing next to the wearer, and PetStripWhenSummonedLate for one that
// is cast on whoever is there when the fight starts. PetCapAtRegular says a
// pet's share of the buff is the unimproved amount, which every row that states
// it now grants anyway, so nothing is emitted for it.
func applyGeneratedPetBuffs(pet *core.Pet, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
{{- range .PetRows}}
{{- if .Strip}}
	{{.Access}} = {{.Zero}}
{{- end}}
{{- end}}
{{- range .PetRows}}
{{- if .Inherit}}
	{{.Access}} = {{.Access}} || pet.Owner.HasAura({{.OwnerAura}})
{{- end}}
{{- end}}

	if !pet.EnabledOnStart() {
{{- range .PetRows}}
{{- if .StripLate}}
		{{.Access}} = {{.Zero}}
{{- end}}
{{- end}}
	}
}
`

const TmplStrDebuffs = `// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
{{- if .NeedsTime}}
	"time"

{{ end }}
	"github.com/wowsims/forever/sim/core"
{{- if .NeedsEnums}}
	"github.com/wowsims/forever/sim/core/dbcenums"
{{- end}}
	"github.com/wowsims/forever/sim/core/proto"
{{- if .NeedsTime}}
	"github.com/wowsims/forever/sim/core/spelldata"
{{- end}}
{{- if .NeedsStats}}
	"github.com/wowsims/forever/sim/core/stats"
{{- end}}
)
` + tmplStrBuffRows + `
func applyGeneratedDebuffs(target *core.Unit, debuffs *proto.Debuffs, raid *proto.Raid) {
{{- range .Rows}}
{{- if and .Supported .HasApply}}
	if {{.ApplyIf}} {
		{{.ApplyBody}}
	}
{{- end}}
{{- end}}
}
`
