// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/stats"
)

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var PaladinAuraCategory = "PaladinAura"

// Blood Pact - https://www.wowhead.com/forever/spell=11767
func BloodPactValue(talentPoints int32) float64 {
	return 54.0
}
func BloodPactDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func BloodPactAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Blood Pact (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 11767}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: BloodPactDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Stamina, Amount: BloodPactValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Battle Shout - https://www.wowhead.com/forever/spell=25289
var BattleShoutCategory = "BattleShout"

func BattleShoutValue(talentPoints int32) float64 {
	return 139.0
}
func BattleShoutDuration(talentPoints int32) time.Duration {
	return 180000 * time.Millisecond
}
func BattleShoutAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:      "Battle Shout (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 25289}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   BattleShoutDuration(talentPoints),
		Category:   BattleShoutCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.AttackPower, Amount: BattleShoutValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Devotion Aura - https://www.wowhead.com/forever/spell=10293
var DevotionAuraCategory = "DevotionAura"

func DevotionAuraValue(talentPoints int32) float64 {
	return 735.0
}
func DevotionAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func DevotionAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Devotion Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: 10293}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       DevotionAuraDuration(talentPoints),
		Category:       DevotionAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: DevotionAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Leader of the Pack - https://www.wowhead.com/forever/spell=24932
var LeaderOfThePackCategory = "DruidCritAura"

func LeaderOfThePackValue(talentPoints int32) float64 {
	return 3.0
}
func LeaderOfThePackDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func LeaderOfThePackAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:      "Leader of the Pack (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 24932}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   LeaderOfThePackDuration(talentPoints),
		Category:   LeaderOfThePackCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.PhysicalCritPercent, Amount: LeaderOfThePackValue(talentPoints), IsMultiplicative: false},
			{Stat: stats.SpellCritPercent, Amount: 3.0, IsMultiplicative: false},
		},
	})
}

// Mana Spring Totem - https://www.wowhead.com/forever/spell=10494
var ManaSpringTotemCategory = "ManaSpringTotem"

func ManaSpringTotemValue(talentPoints int32) float64 {
	return []float64{25.0, 25.0, 27.5, 27.5, 30.0, 30.0}[talentPoints]
}
func ManaSpringTotemDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func ManaSpringTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Mana Spring Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 10494}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: ManaSpringTotemDuration(talentPoints),
		Category: ManaSpringTotemCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.MP5, Amount: ManaSpringTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Mana Tide Totem - https://www.wowhead.com/forever/spell=17360
var ManaTideTotemsCategory = "ManaTideTotem"

func ManaTideTotemsValue(talentPoints int32) float64 {
	return 483.3333333333333
}
func ManaTideTotemsDuration(talentPoints int32) time.Duration {
	return 13000 * time.Millisecond
}
func ManaTideTotemsCooldown() time.Duration {
	return 300000 * time.Millisecond
}
func ManaTideTotemsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Mana Tide Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 17360}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: ManaTideTotemsDuration(talentPoints),
		Category: ManaTideTotemsCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.MP5, Amount: ManaTideTotemsValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Moonkin Aura - https://www.wowhead.com/forever/spell=24907
var MoonkinAuraCategory = "DruidCritAura"

func MoonkinAuraValue(talentPoints int32) float64 {
	return 3.0
}
func MoonkinAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func MoonkinAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:      "Moonkin Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 24907}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   MoonkinAuraDuration(talentPoints),
		Category:   MoonkinAuraCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.PhysicalCritPercent, Amount: MoonkinAuraValue(talentPoints), IsMultiplicative: false},
			{Stat: stats.SpellCritPercent, Amount: 3.0, IsMultiplicative: false},
		},
	})
}

// Retribution Aura - https://www.wowhead.com/forever/spell=10301
var RetributionAuraCategory = "RetributionAura"

func RetributionAuraValue(talentPoints int32) float64 {
	return 30.0
}
func RetributionAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func RetributionAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDamageShield(unit, core.GeneratedBuff{
		Label:          "Retribution Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: 10301}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       RetributionAuraDuration(talentPoints),
		Category:       RetributionAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
	}, core.SpellSchoolHoly, RetributionAuraValue(talentPoints))
}

// func RetributionAuraSpellPowerAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // retribution_aura_spell_power, KindFlag: the Holy spell power of the paladin providing Retribution Aura, which driveRetributionAura scales the damage with; a sim input with no spell source, rendered under Other Inputs.

// Concentration Aura - https://www.wowhead.com/forever/spell=19746
var ConcentrationAuraCategory = "ConcentrationAura"

func ConcentrationAuraValue(talentPoints int32) float64 {
	return -0.35
}
func ConcentrationAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func ConcentrationAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Concentration Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: 19746}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       ConcentrationAuraDuration(talentPoints),
		Category:       ConcentrationAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatPushbackChance, Amount: ConcentrationAuraValue(talentPoints), IsMultiplicative: false, SchoolMask: 0},
		},
	})
}

// Trueshot Aura - https://www.wowhead.com/forever/spell=20906
// the rank ladder is not monotonic: rank 5 (20906) is worth 50 where rank 4 (20905) is worth 75, and the top rank is what the constructor states. TODO: confirm in game which rank the client grants
func TrueshotAuraValue(talentPoints int32) float64 {
	return 50.0
}
func TrueshotAuraDuration(talentPoints int32) time.Duration {
	return 1800000 * time.Millisecond
}
func TrueshotAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Trueshot Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 20906}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: TrueshotAuraDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.RangedAttackPower, Amount: TrueshotAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Atiesh - Mage - https://www.wowhead.com/forever/spell=28142
func AtieshMageValue(talentPoints int32) float64 {
	return 2.0
}
func AtieshMageDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func AtieshMageAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Atiesh - Mage (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 28142}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshMageDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.SpellCritPercent, Amount: AtieshMageValue(talentPoints) * count, IsMultiplicative: false},
		},
	})
}

// Atiesh - Warlock - https://www.wowhead.com/forever/spell=28143
func AtieshWarlockValue(talentPoints int32) float64 {
	return 33.0
}
func AtieshWarlockDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func AtieshWarlockAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Atiesh - Warlock (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 28143}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshWarlockDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.SpellDamage, Amount: AtieshWarlockValue(talentPoints) * count, IsMultiplicative: false},
			{Stat: stats.HealingPower, Amount: 33.0 * count, IsMultiplicative: false},
		},
	})
}

// Strength of Earth Totem - https://www.wowhead.com/forever/spell=25362
var StrengthOfEarthTotemCategory = "StrengthOfEarthTotem"

func StrengthOfEarthTotemValue(talentPoints int32) float64 {
	return 53.0
}
func StrengthOfEarthTotemDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func StrengthOfEarthTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Strength of Earth Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25362}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: StrengthOfEarthTotemDuration(talentPoints),
		Category: StrengthOfEarthTotemCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Strength, Amount: StrengthOfEarthTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Grace of Air Totem - https://www.wowhead.com/forever/spell=25360
var GraceOfAirTotemCategory = "GraceOfAirTotem"

func GraceOfAirTotemValue(talentPoints int32) float64 {
	return 89.0
}
func GraceOfAirTotemDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func GraceOfAirTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Grace of Air Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25360}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GraceOfAirTotemDuration(talentPoints),
		Category: GraceOfAirTotemCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Agility, Amount: GraceOfAirTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Windfury Totem - https://www.wowhead.com/forever/spell=10610
var WindfuryTotemCategory = "WindfuryTotem"

func WindfuryTotemValue(talentPoints int32) float64 {
	return 246.0
}
func WindfuryTotemDuration(talentPoints int32) time.Duration {
	return 1000 * time.Millisecond
}
func WindfuryTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Windfury Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 10610}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: WindfuryTotemDuration(talentPoints),
		Category: WindfuryTotemCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.AttackPower, Amount: WindfuryTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Atiesh - Druid - https://www.wowhead.com/forever/spell=28145
func AtieshDruidValue(talentPoints int32) float64 {
	return 11.0
}
func AtieshDruidDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func AtieshDruidAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Atiesh - Druid (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 28145}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshDruidDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.MP5, Amount: AtieshDruidValue(talentPoints) * count, IsMultiplicative: false},
		},
	})
}

// Atiesh - Priest - https://www.wowhead.com/forever/spell=28144
func AtieshPriestValue(talentPoints int32) float64 {
	return 62.0
}
func AtieshPriestDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func AtieshPriestAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Atiesh - Priest (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 28144}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: AtieshPriestDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.HealingPower, Amount: AtieshPriestValue(talentPoints) * count, IsMultiplicative: false},
		},
	})
}

// func TotemTwistingAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // totem_twisting, KindFlag: sim behaviour toggle with no spell source; rendered under Other Inputs.

// Arcane Brilliance - https://www.wowhead.com/forever/spell=23028
var ArcaneBrillianceCategory = "StatBuff"

func ArcaneBrillianceValue(talentPoints int32) float64 {
	return 31.0
}
func ArcaneBrillianceDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func ArcaneBrillianceAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Arcane Brilliance (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 23028}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: ArcaneBrillianceDuration(talentPoints),
		Category: ArcaneBrillianceCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Intellect, Amount: ArcaneBrillianceValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Greater Blessing of Kings - https://www.wowhead.com/forever/spell=25898
func GreaterBlessingOfKingsValue(talentPoints int32) float64 {
	return 1.1
}
func GreaterBlessingOfKingsDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GreaterBlessingOfKingsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Greater Blessing of Kings (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25898}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GreaterBlessingOfKingsDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Strength, Amount: GreaterBlessingOfKingsValue(talentPoints), IsMultiplicative: true},
			{Stat: stats.Agility, Amount: 1.1, IsMultiplicative: true},
			{Stat: stats.Stamina, Amount: 1.1, IsMultiplicative: true},
			{Stat: stats.Intellect, Amount: 1.1, IsMultiplicative: true},
			{Stat: stats.Spirit, Amount: 1.1, IsMultiplicative: true},
		},
	})
}

// Prayer of Spirit - https://www.wowhead.com/forever/spell=27681
var PrayerOfSpiritCategory = "StatBuff"

func PrayerOfSpiritValue(talentPoints int32) float64 {
	return 40.0
}
func PrayerOfSpiritDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func PrayerOfSpiritAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Prayer of Spirit (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 27681}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: PrayerOfSpiritDuration(talentPoints),
		Category: PrayerOfSpiritCategory,
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Spirit, Amount: PrayerOfSpiritValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Gift of the Wild - https://www.wowhead.com/forever/spell=21850
func GiftOfTheWildValue(talentPoints int32) float64 {
	return 385.0
}
func GiftOfTheWildDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GiftOfTheWildAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Gift of the Wild (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 21850}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GiftOfTheWildDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: GiftOfTheWildValue(talentPoints), IsMultiplicative: false},
			{Stat: stats.Strength, Amount: 16.0, IsMultiplicative: false},
			{Stat: stats.Agility, Amount: 16.0, IsMultiplicative: false},
			{Stat: stats.Stamina, Amount: 16.0, IsMultiplicative: false},
			{Stat: stats.Intellect, Amount: 16.0, IsMultiplicative: false},
			{Stat: stats.Spirit, Amount: 16.0, IsMultiplicative: false},
			{Stat: stats.FireResistance, Amount: 27.0, IsMultiplicative: false},
			{Stat: stats.NatureResistance, Amount: 27.0, IsMultiplicative: false},
			{Stat: stats.FrostResistance, Amount: 27.0, IsMultiplicative: false},
			{Stat: stats.ShadowResistance, Amount: 27.0, IsMultiplicative: false},
			{Stat: stats.ArcaneResistance, Amount: 27.0, IsMultiplicative: false},
		},
	})
}

// Thorns - https://www.wowhead.com/forever/spell=9910
var ThornsCategory = "Thorns"

func ThornsValue(talentPoints int32) float64 {
	return 22.0
}
func ThornsDuration(talentPoints int32) time.Duration {
	return 600000 * time.Millisecond
}
func ThornsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDamageShield(unit, core.GeneratedBuff{
		Label:      "Thorns (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: 9910}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   ThornsDuration(talentPoints),
		Category:   ThornsCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
	}, core.SpellSchoolNature, ThornsValue(talentPoints))
}

// Prayer of Fortitude - https://www.wowhead.com/forever/spell=21564
func PrayerOfFortitudeValue(talentPoints int32) float64 {
	return 70.0
}
func PrayerOfFortitudeDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func PrayerOfFortitudeAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Prayer of Fortitude (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 21564}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: PrayerOfFortitudeDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Stamina, Amount: PrayerOfFortitudeValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Greater Blessing of Might - https://www.wowhead.com/forever/spell=25916
func GreaterBlessingOfMightValue(talentPoints int32) float64 {
	return 133.0
}
func GreaterBlessingOfMightDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GreaterBlessingOfMightAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Greater Blessing of Might (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25916}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GreaterBlessingOfMightDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.AttackPower, Amount: GreaterBlessingOfMightValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Greater Blessing of Wisdom - https://www.wowhead.com/forever/spell=25918
func GreaterBlessingOfWisdomValue(talentPoints int32) float64 {
	return 40.0
}
func GreaterBlessingOfWisdomDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GreaterBlessingOfWisdomAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Greater Blessing of Wisdom (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25918}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GreaterBlessingOfWisdomDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.MP5, Amount: GreaterBlessingOfWisdomValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Greater Blessing of Salvation - https://www.wowhead.com/forever/spell=25895
func GreaterBlessingOfSalvationValue(talentPoints int32) float64 {
	return 0.7
}
func GreaterBlessingOfSalvationDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GreaterBlessingOfSalvationAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Greater Blessing of Salvation (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25895}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GreaterBlessingOfSalvationDuration(talentPoints),
		IsPlayer: isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatThreatMultiplier, Amount: GreaterBlessingOfSalvationValue(talentPoints), IsMultiplicative: true, SchoolMask: 0},
		},
	})
}

// Greater Blessing of Light - https://www.wowhead.com/forever/spell=25890
var GreaterBlessingOfLightCategory = "BlessingOfLight"

func GreaterBlessingOfLightDuration(talentPoints int32) time.Duration {
	return 3600000 * time.Millisecond
}
func GreaterBlessingOfLightAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Greater Blessing of Light (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 25890}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: GreaterBlessingOfLightDuration(talentPoints),
		Category: GreaterBlessingOfLightCategory,
		IsPlayer: isPlayer,
	})
}

// Prayer of Shadow Protection - https://www.wowhead.com/forever/spell=27683
func PrayerOfShadowProtectionValue(talentPoints int32) float64 {
	return 60.0
}
func PrayerOfShadowProtectionDuration(talentPoints int32) time.Duration {
	return 1200000 * time.Millisecond
}
func PrayerOfShadowProtectionAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Prayer of Shadow Protection (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 27683}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: PrayerOfShadowProtectionDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.ShadowResistance, Amount: PrayerOfShadowProtectionValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Fire Resistance Aura - https://www.wowhead.com/forever/spell=19900
var FireResistanceAuraCategory = "FireResistanceAura"

func FireResistanceAuraValue(talentPoints int32) float64 {
	return 60.0
}
func FireResistanceAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func FireResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Fire Resistance Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: 19900}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       FireResistanceAuraDuration(talentPoints),
		Category:       FireResistanceAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.FireResistance, Amount: FireResistanceAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Frost Resistance Aura - https://www.wowhead.com/forever/spell=19898
var FrostResistanceAuraCategory = "FrostResistanceAura"

func FrostResistanceAuraValue(talentPoints int32) float64 {
	return 60.0
}
func FrostResistanceAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func FrostResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Frost Resistance Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: 19898}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       FrostResistanceAuraDuration(talentPoints),
		Category:       FrostResistanceAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.FrostResistance, Amount: FrostResistanceAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Shadow Resistance Aura - https://www.wowhead.com/forever/spell=19896
var ShadowResistanceAuraCategory = "ShadowResistanceAura"

func ShadowResistanceAuraValue(talentPoints int32) float64 {
	return 60.0
}
func ShadowResistanceAuraDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func ShadowResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:          "Shadow Resistance Aura (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:       core.ActionID{SpellID: 19896}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:       ShadowResistanceAuraDuration(talentPoints),
		Category:       ShadowResistanceAuraCategory,
		SharedCategory: PaladinAuraCategory,
		SingleAura:     true,
		IsPlayer:       isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.ShadowResistance, Amount: ShadowResistanceAuraValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Fire Resistance Totem - https://www.wowhead.com/forever/spell=10535
func FireResistanceTotemValue(talentPoints int32) float64 {
	return 60.0
}
func FireResistanceTotemDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func FireResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Fire Resistance Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 10535}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: FireResistanceTotemDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.FireResistance, Amount: FireResistanceTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Frost Resistance Totem - https://www.wowhead.com/forever/spell=10477
func FrostResistanceTotemValue(talentPoints int32) float64 {
	return 60.0
}
func FrostResistanceTotemDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func FrostResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Frost Resistance Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 10477}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: FrostResistanceTotemDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.FrostResistance, Amount: FrostResistanceTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Nature Resistance Totem - https://www.wowhead.com/forever/spell=10599
func NatureResistanceTotemValue(talentPoints int32) float64 {
	return 60.0
}
func NatureResistanceTotemDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func NatureResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Nature Resistance Totem (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 10599}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: NatureResistanceTotemDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.NatureResistance, Amount: NatureResistanceTotemValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Aspect of the Wild - https://www.wowhead.com/forever/spell=20190
func AspectOfTheWildValue(talentPoints int32) float64 {
	return 60.0
}
func AspectOfTheWildDuration(talentPoints int32) time.Duration {
	return core.NeverExpires
}
func AspectOfTheWildAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Aspect of the Wild (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 20190}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: AspectOfTheWildDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.NatureResistance, Amount: AspectOfTheWildValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Innervates - https://www.wowhead.com/forever/spell=29166
var InnervatesCategory = "Innervate"

func InnervatesDuration(talentPoints int32) time.Duration {
	return 20000 * time.Millisecond
}
func InnervatesCooldown() time.Duration {
	return 360000 * time.Millisecond
}
func InnervatesAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Innervates (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 29166}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: InnervatesDuration(talentPoints),
		Category: InnervatesCategory,
		IsPlayer: isPlayer,
	})
}

// Power Infusions - https://www.wowhead.com/forever/spell=10060
var PowerInfusionsCategory = "PowerInfusion"

func PowerInfusionsValue(talentPoints int32) float64 {
	return 1.2
}
func PowerInfusionsDuration(talentPoints int32) time.Duration {
	return 15000 * time.Millisecond
}
func PowerInfusionsCooldown() time.Duration {
	return 180000 * time.Millisecond
}
func PowerInfusionsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedStatAura(unit, core.GeneratedBuff{
		Label:    "Power Infusions (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: 10060}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: PowerInfusionsDuration(talentPoints),
		Category: PowerInfusionsCategory,
		IsPlayer: isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatHealingDealtMultiplier, Amount: PowerInfusionsValue(talentPoints), IsMultiplicative: true, SchoolMask: 0},
			{Kind: core.PseudoStatSchoolDamageDealtMultiplier, Amount: 1.2, IsMultiplicative: true, SchoolMask: 126},
		},
	})
}

func applyGeneratedBuffs(char *core.Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	if party.BloodPact {
		core.MakePermanent(BloodPactAura(&char.Unit, false, 0))
	}
	if party.BattleShout != proto.TristateEffect_TristateEffectMissing {
		driveBattleShout(char, party)
	}
	if party.DevotionAura {
		core.MakePermanent(DevotionAuraAura(&char.Unit, false, 0))
	}
	if party.LeaderOfThePack {
		core.MakePermanent(LeaderOfThePackAura(&char.Unit, false, 0))
	}
	if party.ManaSpringTotem != proto.TristateEffect_TristateEffectMissing {
		core.MakePermanent(ManaSpringTotemAura(&char.Unit, false, core.GetTristateValueInt32(party.ManaSpringTotem, 0, 5)))
	}
	if party.ManaTideTotems > 0 {
		driveManaTideTotems(char, party)
	}
	if party.MoonkinAura {
		core.MakePermanent(MoonkinAuraAura(&char.Unit, false, 0))
	}
	if party.RetributionAura {
		driveRetributionAura(char, party)
	}
	if party.ConcentrationAura {
		core.MakePermanent(ConcentrationAuraAura(&char.Unit, false, 0))
	}
	if party.TrueshotAura {
		core.MakePermanent(TrueshotAuraAura(&char.Unit, false, 0))
	}
	if party.AtieshMage > 0 {
		driveAtieshMage(char, party)
	}
	if party.AtieshWarlock > 0 {
		driveAtieshWarlock(char, party)
	}
	if party.StrengthOfEarthTotem {
		core.MakePermanent(StrengthOfEarthTotemAura(&char.Unit, false, 0))
	}
	if party.GraceOfAirTotem {
		driveGraceOfAirTotem(char, party)
	}
	if party.WindfuryTotem {
		driveWindfuryTotem(char, party)
	}
	if party.AtieshDruid > 0 {
		driveAtieshDruid(char, party)
	}
	if party.AtieshPriest > 0 {
		driveAtieshPriest(char, party)
	}
	if raid.ArcaneBrilliance {
		core.MakePermanent(ArcaneBrillianceAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfKings {
		core.MakePermanent(GreaterBlessingOfKingsAura(&char.Unit, false, 0))
	}
	if raid.PrayerOfSpirit {
		core.MakePermanent(PrayerOfSpiritAura(&char.Unit, false, 0))
	}
	if raid.GiftOfTheWild {
		core.MakePermanent(GiftOfTheWildAura(&char.Unit, false, 0))
	}
	if raid.Thorns {
		core.MakePermanent(ThornsAura(&char.Unit, false, 0))
	}
	if raid.PrayerOfFortitude {
		core.MakePermanent(PrayerOfFortitudeAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfMight {
		core.MakePermanent(GreaterBlessingOfMightAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfWisdom {
		core.MakePermanent(GreaterBlessingOfWisdomAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfSalvation {
		core.MakePermanent(GreaterBlessingOfSalvationAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfLight {
		driveGreaterBlessingOfLight(char, individual)
	}
	if raid.PrayerOfShadowProtection {
		core.MakePermanent(PrayerOfShadowProtectionAura(&char.Unit, false, 0))
	}
	if raid.FireResistanceAura {
		core.MakePermanent(FireResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceAura {
		core.MakePermanent(FrostResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.ShadowResistanceAura {
		core.MakePermanent(ShadowResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.FireResistanceTotem {
		core.MakePermanent(FireResistanceTotemAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceTotem {
		core.MakePermanent(FrostResistanceTotemAura(&char.Unit, false, 0))
	}
	if raid.NatureResistanceTotem {
		core.MakePermanent(NatureResistanceTotemAura(&char.Unit, false, 0))
	}
	if raid.AspectOfTheWild {
		core.MakePermanent(AspectOfTheWildAura(&char.Unit, false, 0))
	}
	if individual.Innervates > 0 {
		driveInnervates(char, individual)
	}
	if individual.PowerInfusions > 0 {
		drivePowerInfusions(char, individual)
	}
}

// What a pet is given of its owner's buffs, by the policy each manifest row
// states. A buff the owner's raid casts on the party reaches the pet as well
// unless the row says otherwise: PetStrip is for one the pet cannot use or is
// given during the fight instead, PetInheritOwnerAura for a neck the pet picks
// up by standing next to the wearer, and PetStripWhenSummonedLate for one that
// is cast on whoever is there when the fight starts. PetCapAtRegular says a
// pet's share of the buff is the unimproved amount, which every row that states
// it now grants anyway, so nothing is emitted for it.
func applyGeneratedPetBuffs(pet *core.Pet, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	party.WindfuryTotem = false
	raid.Thorns = false
	individual.Innervates = 0
	individual.PowerInfusions = 0

	if !pet.EnabledOnStart() {
		raid.ArcaneBrilliance = false
		individual.GreaterBlessingOfKings = false
		raid.PrayerOfSpirit = false
		raid.GiftOfTheWild = false
		raid.PrayerOfFortitude = false
		individual.GreaterBlessingOfMight = false
		individual.GreaterBlessingOfWisdom = false
		individual.GreaterBlessingOfSalvation = false
		individual.GreaterBlessingOfLight = false
		raid.PrayerOfShadowProtection = false
	}
}
