// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/dbcenums"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/spelldata"
	"github.com/wowsims/forever/sim/core/stats"
)

// Hunter's Mark
var HuntersMarkCategory = "HuntersMark"
var huntersMarkSpell = spelldata.MustFind(14325)

func HuntersMarkValue(talentPoints int32) float64 {
	return amount(huntersMarkSpell.Effect(dbcenums.A_RANGED_ATTACK_POWER_ATTACKER_BONUS, 0))
}
func HuntersMarkDuration(talentPoints int32) time.Duration {
	return auraDuration(huntersMarkSpell)
}
func HuntersMarkAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Hunter's Mark (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: huntersMarkSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   HuntersMarkDuration(talentPoints),
		Category:   HuntersMarkCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatBonusRangedAttackPower, Amount: HuntersMarkValue(talentPoints), IsMultiplicative: false, SchoolMask: 0},
		},
	})
}

// Judgement of the Crusader
// func JudgementOfTheCrusaderAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // judgement_of_the_crusader, KindDebuffStat: spell 20303 states no aura effect this generator maps (auras 14)

// Judgement of Light
var judgementOfLightSpell = spelldata.MustFind(20346)

func JudgementOfLightDuration(talentPoints int32) time.Duration {
	return auraDuration(judgementOfLightSpell)
}
func JudgementOfLightAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:    "Judgement of Light (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: judgementOfLightSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: JudgementOfLightDuration(talentPoints),
		IsPlayer: isPlayer,
	})
}

// Judgement of Wisdom
var judgementOfWisdomSpell = spelldata.MustFind(20355)

func JudgementOfWisdomDuration(talentPoints int32) time.Duration {
	return auraDuration(judgementOfWisdomSpell)
}
func JudgementOfWisdomAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:    "Judgement of Wisdom (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: judgementOfWisdomSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: JudgementOfWisdomDuration(talentPoints),
		IsPlayer: isPlayer,
	})
}

// Mangle
// func MangleAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // mangle, KindDebuffDamageTaken: spell 1238073 states no aura effect this generator maps (auras )

// Curse of the Elements
var CurseOfElementsCategory = "CurseOfElements"
var curseOfElementsSpell = spelldata.MustFind(1311680)

func CurseOfElementsValue(talentPoints int32) float64 {
	return amount(curseOfElementsSpell.Effect(dbcenums.A_MOD_RESISTANCE, 126))
}
func CurseOfElementsDuration(talentPoints int32) time.Duration {
	return auraDuration(curseOfElementsSpell)
}
func CurseOfElementsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Curse of the Elements (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: curseOfElementsSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   CurseOfElementsDuration(talentPoints),
		Category:   CurseOfElementsCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.ArcaneResistance, Amount: CurseOfElementsValue(talentPoints), IsMultiplicative: false},
			{Stat: stats.FireResistance, Amount: amount(curseOfElementsSpell.Effect(dbcenums.A_MOD_RESISTANCE, 126)), IsMultiplicative: false},
			{Stat: stats.FrostResistance, Amount: amount(curseOfElementsSpell.Effect(dbcenums.A_MOD_RESISTANCE, 126)), IsMultiplicative: false},
			{Stat: stats.NatureResistance, Amount: amount(curseOfElementsSpell.Effect(dbcenums.A_MOD_RESISTANCE, 126)), IsMultiplicative: false},
			{Stat: stats.ShadowResistance, Amount: amount(curseOfElementsSpell.Effect(dbcenums.A_MOD_RESISTANCE, 126)), IsMultiplicative: false},
		},
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatSchoolDamageTakenMultiplier, Amount: 1 + amount(curseOfElementsSpell.Effect(dbcenums.A_MOD_DAMAGE_PERCENT_TAKEN, 126))/100, IsMultiplicative: true, SchoolMask: 126},
		},
	})
}

// Curse of Recklessness
var CurseOfRecklessnessCategory = "CurseOfRecklessness"
var curseOfRecklessnessSpell = spelldata.MustFind(11717)

func CurseOfRecklessnessValue(talentPoints int32) float64 {
	return amount(curseOfRecklessnessSpell.Effect(dbcenums.A_MOD_RESISTANCE, 1))
}
func CurseOfRecklessnessDuration(talentPoints int32) time.Duration {
	return auraDuration(curseOfRecklessnessSpell)
}
func CurseOfRecklessnessAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Curse of Recklessness (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: curseOfRecklessnessSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   CurseOfRecklessnessDuration(talentPoints),
		Category:   CurseOfRecklessnessCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: CurseOfRecklessnessValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Faerie Fire
var FaerieFireCategory = "FaerieFireAura"
var faerieFireSpell = spelldata.MustFind(9907)

func FaerieFireValue(talentPoints int32) float64 {
	return amount(faerieFireSpell.Effect(dbcenums.A_MOD_RESISTANCE, 1))
}
func FaerieFireDuration(talentPoints int32) time.Duration {
	return auraDuration(faerieFireSpell)
}
func FaerieFireAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Faerie Fire (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: faerieFireSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   FaerieFireDuration(talentPoints),
		Category:   FaerieFireCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: FaerieFireValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Expose Armor
// Effect 0 is worth -450.0 per combo point; this is the 5-point finisher.
var ExposeArmorCategory = "MajorArmorReduction"
var exposeArmorSpell = spelldata.MustFind(11198)

func ExposeArmorValue(talentPoints int32) float64 {
	return fullComboPoints(exposeArmorSpell.Effect(dbcenums.A_MOD_RESISTANCE, 1))
}
func ExposeArmorDuration(talentPoints int32) time.Duration {
	return auraDuration(exposeArmorSpell)
}
func ExposeArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Expose Armor (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: exposeArmorSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   ExposeArmorDuration(talentPoints),
		Category:   ExposeArmorCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: ExposeArmorValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Sunder Armor
var SunderArmorCategory = "MajorArmorReduction"
var sunderArmorSpell = spelldata.MustFind(11597)

func SunderArmorValue(talentPoints int32) float64 {
	return amount(sunderArmorSpell.Effect(dbcenums.A_MOD_RESISTANCE, 1))
}
func SunderArmorDuration(talentPoints int32) time.Duration {
	return auraDuration(sunderArmorSpell)
}
func SunderArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Sunder Armor (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: sunderArmorSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   SunderArmorDuration(talentPoints),
		MaxStacks:  5,
		Category:   SunderArmorCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.Armor, Amount: SunderArmorValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Gift of Arthas
var GiftOfArthasCategory = "GiftOfArthasAura"
var giftOfArthasSpell = spelldata.MustFind(11374)

func GiftOfArthasValue(talentPoints int32) float64 {
	return amount(giftOfArthasSpell.Effect(dbcenums.A_MOD_DAMAGE_TAKEN, 1))
}
func GiftOfArthasDuration(talentPoints int32) time.Duration {
	return auraDuration(giftOfArthasSpell)
}
func GiftOfArthasAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Gift of Arthas (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: giftOfArthasSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   GiftOfArthasDuration(talentPoints),
		Category:   GiftOfArthasCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatBonusPhysicalDamageTaken, Amount: GiftOfArthasValue(talentPoints), IsMultiplicative: false, SchoolMask: 0},
		},
	})
}

// Demoralizing Roar
var DemoralizingRoarCategory = "Demoralizing"
var demoralizingRoarSpell = spelldata.MustFind(9898)

func DemoralizingRoarValue(talentPoints int32) float64 {
	return amount(demoralizingRoarSpell.Effect(dbcenums.A_MOD_ATTACK_POWER, 0))
}
func DemoralizingRoarDuration(talentPoints int32) time.Duration {
	return auraDuration(demoralizingRoarSpell)
}
func DemoralizingRoarAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Demoralizing Roar (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: demoralizingRoarSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   DemoralizingRoarDuration(talentPoints),
		Category:   DemoralizingRoarCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.AttackPower, Amount: DemoralizingRoarValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Demoralizing Shout
var DemoralizingShoutCategory = "Demoralizing"
var demoralizingShoutSpell = spelldata.MustFind(11556)

func DemoralizingShoutValue(talentPoints int32) float64 {
	return amount(demoralizingShoutSpell.Effect(dbcenums.A_MOD_ATTACK_POWER, 0))
}
func DemoralizingShoutDuration(talentPoints int32) time.Duration {
	return auraDuration(demoralizingShoutSpell)
}
func DemoralizingShoutAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:      "Demoralizing Shout (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID:   core.ActionID{SpellID: demoralizingShoutSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration:   DemoralizingShoutDuration(talentPoints),
		Category:   DemoralizingShoutCategory,
		SingleAura: true,
		IsPlayer:   isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.AttackPower, Amount: DemoralizingShoutValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Thunder Clap
var ThunderClapCategory = "AtkSpdReduction"
var thunderClapSpell = spelldata.MustFind(11581)

func ThunderClapValue(talentPoints int32) float64 {
	return 1 + amount(thunderClapSpell.Effect(dbcenums.A_MOD_MELEE_HASTE_3, 0))/100
}
func ThunderClapDuration(talentPoints int32) time.Duration {
	return auraDuration(thunderClapSpell)
}
func ThunderClapAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:    "Thunder Clap (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: thunderClapSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: ThunderClapDuration(talentPoints),
		Category: ThunderClapCategory,
		IsPlayer: isPlayer,
		Pseudo: []core.PseudoConfig{
			{Kind: core.PseudoStatMeleeSpeedMultiplier, Amount: ThunderClapValue(talentPoints), IsMultiplicative: true, SchoolMask: 0},
		},
	})
}

// Insect Swarm
var insectSwarmSpell = spelldata.MustFind(24977)

func InsectSwarmValue(talentPoints int32) float64 {
	return amount(insectSwarmSpell.Effect(dbcenums.A_MOD_HIT_CHANCE, 0))
}
func InsectSwarmDuration(talentPoints int32) time.Duration {
	return auraDuration(insectSwarmSpell)
}
func InsectSwarmAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:    "Insect Swarm (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: insectSwarmSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: InsectSwarmDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.PhysicalHitPercent, Amount: InsectSwarmValue(talentPoints), IsMultiplicative: false},
		},
	})
}

// Scorpid Sting
var scorpidStingSpell = spelldata.MustFind(3043)

func ScorpidStingValue(talentPoints int32) float64 {
	return amount(scorpidStingSpell.Effect(dbcenums.A_MOD_HIT_CHANCE, 0))
}
func ScorpidStingDuration(talentPoints int32) time.Duration {
	return auraDuration(scorpidStingSpell)
}
func ScorpidStingAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return core.NewGeneratedDebuff(unit, core.GeneratedBuff{
		Label:    "Scorpid Sting (" + core.Ternary(isPlayer, "Player", "External") + ")",
		ActionID: core.ActionID{SpellID: scorpidStingSpell.ID}.WithTag(core.TernaryInt32(isPlayer, 0, -1)),
		Duration: ScorpidStingDuration(talentPoints),
		IsPlayer: isPlayer,
		Stats: []core.StatConfig{
			{Stat: stats.PhysicalHitPercent, Amount: ScorpidStingValue(talentPoints), IsMultiplicative: false},
		},
	})
}

func applyGeneratedDebuffs(target *core.Unit, debuffs *proto.Debuffs, raid *proto.Raid) {
	if debuffs.HuntersMark {
		core.MakePermanent(HuntersMarkAura(target, false, 0))
	}
	if debuffs.JudgementOfLight {
		driveJudgementOfLight(target, debuffs, raid)
	}
	if debuffs.JudgementOfWisdom {
		driveJudgementOfWisdom(target, debuffs, raid)
	}
	if debuffs.CurseOfElements {
		core.MakePermanent(CurseOfElementsAura(target, false, 0))
	}
	if debuffs.CurseOfRecklessness {
		core.MakePermanent(CurseOfRecklessnessAura(target, false, 0))
	}
	if debuffs.FaerieFire {
		core.MakePermanent(FaerieFireAura(target, false, 0))
	}
	if debuffs.ExposeArmor {
		core.MakePermanent(ExposeArmorAura(target, false, 0))
	}
	if debuffs.SunderArmor {
		driveSunderArmor(target, debuffs, raid)
	}
	if debuffs.GiftOfArthas {
		core.MakePermanent(GiftOfArthasAura(target, false, 0))
	}
	if debuffs.DemoralizingRoar {
		core.MakePermanent(DemoralizingRoarAura(target, false, 0))
	}
	if debuffs.DemoralizingShout {
		core.MakePermanent(DemoralizingShoutAura(target, false, 0))
	}
	if debuffs.ThunderClap {
		core.MakePermanent(ThunderClapAura(target, false, 0))
	}
	if debuffs.InsectSwarm {
		core.MakePermanent(InsectSwarmAura(target, false, 0))
	}
	if debuffs.ScorpidSting {
		core.MakePermanent(ScorpidStingAura(target, false, 0))
	}
}
