package warrior

import (
	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
	"slices"
	"time"
)

///////////////////////////////////////////////////////////////////////////
//                            Phase 1 Item Sets - Molten Core
///////////////////////////////////////////////////////////////////////////

var ItemSetBattleGearOfMight = core.NewItemSet(core.ItemSet{
	Name: "Battlegear of Might",
	Bonuses: map[int32]core.ApplyEffect{
		// Increases the block value of your shield by 30.
		3: func(agent core.Agent) {
			character := agent.GetCharacter()
			character.AddStat(stats.BlockValue, 30)
		},
		// Gives you a 20% chance to generate an additional Rage point whenever damage is dealt to you.
		5: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			actionID := core.ActionID{SpellID: 21838}
			rageMetrics := warrior.NewRageMetrics(actionID)

			core.MakeProcTriggerAura(&warrior.Unit, core.ProcTrigger{
				ActionID:   actionID,
				Name:       "Battlegear of Might - Rage",
				Callback:   core.CallbackOnSpellHitTaken,
				ProcMask:   core.ProcMaskMelee,
				ProcChance: 0.20,
				Handler: func(sim *core.Simulation, spell *core.Spell, _ *core.SpellResult) {
					warrior.AddRage(sim, 1, rageMetrics)
				},
			})
		},
		// Increases the threat generated by Sunder Armor by 15%.
		8: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Enhanced Sunder Armor",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warrior.SunderArmor.ThreatMultiplier *= 1.15
					warrior.SunderArmor.FlatThreatBonus *= 1.15
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 2 Item Sets - Dire Maul
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//                            Phase 3 Item Sets - BWL
///////////////////////////////////////////////////////////////////////////

var ItemSetBattleGearOfWrath = core.NewItemSet(core.ItemSet{
	Name: "Battlegear of Wrath",
	Bonuses: map[int32]core.ApplyEffect{
		// Increases the attack power granted by Battle Shout by 30.
		3: func(agent core.Agent) {
			// Managed in shouts.go
		},
		// 20% chance after using an offensive ability requiring rage that your next offensive ability requires 5 less rage to use.
		5: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()

			var affectedSpells []*core.Spell

			warriorsWrathAura := warrior.RegisterAura(core.Aura{
				ActionID: core.ActionID{SpellID: 21887},
				Label:    "Warrior's Wrath",
				Duration: time.Second * 10,
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range warrior.Spellbook {
						if spell.Cost != nil && spell.Cost.CostType() == core.CostTypeRage && !spell.Flags.Matches(core.SpellFlagHelpful) {
							affectedSpells = append(affectedSpells, spell)
						}
					}
				},
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range affectedSpells {
						spell.Cost.FlatModifier -= 5
					}
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range affectedSpells {
						spell.Cost.FlatModifier += 5
					}
				},
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if slices.Contains(affectedSpells, spell) {
						aura.Deactivate(sim)
					}
				},
			})

			core.MakePermanent(warrior.RegisterAura(core.Aura{
				Label: "Warrior's Wrath Trigger",
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if slices.Contains(affectedSpells, spell) {
						if sim.Proc(0.2, "Warrior's Wrath Trigger") {
							warriorsWrathAura.Activate(sim)
						}
					}
				},
			}))
		},
		// 4% chance to parry the next attack after a block.
		8: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			actionID := core.ActionID{SpellID: 23548}

			parryAura := warrior.RegisterAura(core.Aura{
				ActionID: actionID,
				Label:    "Parry",
				Duration: time.Second * 10,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					warrior.AddStatDynamic(sim, stats.Parry, 100*core.ParryRatingPerParryChance)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					warrior.AddStatDynamic(sim, stats.Parry, -100*core.ParryRatingPerParryChance)
				},
				OnSpellHitTaken: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					aura.Deactivate(sim)
				},
			})

			core.MakePermanent(warrior.RegisterAura(core.Aura{
				Label: "Parry Trigger Aura",
				OnSpellHitTaken: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if result.DidBlock() && sim.Proc(0.04, "Parry Proc") {
						parryAura.Activate(sim)
					}
				},
			}))

		},
	},
})

var ItemSetVindicatorsBattlegear = core.NewItemSet(core.ItemSet{
	Name: "Vindicator's Battlegear",
	Bonuses: map[int32]core.ApplyEffect{
		// Increases your chance to block attacks with a shield by 2%.
		2: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.AddStat(stats.Block, 2)
		},
		// Decreases the cooldown of Intimidating Shout by 15 sec.
		3: func(agent core.Agent) {
			// No implementation of Intimidating Shout in sim
		},
		// Decrease the rage cost of Whirlwind by 3.
		5: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			warrior.RegisterAura(core.Aura{
				Label: "Improved Whirlwind",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					warrior.Whirlwind.Cost.FlatModifier -= 3
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Phase 4 Item Sets - AQ
///////////////////////////////////////////////////////////////////////////

var ItemSetBattlegearOfHeroism = core.NewItemSet(core.ItemSet{
	Name: "Battlegear of Heroism",
	Bonuses: map[int32]core.ApplyEffect{
		// +8 All Resistances.
		2: func(agent core.Agent) {
			c := agent.GetCharacter()
			c.AddResistances(8)
		},
		// Vitality: 15 health every 5 sec, which a boss fight never lets tick usefully.
		3: func(_ core.Agent) {},
		// Chance on melee attack to heal you for 88 to 132, and in Forever to return 10 Rage.
		4: func(agent core.Agent) {
			c := agent.GetCharacter()
			actionID := core.ActionID{SpellID: 450587}
			healthMetrics := c.NewHealthMetrics(core.ActionID{SpellID: 450589})
			rageMetrics := c.NewRageMetrics(core.ActionID{SpellID: 450589})

			core.MakeProcTriggerAura(&c.Unit, core.ProcTrigger{
				ActionID: actionID,
				Name:     "Warrior's Resolve",
				Callback: core.CallbackOnSpellHitDealt,
				Outcome:  core.OutcomeLanded,
				ProcMask: core.ProcMaskMelee,
				PPM:      1,
				Handler: func(sim *core.Simulation, _ *core.Spell, _ *core.SpellResult) {
					c.GainHealth(sim, sim.Roll(88, 133), healthMetrics)
					if c.HasRageBar() {
						c.AddRage(sim, 10, rageMetrics)
					}
				},
			})
		},
		// Moment of Valor: breaks a Disarm when struck.
		5: func(_ core.Agent) {},
		// +20 Strength, where Classic gave +40 attack power.
		6: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.Strength, 20)
		},
	},
})

var ItemSetConquerorsBattleGear = core.NewItemSet(core.ItemSet{
	Name: "Conqueror's Battlegear",
	Bonuses: map[int32]core.ApplyEffect{
		// Decreases the rage cost of all Warrior shouts by 35%.
		3: func(agent core.Agent) {
			warrior := agent.(WarriorAgent).GetWarrior()
			core.MakePermanent(warrior.RegisterAura(core.Aura{
				Label: "Conqueror Shout Bonus",
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					warrior.BattleShout.Cost.Multiplier -= 35
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					warrior.BattleShout.Cost.Multiplier += 35
				},
			}))
		},
		// Increase the Slow effect and damage of Thunder Clap by 50%.
		5: func(agent core.Agent) {
			//Implemented in Thunderclap.go
		},
	},
})
