syntax = "proto3";
package proto;

option go_package = "./proto";

message MageTalents {
	// Arcane
	int32 wand_specialization = 1;
	int32 arcane_focus = 2;
	int32 improved_channeling = 3;
	int32 arcane_subtlety = 4;
	int32 magic_absorption = 5;
	int32 arcane_concentration = 6;
	int32 arcane_resilience = 7;
	int32 arcane_geometry = 8;
	int32 arcane_impact = 9;
	bool arcane_blast = 10;
	int32 arcane_shielding = 11;
	int32 improved_counterspell = 12;
	int32 arcane_meditation = 13;
	bool missile_barrage = 14;
	bool presence_of_mind = 15;
	int32 arcane_mind = 16;
	int32 arcane_instability = 17;
	bool arcane_power = 18;

	// Fire
	int32 wake_of_fire = 19;
	int32 incineration = 20;
	int32 ignite = 21;
	int32 flame_throwing = 22;
	int32 impact = 23;
	int32 burning_soul = 24;
	int32 improved_flamestrike = 25;
	bool pyroblast = 26;
	int32 improved_scorch = 27;
	int32 improved_fire_ward = 28;
	bool hot_streak = 29;
	int32 master_of_elements = 30;
	int32 critical_mass = 31;
	bool blast_wave = 32;
	int32 fire_power = 33;
	bool combustion = 34;

	// Frost
	int32 frost_warding = 35;
	int32 improved_frostbolt = 36;
	int32 elemental_precision = 37;
	int32 ice_shards = 38;
	int32 permafrost = 39;
	int32 improved_frost_nova = 40;
	int32 frostbite = 41;
	int32 piercing_ice = 42;
	int32 frost_channeling = 43;
	bool ice_lance = 44;
	int32 improved_blizzard = 45;
	int32 arctic_reach = 46;
	bool ice_block = 47;
	int32 shatter = 48;
	int32 improved_cone_of_cold = 49;
	bool cold_snap = 50;
	int32 fingers_of_frost = 51;
	int32 winters_chill = 52;
	bool ice_barrier = 53;
}

message Mage {
	message Rotation {
	}

	message Options {
		enum ArmorType {
			NoArmor = 0;
			IceArmor = 1;
			MageArmor = 2;
			MoltenArmor = 3;
		}
		ArmorType armor = 1;
	}
	Options options = 3;
}
