// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "paladin.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * DO NOT REMOVE THE COMMENTS
 * BEGIN GENERATED
 * PaladinTalents message.
 *
 * @generated from protobuf message proto.PaladinTalents
 */
export interface PaladinTalents {
    /**
     * Holy
     *
     * @generated from protobuf field: int32 improved_holy_strike = 1;
     */
    improvedHolyStrike: number;
    /**
     * @generated from protobuf field: int32 divine_strength = 2;
     */
    divineStrength: number;
    /**
     * @generated from protobuf field: int32 divine_intellect = 3;
     */
    divineIntellect: number;
    /**
     * @generated from protobuf field: int32 healing_light = 4;
     */
    healingLight: number;
    /**
     * @generated from protobuf field: int32 spiritual_focus = 5;
     */
    spiritualFocus: number;
    /**
     * @generated from protobuf field: int32 improved_seals = 6;
     */
    improvedSeals: number;
    /**
     * @generated from protobuf field: int32 unyielding_faith = 7;
     */
    unyieldingFaith: number;
    /**
     * @generated from protobuf field: bool voice_of_truth = 8;
     */
    voiceOfTruth: boolean;
    /**
     * @generated from protobuf field: int32 reverence = 9;
     */
    reverence: number;
    /**
     * @generated from protobuf field: int32 purifying_power = 10;
     */
    purifyingPower: number;
    /**
     * @generated from protobuf field: int32 infusion_of_light = 11;
     */
    infusionOfLight: number;
    /**
     * @generated from protobuf field: int32 illumination = 12;
     */
    illumination: number;
    /**
     * @generated from protobuf field: bool divine_favor = 13;
     */
    divineFavor: boolean;
    /**
     * @generated from protobuf field: int32 divine_precision = 14;
     */
    divinePrecision: number;
    /**
     * @generated from protobuf field: bool holy_shock = 15;
     */
    holyShock: boolean;
    /**
     * @generated from protobuf field: int32 consecrated_ground = 16;
     */
    consecratedGround: number;
    /**
     * @generated from protobuf field: int32 holy_power = 17;
     */
    holyPower: number;
    /**
     * @generated from protobuf field: bool lights_vigil = 18;
     */
    lightsVigil: boolean;
    /**
     * Protection
     *
     * @generated from protobuf field: int32 toughness = 19;
     */
    toughness: number;
    /**
     * @generated from protobuf field: int32 redoubt = 20;
     */
    redoubt: number;
    /**
     * @generated from protobuf field: int32 precision = 21;
     */
    precision: number;
    /**
     * @generated from protobuf field: int32 guardians_favor = 22;
     */
    guardiansFavor: number;
    /**
     * @generated from protobuf field: int32 anticipation = 23;
     */
    anticipation: number;
    /**
     * @generated from protobuf field: bool improved_seal_of_fury = 24;
     */
    improvedSealOfFury: boolean;
    /**
     * @generated from protobuf field: int32 improved_righteous_fury = 25;
     */
    improvedRighteousFury: number;
    /**
     * @generated from protobuf field: int32 shield_specialization = 26;
     */
    shieldSpecialization: number;
    /**
     * @generated from protobuf field: int32 sacred_duty = 27;
     */
    sacredDuty: number;
    /**
     * @generated from protobuf field: bool swift_judgement = 28;
     */
    swiftJudgement: boolean;
    /**
     * @generated from protobuf field: int32 one_handed_weapon_specialization = 29;
     */
    oneHandedWeaponSpecialization: number;
    /**
     * @generated from protobuf field: int32 improved_hammer_of_justice = 30;
     */
    improvedHammerOfJustice: number;
    /**
     * @generated from protobuf field: bool templars_bulwark = 31;
     */
    templarsBulwark: boolean;
    /**
     * @generated from protobuf field: int32 reckoning = 32;
     */
    reckoning: number;
    /**
     * @generated from protobuf field: int32 iron_creed = 33;
     */
    ironCreed: number;
    /**
     * @generated from protobuf field: bool holy_shield = 34;
     */
    holyShield: boolean;
    /**
     * Retribution
     *
     * @generated from protobuf field: int32 deflection = 35;
     */
    deflection: number;
    /**
     * @generated from protobuf field: int32 benediction = 36;
     */
    benediction: number;
    /**
     * @generated from protobuf field: int32 improved_judgement = 37;
     */
    improvedJudgement: number;
    /**
     * @generated from protobuf field: int32 holy_conduit = 38;
     */
    holyConduit: number;
    /**
     * @generated from protobuf field: int32 conviction = 39;
     */
    conviction: number;
    /**
     * @generated from protobuf field: int32 vindication = 40;
     */
    vindication: number;
    /**
     * @generated from protobuf field: int32 sanctified_judgement = 41;
     */
    sanctifiedJudgement: number;
    /**
     * @generated from protobuf field: bool seal_of_command = 42;
     */
    sealOfCommand: boolean;
    /**
     * @generated from protobuf field: int32 pursuit_of_justice = 43;
     */
    pursuitOfJustice: number;
    /**
     * @generated from protobuf field: int32 eye_for_an_eye = 44;
     */
    eyeForAnEye: number;
    /**
     * @generated from protobuf field: bool sacred_arbiter = 45;
     */
    sacredArbiter: boolean;
    /**
     * @generated from protobuf field: int32 crusade = 46;
     */
    crusade: number;
    /**
     * @generated from protobuf field: int32 two_handed_weapon_specialization = 47;
     */
    twoHandedWeaponSpecialization: number;
    /**
     * @generated from protobuf field: int32 vengeance = 48;
     */
    vengeance: number;
    /**
     * @generated from protobuf field: bool repentance = 49;
     */
    repentance: boolean;
    /**
     * @generated from protobuf field: int32 champion_of_the_light = 50;
     */
    championOfTheLight: number;
    /**
     * @generated from protobuf field: int32 instrument_of_law = 51;
     */
    instrumentOfLaw: number;
    /**
     * @generated from protobuf field: bool twist_of_light = 52;
     */
    twistOfLight: boolean;
}
/**
 * @generated from protobuf message proto.PaladinOptions
 */
export interface PaladinOptions {
    /**
     * @generated from protobuf field: proto.PaladinSeal primarySeal = 1;
     */
    primarySeal: PaladinSeal;
    /**
     * @generated from protobuf field: proto.PaladinAura aura = 2;
     */
    aura: PaladinAura;
    /**
     * @generated from protobuf field: bool IsUsingJudgementStopAttack = 5 [json_name = "IsUsingJudgementStopAttack"];
     */
    isUsingJudgementStopAttack: boolean;
    /**
     * @generated from protobuf field: bool righteousFury = 8;
     */
    righteousFury: boolean;
    /**
     * @generated from protobuf field: proto.Blessings personalBlessing = 9;
     */
    personalBlessing: Blessings;
}
/**
 * @generated from protobuf message proto.RetributionPaladin
 */
export interface RetributionPaladin {
    /**
     * @generated from protobuf field: proto.PaladinOptions options = 3;
     */
    options?: PaladinOptions;
}
/**
 * @generated from protobuf message proto.RetributionPaladin.Rotation
 */
export interface RetributionPaladin_Rotation {
}
/**
 * @generated from protobuf message proto.ProtectionPaladin
 */
export interface ProtectionPaladin {
    /**
     * @generated from protobuf field: proto.PaladinOptions options = 3;
     */
    options?: PaladinOptions;
}
/**
 * @generated from protobuf message proto.ProtectionPaladin.Rotation
 */
export interface ProtectionPaladin_Rotation {
}
/**
 * @generated from protobuf message proto.HolyPaladin
 */
export interface HolyPaladin {
    /**
     * @generated from protobuf field: proto.PaladinOptions options = 3;
     */
    options?: PaladinOptions;
}
/**
 * @generated from protobuf message proto.HolyPaladin.Rotation
 */
export interface HolyPaladin_Rotation {
}
// END GENERATED

/**
 * @generated from protobuf enum proto.Blessings
 */
export enum Blessings {
    /**
     * @generated from protobuf enum value: BlessingUnknown = 0;
     */
    BlessingUnknown = 0,
    /**
     * @generated from protobuf enum value: BlessingOfKings = 1;
     */
    BlessingOfKings = 1,
    /**
     * @generated from protobuf enum value: BlessingOfMight = 2;
     */
    BlessingOfMight = 2,
    /**
     * @generated from protobuf enum value: BlessingOfSalvation = 3;
     */
    BlessingOfSalvation = 3,
    /**
     * @generated from protobuf enum value: BlessingOfWisdom = 4;
     */
    BlessingOfWisdom = 4,
    /**
     * @generated from protobuf enum value: BlessingOfSanctuary = 5;
     */
    BlessingOfSanctuary = 5,
    /**
     * @generated from protobuf enum value: BlessingOfLight = 6;
     */
    BlessingOfLight = 6
}
/**
 * @generated from protobuf enum proto.PaladinAura
 */
export enum PaladinAura {
    /**
     * @generated from protobuf enum value: NoPaladinAura = 0;
     */
    NoPaladinAura = 0,
    /**
     * @generated from protobuf enum value: SanctityAura = 1;
     */
    SanctityAura = 1,
    /**
     * @generated from protobuf enum value: DevotionAura = 2;
     */
    DevotionAura = 2,
    /**
     * @generated from protobuf enum value: RetributionAura = 3;
     */
    RetributionAura = 3,
    /**
     * @generated from protobuf enum value: ConcentrationAura = 4;
     */
    ConcentrationAura = 4,
    /**
     * @generated from protobuf enum value: FrostResistanceAura = 5;
     */
    FrostResistanceAura = 5,
    /**
     * @generated from protobuf enum value: ShadowResistanceAura = 6;
     */
    ShadowResistanceAura = 6,
    /**
     * @generated from protobuf enum value: FireResistanceAura = 7;
     */
    FireResistanceAura = 7
}
/**
 * @generated from protobuf enum proto.PaladinSeal
 */
export enum PaladinSeal {
    /**
     * @generated from protobuf enum value: NoSeal = 0;
     */
    NoSeal = 0,
    /**
     * @generated from protobuf enum value: Righteousness = 1;
     */
    Righteousness = 1,
    /**
     * @generated from protobuf enum value: Command = 2;
     */
    Command = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class PaladinTalents$Type extends MessageType<PaladinTalents> {
    constructor() {
        super("proto.PaladinTalents", [
            { no: 1, name: "improved_holy_strike", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "divine_strength", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "divine_intellect", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "healing_light", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "spiritual_focus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "improved_seals", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "unyielding_faith", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "voice_of_truth", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "reverence", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "purifying_power", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "infusion_of_light", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "illumination", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "divine_favor", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "divine_precision", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 15, name: "holy_shock", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "consecrated_ground", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "holy_power", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 18, name: "lights_vigil", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "toughness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "redoubt", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "precision", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "guardians_favor", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 23, name: "anticipation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 24, name: "improved_seal_of_fury", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 25, name: "improved_righteous_fury", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 26, name: "shield_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "sacred_duty", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 28, name: "swift_judgement", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 29, name: "one_handed_weapon_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 30, name: "improved_hammer_of_justice", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 31, name: "templars_bulwark", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 32, name: "reckoning", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 33, name: "iron_creed", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 34, name: "holy_shield", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 35, name: "deflection", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 36, name: "benediction", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 37, name: "improved_judgement", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 38, name: "holy_conduit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 39, name: "conviction", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 40, name: "vindication", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 41, name: "sanctified_judgement", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 42, name: "seal_of_command", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 43, name: "pursuit_of_justice", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 44, name: "eye_for_an_eye", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 45, name: "sacred_arbiter", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 46, name: "crusade", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 47, name: "two_handed_weapon_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 48, name: "vengeance", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 49, name: "repentance", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 50, name: "champion_of_the_light", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 51, name: "instrument_of_law", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 52, name: "twist_of_light", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PaladinTalents>): PaladinTalents {
        const message = { improvedHolyStrike: 0, divineStrength: 0, divineIntellect: 0, healingLight: 0, spiritualFocus: 0, improvedSeals: 0, unyieldingFaith: 0, voiceOfTruth: false, reverence: 0, purifyingPower: 0, infusionOfLight: 0, illumination: 0, divineFavor: false, divinePrecision: 0, holyShock: false, consecratedGround: 0, holyPower: 0, lightsVigil: false, toughness: 0, redoubt: 0, precision: 0, guardiansFavor: 0, anticipation: 0, improvedSealOfFury: false, improvedRighteousFury: 0, shieldSpecialization: 0, sacredDuty: 0, swiftJudgement: false, oneHandedWeaponSpecialization: 0, improvedHammerOfJustice: 0, templarsBulwark: false, reckoning: 0, ironCreed: 0, holyShield: false, deflection: 0, benediction: 0, improvedJudgement: 0, holyConduit: 0, conviction: 0, vindication: 0, sanctifiedJudgement: 0, sealOfCommand: false, pursuitOfJustice: 0, eyeForAnEye: 0, sacredArbiter: false, crusade: 0, twoHandedWeaponSpecialization: 0, vengeance: 0, repentance: false, championOfTheLight: 0, instrumentOfLaw: 0, twistOfLight: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PaladinTalents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaladinTalents): PaladinTalents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 improved_holy_strike */ 1:
                    message.improvedHolyStrike = reader.int32();
                    break;
                case /* int32 divine_strength */ 2:
                    message.divineStrength = reader.int32();
                    break;
                case /* int32 divine_intellect */ 3:
                    message.divineIntellect = reader.int32();
                    break;
                case /* int32 healing_light */ 4:
                    message.healingLight = reader.int32();
                    break;
                case /* int32 spiritual_focus */ 5:
                    message.spiritualFocus = reader.int32();
                    break;
                case /* int32 improved_seals */ 6:
                    message.improvedSeals = reader.int32();
                    break;
                case /* int32 unyielding_faith */ 7:
                    message.unyieldingFaith = reader.int32();
                    break;
                case /* bool voice_of_truth */ 8:
                    message.voiceOfTruth = reader.bool();
                    break;
                case /* int32 reverence */ 9:
                    message.reverence = reader.int32();
                    break;
                case /* int32 purifying_power */ 10:
                    message.purifyingPower = reader.int32();
                    break;
                case /* int32 infusion_of_light */ 11:
                    message.infusionOfLight = reader.int32();
                    break;
                case /* int32 illumination */ 12:
                    message.illumination = reader.int32();
                    break;
                case /* bool divine_favor */ 13:
                    message.divineFavor = reader.bool();
                    break;
                case /* int32 divine_precision */ 14:
                    message.divinePrecision = reader.int32();
                    break;
                case /* bool holy_shock */ 15:
                    message.holyShock = reader.bool();
                    break;
                case /* int32 consecrated_ground */ 16:
                    message.consecratedGround = reader.int32();
                    break;
                case /* int32 holy_power */ 17:
                    message.holyPower = reader.int32();
                    break;
                case /* bool lights_vigil */ 18:
                    message.lightsVigil = reader.bool();
                    break;
                case /* int32 toughness */ 19:
                    message.toughness = reader.int32();
                    break;
                case /* int32 redoubt */ 20:
                    message.redoubt = reader.int32();
                    break;
                case /* int32 precision */ 21:
                    message.precision = reader.int32();
                    break;
                case /* int32 guardians_favor */ 22:
                    message.guardiansFavor = reader.int32();
                    break;
                case /* int32 anticipation */ 23:
                    message.anticipation = reader.int32();
                    break;
                case /* bool improved_seal_of_fury */ 24:
                    message.improvedSealOfFury = reader.bool();
                    break;
                case /* int32 improved_righteous_fury */ 25:
                    message.improvedRighteousFury = reader.int32();
                    break;
                case /* int32 shield_specialization */ 26:
                    message.shieldSpecialization = reader.int32();
                    break;
                case /* int32 sacred_duty */ 27:
                    message.sacredDuty = reader.int32();
                    break;
                case /* bool swift_judgement */ 28:
                    message.swiftJudgement = reader.bool();
                    break;
                case /* int32 one_handed_weapon_specialization */ 29:
                    message.oneHandedWeaponSpecialization = reader.int32();
                    break;
                case /* int32 improved_hammer_of_justice */ 30:
                    message.improvedHammerOfJustice = reader.int32();
                    break;
                case /* bool templars_bulwark */ 31:
                    message.templarsBulwark = reader.bool();
                    break;
                case /* int32 reckoning */ 32:
                    message.reckoning = reader.int32();
                    break;
                case /* int32 iron_creed */ 33:
                    message.ironCreed = reader.int32();
                    break;
                case /* bool holy_shield */ 34:
                    message.holyShield = reader.bool();
                    break;
                case /* int32 deflection */ 35:
                    message.deflection = reader.int32();
                    break;
                case /* int32 benediction */ 36:
                    message.benediction = reader.int32();
                    break;
                case /* int32 improved_judgement */ 37:
                    message.improvedJudgement = reader.int32();
                    break;
                case /* int32 holy_conduit */ 38:
                    message.holyConduit = reader.int32();
                    break;
                case /* int32 conviction */ 39:
                    message.conviction = reader.int32();
                    break;
                case /* int32 vindication */ 40:
                    message.vindication = reader.int32();
                    break;
                case /* int32 sanctified_judgement */ 41:
                    message.sanctifiedJudgement = reader.int32();
                    break;
                case /* bool seal_of_command */ 42:
                    message.sealOfCommand = reader.bool();
                    break;
                case /* int32 pursuit_of_justice */ 43:
                    message.pursuitOfJustice = reader.int32();
                    break;
                case /* int32 eye_for_an_eye */ 44:
                    message.eyeForAnEye = reader.int32();
                    break;
                case /* bool sacred_arbiter */ 45:
                    message.sacredArbiter = reader.bool();
                    break;
                case /* int32 crusade */ 46:
                    message.crusade = reader.int32();
                    break;
                case /* int32 two_handed_weapon_specialization */ 47:
                    message.twoHandedWeaponSpecialization = reader.int32();
                    break;
                case /* int32 vengeance */ 48:
                    message.vengeance = reader.int32();
                    break;
                case /* bool repentance */ 49:
                    message.repentance = reader.bool();
                    break;
                case /* int32 champion_of_the_light */ 50:
                    message.championOfTheLight = reader.int32();
                    break;
                case /* int32 instrument_of_law */ 51:
                    message.instrumentOfLaw = reader.int32();
                    break;
                case /* bool twist_of_light */ 52:
                    message.twistOfLight = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaladinTalents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 improved_holy_strike = 1; */
        if (message.improvedHolyStrike !== 0)
            writer.tag(1, WireType.Varint).int32(message.improvedHolyStrike);
        /* int32 divine_strength = 2; */
        if (message.divineStrength !== 0)
            writer.tag(2, WireType.Varint).int32(message.divineStrength);
        /* int32 divine_intellect = 3; */
        if (message.divineIntellect !== 0)
            writer.tag(3, WireType.Varint).int32(message.divineIntellect);
        /* int32 healing_light = 4; */
        if (message.healingLight !== 0)
            writer.tag(4, WireType.Varint).int32(message.healingLight);
        /* int32 spiritual_focus = 5; */
        if (message.spiritualFocus !== 0)
            writer.tag(5, WireType.Varint).int32(message.spiritualFocus);
        /* int32 improved_seals = 6; */
        if (message.improvedSeals !== 0)
            writer.tag(6, WireType.Varint).int32(message.improvedSeals);
        /* int32 unyielding_faith = 7; */
        if (message.unyieldingFaith !== 0)
            writer.tag(7, WireType.Varint).int32(message.unyieldingFaith);
        /* bool voice_of_truth = 8; */
        if (message.voiceOfTruth !== false)
            writer.tag(8, WireType.Varint).bool(message.voiceOfTruth);
        /* int32 reverence = 9; */
        if (message.reverence !== 0)
            writer.tag(9, WireType.Varint).int32(message.reverence);
        /* int32 purifying_power = 10; */
        if (message.purifyingPower !== 0)
            writer.tag(10, WireType.Varint).int32(message.purifyingPower);
        /* int32 infusion_of_light = 11; */
        if (message.infusionOfLight !== 0)
            writer.tag(11, WireType.Varint).int32(message.infusionOfLight);
        /* int32 illumination = 12; */
        if (message.illumination !== 0)
            writer.tag(12, WireType.Varint).int32(message.illumination);
        /* bool divine_favor = 13; */
        if (message.divineFavor !== false)
            writer.tag(13, WireType.Varint).bool(message.divineFavor);
        /* int32 divine_precision = 14; */
        if (message.divinePrecision !== 0)
            writer.tag(14, WireType.Varint).int32(message.divinePrecision);
        /* bool holy_shock = 15; */
        if (message.holyShock !== false)
            writer.tag(15, WireType.Varint).bool(message.holyShock);
        /* int32 consecrated_ground = 16; */
        if (message.consecratedGround !== 0)
            writer.tag(16, WireType.Varint).int32(message.consecratedGround);
        /* int32 holy_power = 17; */
        if (message.holyPower !== 0)
            writer.tag(17, WireType.Varint).int32(message.holyPower);
        /* bool lights_vigil = 18; */
        if (message.lightsVigil !== false)
            writer.tag(18, WireType.Varint).bool(message.lightsVigil);
        /* int32 toughness = 19; */
        if (message.toughness !== 0)
            writer.tag(19, WireType.Varint).int32(message.toughness);
        /* int32 redoubt = 20; */
        if (message.redoubt !== 0)
            writer.tag(20, WireType.Varint).int32(message.redoubt);
        /* int32 precision = 21; */
        if (message.precision !== 0)
            writer.tag(21, WireType.Varint).int32(message.precision);
        /* int32 guardians_favor = 22; */
        if (message.guardiansFavor !== 0)
            writer.tag(22, WireType.Varint).int32(message.guardiansFavor);
        /* int32 anticipation = 23; */
        if (message.anticipation !== 0)
            writer.tag(23, WireType.Varint).int32(message.anticipation);
        /* bool improved_seal_of_fury = 24; */
        if (message.improvedSealOfFury !== false)
            writer.tag(24, WireType.Varint).bool(message.improvedSealOfFury);
        /* int32 improved_righteous_fury = 25; */
        if (message.improvedRighteousFury !== 0)
            writer.tag(25, WireType.Varint).int32(message.improvedRighteousFury);
        /* int32 shield_specialization = 26; */
        if (message.shieldSpecialization !== 0)
            writer.tag(26, WireType.Varint).int32(message.shieldSpecialization);
        /* int32 sacred_duty = 27; */
        if (message.sacredDuty !== 0)
            writer.tag(27, WireType.Varint).int32(message.sacredDuty);
        /* bool swift_judgement = 28; */
        if (message.swiftJudgement !== false)
            writer.tag(28, WireType.Varint).bool(message.swiftJudgement);
        /* int32 one_handed_weapon_specialization = 29; */
        if (message.oneHandedWeaponSpecialization !== 0)
            writer.tag(29, WireType.Varint).int32(message.oneHandedWeaponSpecialization);
        /* int32 improved_hammer_of_justice = 30; */
        if (message.improvedHammerOfJustice !== 0)
            writer.tag(30, WireType.Varint).int32(message.improvedHammerOfJustice);
        /* bool templars_bulwark = 31; */
        if (message.templarsBulwark !== false)
            writer.tag(31, WireType.Varint).bool(message.templarsBulwark);
        /* int32 reckoning = 32; */
        if (message.reckoning !== 0)
            writer.tag(32, WireType.Varint).int32(message.reckoning);
        /* int32 iron_creed = 33; */
        if (message.ironCreed !== 0)
            writer.tag(33, WireType.Varint).int32(message.ironCreed);
        /* bool holy_shield = 34; */
        if (message.holyShield !== false)
            writer.tag(34, WireType.Varint).bool(message.holyShield);
        /* int32 deflection = 35; */
        if (message.deflection !== 0)
            writer.tag(35, WireType.Varint).int32(message.deflection);
        /* int32 benediction = 36; */
        if (message.benediction !== 0)
            writer.tag(36, WireType.Varint).int32(message.benediction);
        /* int32 improved_judgement = 37; */
        if (message.improvedJudgement !== 0)
            writer.tag(37, WireType.Varint).int32(message.improvedJudgement);
        /* int32 holy_conduit = 38; */
        if (message.holyConduit !== 0)
            writer.tag(38, WireType.Varint).int32(message.holyConduit);
        /* int32 conviction = 39; */
        if (message.conviction !== 0)
            writer.tag(39, WireType.Varint).int32(message.conviction);
        /* int32 vindication = 40; */
        if (message.vindication !== 0)
            writer.tag(40, WireType.Varint).int32(message.vindication);
        /* int32 sanctified_judgement = 41; */
        if (message.sanctifiedJudgement !== 0)
            writer.tag(41, WireType.Varint).int32(message.sanctifiedJudgement);
        /* bool seal_of_command = 42; */
        if (message.sealOfCommand !== false)
            writer.tag(42, WireType.Varint).bool(message.sealOfCommand);
        /* int32 pursuit_of_justice = 43; */
        if (message.pursuitOfJustice !== 0)
            writer.tag(43, WireType.Varint).int32(message.pursuitOfJustice);
        /* int32 eye_for_an_eye = 44; */
        if (message.eyeForAnEye !== 0)
            writer.tag(44, WireType.Varint).int32(message.eyeForAnEye);
        /* bool sacred_arbiter = 45; */
        if (message.sacredArbiter !== false)
            writer.tag(45, WireType.Varint).bool(message.sacredArbiter);
        /* int32 crusade = 46; */
        if (message.crusade !== 0)
            writer.tag(46, WireType.Varint).int32(message.crusade);
        /* int32 two_handed_weapon_specialization = 47; */
        if (message.twoHandedWeaponSpecialization !== 0)
            writer.tag(47, WireType.Varint).int32(message.twoHandedWeaponSpecialization);
        /* int32 vengeance = 48; */
        if (message.vengeance !== 0)
            writer.tag(48, WireType.Varint).int32(message.vengeance);
        /* bool repentance = 49; */
        if (message.repentance !== false)
            writer.tag(49, WireType.Varint).bool(message.repentance);
        /* int32 champion_of_the_light = 50; */
        if (message.championOfTheLight !== 0)
            writer.tag(50, WireType.Varint).int32(message.championOfTheLight);
        /* int32 instrument_of_law = 51; */
        if (message.instrumentOfLaw !== 0)
            writer.tag(51, WireType.Varint).int32(message.instrumentOfLaw);
        /* bool twist_of_light = 52; */
        if (message.twistOfLight !== false)
            writer.tag(52, WireType.Varint).bool(message.twistOfLight);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.PaladinTalents
 */
export const PaladinTalents = new PaladinTalents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaladinOptions$Type extends MessageType<PaladinOptions> {
    constructor() {
        super("proto.PaladinOptions", [
            { no: 1, name: "primarySeal", kind: "enum", T: () => ["proto.PaladinSeal", PaladinSeal] },
            { no: 2, name: "aura", kind: "enum", T: () => ["proto.PaladinAura", PaladinAura] },
            { no: 5, name: "IsUsingJudgementStopAttack", kind: "scalar", jsonName: "IsUsingJudgementStopAttack", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "righteousFury", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "personalBlessing", kind: "enum", T: () => ["proto.Blessings", Blessings] }
        ]);
    }
    create(value?: PartialMessage<PaladinOptions>): PaladinOptions {
        const message = { primarySeal: 0, aura: 0, isUsingJudgementStopAttack: false, righteousFury: false, personalBlessing: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PaladinOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PaladinOptions): PaladinOptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.PaladinSeal primarySeal */ 1:
                    message.primarySeal = reader.int32();
                    break;
                case /* proto.PaladinAura aura */ 2:
                    message.aura = reader.int32();
                    break;
                case /* bool IsUsingJudgementStopAttack = 5 [json_name = "IsUsingJudgementStopAttack"];*/ 5:
                    message.isUsingJudgementStopAttack = reader.bool();
                    break;
                case /* bool righteousFury */ 8:
                    message.righteousFury = reader.bool();
                    break;
                case /* proto.Blessings personalBlessing */ 9:
                    message.personalBlessing = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PaladinOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.PaladinSeal primarySeal = 1; */
        if (message.primarySeal !== 0)
            writer.tag(1, WireType.Varint).int32(message.primarySeal);
        /* proto.PaladinAura aura = 2; */
        if (message.aura !== 0)
            writer.tag(2, WireType.Varint).int32(message.aura);
        /* bool IsUsingJudgementStopAttack = 5 [json_name = "IsUsingJudgementStopAttack"]; */
        if (message.isUsingJudgementStopAttack !== false)
            writer.tag(5, WireType.Varint).bool(message.isUsingJudgementStopAttack);
        /* bool righteousFury = 8; */
        if (message.righteousFury !== false)
            writer.tag(8, WireType.Varint).bool(message.righteousFury);
        /* proto.Blessings personalBlessing = 9; */
        if (message.personalBlessing !== 0)
            writer.tag(9, WireType.Varint).int32(message.personalBlessing);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.PaladinOptions
 */
export const PaladinOptions = new PaladinOptions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RetributionPaladin$Type extends MessageType<RetributionPaladin> {
    constructor() {
        super("proto.RetributionPaladin", [
            { no: 3, name: "options", kind: "message", T: () => PaladinOptions }
        ]);
    }
    create(value?: PartialMessage<RetributionPaladin>): RetributionPaladin {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RetributionPaladin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RetributionPaladin): RetributionPaladin {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.PaladinOptions options */ 3:
                    message.options = PaladinOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RetributionPaladin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.PaladinOptions options = 3; */
        if (message.options)
            PaladinOptions.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RetributionPaladin
 */
export const RetributionPaladin = new RetributionPaladin$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RetributionPaladin_Rotation$Type extends MessageType<RetributionPaladin_Rotation> {
    constructor() {
        super("proto.RetributionPaladin.Rotation", []);
    }
    create(value?: PartialMessage<RetributionPaladin_Rotation>): RetributionPaladin_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RetributionPaladin_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RetributionPaladin_Rotation): RetributionPaladin_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: RetributionPaladin_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RetributionPaladin.Rotation
 */
export const RetributionPaladin_Rotation = new RetributionPaladin_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProtectionPaladin$Type extends MessageType<ProtectionPaladin> {
    constructor() {
        super("proto.ProtectionPaladin", [
            { no: 3, name: "options", kind: "message", T: () => PaladinOptions }
        ]);
    }
    create(value?: PartialMessage<ProtectionPaladin>): ProtectionPaladin {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ProtectionPaladin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProtectionPaladin): ProtectionPaladin {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.PaladinOptions options */ 3:
                    message.options = PaladinOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProtectionPaladin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.PaladinOptions options = 3; */
        if (message.options)
            PaladinOptions.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ProtectionPaladin
 */
export const ProtectionPaladin = new ProtectionPaladin$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProtectionPaladin_Rotation$Type extends MessageType<ProtectionPaladin_Rotation> {
    constructor() {
        super("proto.ProtectionPaladin.Rotation", []);
    }
    create(value?: PartialMessage<ProtectionPaladin_Rotation>): ProtectionPaladin_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ProtectionPaladin_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProtectionPaladin_Rotation): ProtectionPaladin_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ProtectionPaladin_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ProtectionPaladin.Rotation
 */
export const ProtectionPaladin_Rotation = new ProtectionPaladin_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HolyPaladin$Type extends MessageType<HolyPaladin> {
    constructor() {
        super("proto.HolyPaladin", [
            { no: 3, name: "options", kind: "message", T: () => PaladinOptions }
        ]);
    }
    create(value?: PartialMessage<HolyPaladin>): HolyPaladin {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HolyPaladin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HolyPaladin): HolyPaladin {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.PaladinOptions options */ 3:
                    message.options = PaladinOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HolyPaladin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.PaladinOptions options = 3; */
        if (message.options)
            PaladinOptions.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.HolyPaladin
 */
export const HolyPaladin = new HolyPaladin$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HolyPaladin_Rotation$Type extends MessageType<HolyPaladin_Rotation> {
    constructor() {
        super("proto.HolyPaladin.Rotation", []);
    }
    create(value?: PartialMessage<HolyPaladin_Rotation>): HolyPaladin_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HolyPaladin_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HolyPaladin_Rotation): HolyPaladin_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: HolyPaladin_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.HolyPaladin.Rotation
 */
export const HolyPaladin_Rotation = new HolyPaladin_Rotation$Type();
