// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "priest.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { UnitReference } from "./common";
/**
 * DO NOT REMOVE THE COMMENTS
 * BEGIN GENERATED
 * PriestTalents message.
 *
 * @generated from protobuf message proto.PriestTalents
 */
export interface PriestTalents {
    /**
     * Discipline
     *
     * @generated from protobuf field: int32 power_in_light = 1;
     */
    powerInLight: number;
    /**
     * @generated from protobuf field: int32 wand_specialization = 2;
     */
    wandSpecialization: number;
    /**
     * @generated from protobuf field: int32 twin_disciplines = 3;
     */
    twinDisciplines: number;
    /**
     * @generated from protobuf field: int32 silent_resolve = 4;
     */
    silentResolve: number;
    /**
     * @generated from protobuf field: int32 holy_precision = 5;
     */
    holyPrecision: number;
    /**
     * @generated from protobuf field: int32 improved_power_word_shield = 6;
     */
    improvedPowerWordShield: number;
    /**
     * @generated from protobuf field: int32 martyrdom = 7;
     */
    martyrdom: number;
    /**
     * @generated from protobuf field: int32 mental_agility = 8;
     */
    mentalAgility: number;
    /**
     * @generated from protobuf field: bool inner_focus = 9;
     */
    innerFocus: boolean;
    /**
     * @generated from protobuf field: int32 meditation = 10;
     */
    meditation: number;
    /**
     * @generated from protobuf field: int32 improved_inner_fire = 11;
     */
    improvedInnerFire: number;
    /**
     * @generated from protobuf field: int32 mental_strength = 12;
     */
    mentalStrength: number;
    /**
     * @generated from protobuf field: bool soul_warding = 13;
     */
    soulWarding: boolean;
    /**
     * @generated from protobuf field: int32 improved_mana_burn = 14;
     */
    improvedManaBurn: number;
    /**
     * @generated from protobuf field: bool penance = 15;
     */
    penance: boolean;
    /**
     * @generated from protobuf field: int32 renewed_hope = 16;
     */
    renewedHope: number;
    /**
     * @generated from protobuf field: int32 divine_aegis = 17;
     */
    divineAegis: number;
    /**
     * @generated from protobuf field: bool power_infusion = 18;
     */
    powerInfusion: boolean;
    /**
     * Holy
     *
     * @generated from protobuf field: int32 twilight_focus = 19;
     */
    twilightFocus: number;
    /**
     * @generated from protobuf field: int32 improved_renew = 20;
     */
    improvedRenew: number;
    /**
     * @generated from protobuf field: int32 holy_specialization = 21;
     */
    holySpecialization: number;
    /**
     * @generated from protobuf field: int32 spell_warding = 22;
     */
    spellWarding: number;
    /**
     * @generated from protobuf field: int32 divine_fury = 23;
     */
    divineFury: number;
    /**
     * @generated from protobuf field: bool holy_nova = 24;
     */
    holyNova: boolean;
    /**
     * @generated from protobuf field: int32 blessed_recovery = 25;
     */
    blessedRecovery: number;
    /**
     * @generated from protobuf field: int32 inspiration = 26;
     */
    inspiration: number;
    /**
     * @generated from protobuf field: int32 holy_reach = 27;
     */
    holyReach: number;
    /**
     * @generated from protobuf field: int32 improved_healing = 28;
     */
    improvedHealing: number;
    /**
     * @generated from protobuf field: int32 searing_light = 29;
     */
    searingLight: number;
    /**
     * @generated from protobuf field: bool binding_heal = 30;
     */
    bindingHeal: boolean;
    /**
     * @generated from protobuf field: int32 litany_of_light = 31;
     */
    litanyOfLight: number;
    /**
     * @generated from protobuf field: bool spirit_of_redemption = 32;
     */
    spiritOfRedemption: boolean;
    /**
     * @generated from protobuf field: int32 spiritual_guidance = 33;
     */
    spiritualGuidance: number;
    /**
     * @generated from protobuf field: int32 spiritual_healing = 34;
     */
    spiritualHealing: number;
    /**
     * @generated from protobuf field: bool prayer_of_mending = 35;
     */
    prayerOfMending: boolean;
    /**
     * Shadow
     *
     * @generated from protobuf field: int32 shadow_focus = 36;
     */
    shadowFocus: number;
    /**
     * @generated from protobuf field: int32 blackout = 37;
     */
    blackout: number;
    /**
     * @generated from protobuf field: int32 spirit_tap = 38;
     */
    spiritTap: number;
    /**
     * @generated from protobuf field: int32 shadow_affinity = 39;
     */
    shadowAffinity: number;
    /**
     * @generated from protobuf field: int32 improved_shadow_word_pain = 40;
     */
    improvedShadowWordPain: number;
    /**
     * @generated from protobuf field: int32 shadow_reach = 41;
     */
    shadowReach: number;
    /**
     * @generated from protobuf field: int32 improved_mind_blast = 42;
     */
    improvedMindBlast: number;
    /**
     * @generated from protobuf field: int32 improved_psychic_scream = 43;
     */
    improvedPsychicScream: number;
    /**
     * @generated from protobuf field: bool mind_flay = 44;
     */
    mindFlay: boolean;
    /**
     * @generated from protobuf field: int32 improved_mind_flay = 45;
     */
    improvedMindFlay: number;
    /**
     * @generated from protobuf field: int32 improved_fade = 46;
     */
    improvedFade: number;
    /**
     * @generated from protobuf field: bool vampiric_embrace = 47;
     */
    vampiricEmbrace: boolean;
    /**
     * @generated from protobuf field: int32 shadow_weaving = 48;
     */
    shadowWeaving: number;
    /**
     * @generated from protobuf field: bool silence = 49;
     */
    silence: boolean;
    /**
     * @generated from protobuf field: int32 devouring_contagion = 50;
     */
    devouringContagion: number;
    /**
     * @generated from protobuf field: int32 early_demise = 51;
     */
    earlyDemise: number;
    /**
     * @generated from protobuf field: int32 darkness = 52;
     */
    darkness: number;
    /**
     * @generated from protobuf field: bool shadowform = 53;
     */
    shadowform: boolean;
}
// END GENERATED

/**
 * @generated from protobuf message proto.ShadowPriest
 */
export interface ShadowPriest {
    /**
     * @generated from protobuf field: proto.ShadowPriest.Options options = 3;
     */
    options?: ShadowPriest_Options;
}
/**
 * @generated from protobuf message proto.ShadowPriest.Rotation
 */
export interface ShadowPriest_Rotation {
}
/**
 * @generated from protobuf message proto.ShadowPriest.Options
 */
export interface ShadowPriest_Options {
    /**
     * @generated from protobuf field: bool use_shadowfiend = 1;
     */
    useShadowfiend: boolean;
    /**
     * @generated from protobuf field: proto.ShadowPriest.Options.Armor armor = 2;
     */
    armor: ShadowPriest_Options_Armor;
    /**
     * @generated from protobuf field: bool use_mind_blast = 4;
     */
    useMindBlast: boolean;
    /**
     * @generated from protobuf field: proto.UnitReference power_infusion_target = 5;
     */
    powerInfusionTarget?: UnitReference;
    /**
     * @deprecated
     * @generated from protobuf field: double latency = 6 [deprecated = true];
     */
    latency: number; // Latency between actions
}
/**
 * @generated from protobuf enum proto.ShadowPriest.Options.Armor
 */
export enum ShadowPriest_Options_Armor {
    /**
     * @generated from protobuf enum value: NoArmor = 0;
     */
    NoArmor = 0,
    /**
     * @generated from protobuf enum value: InnerFire = 1;
     */
    InnerFire = 1
}
/**
 * Forever's holy damage build: Smite and Holy Fire carried by Power in Light and
 * Searing Light, rather than Shadowform and dots.
 *
 * @generated from protobuf message proto.SmitePriest
 */
export interface SmitePriest {
    /**
     * @generated from protobuf field: proto.SmitePriest.Options options = 3;
     */
    options?: SmitePriest_Options;
}
/**
 * @generated from protobuf message proto.SmitePriest.Rotation
 */
export interface SmitePriest_Rotation {
}
/**
 * @generated from protobuf message proto.SmitePriest.Options
 */
export interface SmitePriest_Options {
    /**
     * @generated from protobuf field: proto.SmitePriest.Options.Armor armor = 1;
     */
    armor: SmitePriest_Options_Armor;
    /**
     * @generated from protobuf field: proto.UnitReference power_infusion_target = 2;
     */
    powerInfusionTarget?: UnitReference;
}
/**
 * @generated from protobuf enum proto.SmitePriest.Options.Armor
 */
export enum SmitePriest_Options_Armor {
    /**
     * @generated from protobuf enum value: NoArmor = 0;
     */
    NoArmor = 0,
    /**
     * @generated from protobuf enum value: InnerFire = 1;
     */
    InnerFire = 1
}
/**
 * @generated from protobuf message proto.HealingPriest
 */
export interface HealingPriest {
    /**
     * @generated from protobuf field: proto.HealingPriest.Options options = 3;
     */
    options?: HealingPriest_Options;
}
/**
 * @generated from protobuf message proto.HealingPriest.Rotation
 */
export interface HealingPriest_Rotation {
}
/**
 * @generated from protobuf message proto.HealingPriest.Options
 */
export interface HealingPriest_Options {
    /**
     * @generated from protobuf field: bool use_inner_fire = 2;
     */
    useInnerFire: boolean;
    /**
     * @generated from protobuf field: proto.UnitReference power_infusion_target = 1;
     */
    powerInfusionTarget?: UnitReference;
}
// @generated message type with reflection information, may provide speed optimized methods
class PriestTalents$Type extends MessageType<PriestTalents> {
    constructor() {
        super("proto.PriestTalents", [
            { no: 1, name: "power_in_light", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "wand_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "twin_disciplines", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "silent_resolve", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "holy_precision", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "improved_power_word_shield", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "martyrdom", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "mental_agility", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "inner_focus", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "meditation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "improved_inner_fire", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "mental_strength", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "soul_warding", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "improved_mana_burn", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 15, name: "penance", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 16, name: "renewed_hope", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "divine_aegis", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 18, name: "power_infusion", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "twilight_focus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "improved_renew", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "holy_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "spell_warding", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 23, name: "divine_fury", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 24, name: "holy_nova", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 25, name: "blessed_recovery", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 26, name: "inspiration", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "holy_reach", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 28, name: "improved_healing", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 29, name: "searing_light", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 30, name: "binding_heal", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 31, name: "litany_of_light", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 32, name: "spirit_of_redemption", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 33, name: "spiritual_guidance", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 34, name: "spiritual_healing", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 35, name: "prayer_of_mending", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 36, name: "shadow_focus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 37, name: "blackout", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 38, name: "spirit_tap", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 39, name: "shadow_affinity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 40, name: "improved_shadow_word_pain", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 41, name: "shadow_reach", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 42, name: "improved_mind_blast", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 43, name: "improved_psychic_scream", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 44, name: "mind_flay", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 45, name: "improved_mind_flay", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 46, name: "improved_fade", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 47, name: "vampiric_embrace", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 48, name: "shadow_weaving", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 49, name: "silence", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 50, name: "devouring_contagion", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 51, name: "early_demise", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 52, name: "darkness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 53, name: "shadowform", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PriestTalents>): PriestTalents {
        const message = { powerInLight: 0, wandSpecialization: 0, twinDisciplines: 0, silentResolve: 0, holyPrecision: 0, improvedPowerWordShield: 0, martyrdom: 0, mentalAgility: 0, innerFocus: false, meditation: 0, improvedInnerFire: 0, mentalStrength: 0, soulWarding: false, improvedManaBurn: 0, penance: false, renewedHope: 0, divineAegis: 0, powerInfusion: false, twilightFocus: 0, improvedRenew: 0, holySpecialization: 0, spellWarding: 0, divineFury: 0, holyNova: false, blessedRecovery: 0, inspiration: 0, holyReach: 0, improvedHealing: 0, searingLight: 0, bindingHeal: false, litanyOfLight: 0, spiritOfRedemption: false, spiritualGuidance: 0, spiritualHealing: 0, prayerOfMending: false, shadowFocus: 0, blackout: 0, spiritTap: 0, shadowAffinity: 0, improvedShadowWordPain: 0, shadowReach: 0, improvedMindBlast: 0, improvedPsychicScream: 0, mindFlay: false, improvedMindFlay: 0, improvedFade: 0, vampiricEmbrace: false, shadowWeaving: 0, silence: false, devouringContagion: 0, earlyDemise: 0, darkness: 0, shadowform: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PriestTalents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PriestTalents): PriestTalents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 power_in_light */ 1:
                    message.powerInLight = reader.int32();
                    break;
                case /* int32 wand_specialization */ 2:
                    message.wandSpecialization = reader.int32();
                    break;
                case /* int32 twin_disciplines */ 3:
                    message.twinDisciplines = reader.int32();
                    break;
                case /* int32 silent_resolve */ 4:
                    message.silentResolve = reader.int32();
                    break;
                case /* int32 holy_precision */ 5:
                    message.holyPrecision = reader.int32();
                    break;
                case /* int32 improved_power_word_shield */ 6:
                    message.improvedPowerWordShield = reader.int32();
                    break;
                case /* int32 martyrdom */ 7:
                    message.martyrdom = reader.int32();
                    break;
                case /* int32 mental_agility */ 8:
                    message.mentalAgility = reader.int32();
                    break;
                case /* bool inner_focus */ 9:
                    message.innerFocus = reader.bool();
                    break;
                case /* int32 meditation */ 10:
                    message.meditation = reader.int32();
                    break;
                case /* int32 improved_inner_fire */ 11:
                    message.improvedInnerFire = reader.int32();
                    break;
                case /* int32 mental_strength */ 12:
                    message.mentalStrength = reader.int32();
                    break;
                case /* bool soul_warding */ 13:
                    message.soulWarding = reader.bool();
                    break;
                case /* int32 improved_mana_burn */ 14:
                    message.improvedManaBurn = reader.int32();
                    break;
                case /* bool penance */ 15:
                    message.penance = reader.bool();
                    break;
                case /* int32 renewed_hope */ 16:
                    message.renewedHope = reader.int32();
                    break;
                case /* int32 divine_aegis */ 17:
                    message.divineAegis = reader.int32();
                    break;
                case /* bool power_infusion */ 18:
                    message.powerInfusion = reader.bool();
                    break;
                case /* int32 twilight_focus */ 19:
                    message.twilightFocus = reader.int32();
                    break;
                case /* int32 improved_renew */ 20:
                    message.improvedRenew = reader.int32();
                    break;
                case /* int32 holy_specialization */ 21:
                    message.holySpecialization = reader.int32();
                    break;
                case /* int32 spell_warding */ 22:
                    message.spellWarding = reader.int32();
                    break;
                case /* int32 divine_fury */ 23:
                    message.divineFury = reader.int32();
                    break;
                case /* bool holy_nova */ 24:
                    message.holyNova = reader.bool();
                    break;
                case /* int32 blessed_recovery */ 25:
                    message.blessedRecovery = reader.int32();
                    break;
                case /* int32 inspiration */ 26:
                    message.inspiration = reader.int32();
                    break;
                case /* int32 holy_reach */ 27:
                    message.holyReach = reader.int32();
                    break;
                case /* int32 improved_healing */ 28:
                    message.improvedHealing = reader.int32();
                    break;
                case /* int32 searing_light */ 29:
                    message.searingLight = reader.int32();
                    break;
                case /* bool binding_heal */ 30:
                    message.bindingHeal = reader.bool();
                    break;
                case /* int32 litany_of_light */ 31:
                    message.litanyOfLight = reader.int32();
                    break;
                case /* bool spirit_of_redemption */ 32:
                    message.spiritOfRedemption = reader.bool();
                    break;
                case /* int32 spiritual_guidance */ 33:
                    message.spiritualGuidance = reader.int32();
                    break;
                case /* int32 spiritual_healing */ 34:
                    message.spiritualHealing = reader.int32();
                    break;
                case /* bool prayer_of_mending */ 35:
                    message.prayerOfMending = reader.bool();
                    break;
                case /* int32 shadow_focus */ 36:
                    message.shadowFocus = reader.int32();
                    break;
                case /* int32 blackout */ 37:
                    message.blackout = reader.int32();
                    break;
                case /* int32 spirit_tap */ 38:
                    message.spiritTap = reader.int32();
                    break;
                case /* int32 shadow_affinity */ 39:
                    message.shadowAffinity = reader.int32();
                    break;
                case /* int32 improved_shadow_word_pain */ 40:
                    message.improvedShadowWordPain = reader.int32();
                    break;
                case /* int32 shadow_reach */ 41:
                    message.shadowReach = reader.int32();
                    break;
                case /* int32 improved_mind_blast */ 42:
                    message.improvedMindBlast = reader.int32();
                    break;
                case /* int32 improved_psychic_scream */ 43:
                    message.improvedPsychicScream = reader.int32();
                    break;
                case /* bool mind_flay */ 44:
                    message.mindFlay = reader.bool();
                    break;
                case /* int32 improved_mind_flay */ 45:
                    message.improvedMindFlay = reader.int32();
                    break;
                case /* int32 improved_fade */ 46:
                    message.improvedFade = reader.int32();
                    break;
                case /* bool vampiric_embrace */ 47:
                    message.vampiricEmbrace = reader.bool();
                    break;
                case /* int32 shadow_weaving */ 48:
                    message.shadowWeaving = reader.int32();
                    break;
                case /* bool silence */ 49:
                    message.silence = reader.bool();
                    break;
                case /* int32 devouring_contagion */ 50:
                    message.devouringContagion = reader.int32();
                    break;
                case /* int32 early_demise */ 51:
                    message.earlyDemise = reader.int32();
                    break;
                case /* int32 darkness */ 52:
                    message.darkness = reader.int32();
                    break;
                case /* bool shadowform */ 53:
                    message.shadowform = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PriestTalents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 power_in_light = 1; */
        if (message.powerInLight !== 0)
            writer.tag(1, WireType.Varint).int32(message.powerInLight);
        /* int32 wand_specialization = 2; */
        if (message.wandSpecialization !== 0)
            writer.tag(2, WireType.Varint).int32(message.wandSpecialization);
        /* int32 twin_disciplines = 3; */
        if (message.twinDisciplines !== 0)
            writer.tag(3, WireType.Varint).int32(message.twinDisciplines);
        /* int32 silent_resolve = 4; */
        if (message.silentResolve !== 0)
            writer.tag(4, WireType.Varint).int32(message.silentResolve);
        /* int32 holy_precision = 5; */
        if (message.holyPrecision !== 0)
            writer.tag(5, WireType.Varint).int32(message.holyPrecision);
        /* int32 improved_power_word_shield = 6; */
        if (message.improvedPowerWordShield !== 0)
            writer.tag(6, WireType.Varint).int32(message.improvedPowerWordShield);
        /* int32 martyrdom = 7; */
        if (message.martyrdom !== 0)
            writer.tag(7, WireType.Varint).int32(message.martyrdom);
        /* int32 mental_agility = 8; */
        if (message.mentalAgility !== 0)
            writer.tag(8, WireType.Varint).int32(message.mentalAgility);
        /* bool inner_focus = 9; */
        if (message.innerFocus !== false)
            writer.tag(9, WireType.Varint).bool(message.innerFocus);
        /* int32 meditation = 10; */
        if (message.meditation !== 0)
            writer.tag(10, WireType.Varint).int32(message.meditation);
        /* int32 improved_inner_fire = 11; */
        if (message.improvedInnerFire !== 0)
            writer.tag(11, WireType.Varint).int32(message.improvedInnerFire);
        /* int32 mental_strength = 12; */
        if (message.mentalStrength !== 0)
            writer.tag(12, WireType.Varint).int32(message.mentalStrength);
        /* bool soul_warding = 13; */
        if (message.soulWarding !== false)
            writer.tag(13, WireType.Varint).bool(message.soulWarding);
        /* int32 improved_mana_burn = 14; */
        if (message.improvedManaBurn !== 0)
            writer.tag(14, WireType.Varint).int32(message.improvedManaBurn);
        /* bool penance = 15; */
        if (message.penance !== false)
            writer.tag(15, WireType.Varint).bool(message.penance);
        /* int32 renewed_hope = 16; */
        if (message.renewedHope !== 0)
            writer.tag(16, WireType.Varint).int32(message.renewedHope);
        /* int32 divine_aegis = 17; */
        if (message.divineAegis !== 0)
            writer.tag(17, WireType.Varint).int32(message.divineAegis);
        /* bool power_infusion = 18; */
        if (message.powerInfusion !== false)
            writer.tag(18, WireType.Varint).bool(message.powerInfusion);
        /* int32 twilight_focus = 19; */
        if (message.twilightFocus !== 0)
            writer.tag(19, WireType.Varint).int32(message.twilightFocus);
        /* int32 improved_renew = 20; */
        if (message.improvedRenew !== 0)
            writer.tag(20, WireType.Varint).int32(message.improvedRenew);
        /* int32 holy_specialization = 21; */
        if (message.holySpecialization !== 0)
            writer.tag(21, WireType.Varint).int32(message.holySpecialization);
        /* int32 spell_warding = 22; */
        if (message.spellWarding !== 0)
            writer.tag(22, WireType.Varint).int32(message.spellWarding);
        /* int32 divine_fury = 23; */
        if (message.divineFury !== 0)
            writer.tag(23, WireType.Varint).int32(message.divineFury);
        /* bool holy_nova = 24; */
        if (message.holyNova !== false)
            writer.tag(24, WireType.Varint).bool(message.holyNova);
        /* int32 blessed_recovery = 25; */
        if (message.blessedRecovery !== 0)
            writer.tag(25, WireType.Varint).int32(message.blessedRecovery);
        /* int32 inspiration = 26; */
        if (message.inspiration !== 0)
            writer.tag(26, WireType.Varint).int32(message.inspiration);
        /* int32 holy_reach = 27; */
        if (message.holyReach !== 0)
            writer.tag(27, WireType.Varint).int32(message.holyReach);
        /* int32 improved_healing = 28; */
        if (message.improvedHealing !== 0)
            writer.tag(28, WireType.Varint).int32(message.improvedHealing);
        /* int32 searing_light = 29; */
        if (message.searingLight !== 0)
            writer.tag(29, WireType.Varint).int32(message.searingLight);
        /* bool binding_heal = 30; */
        if (message.bindingHeal !== false)
            writer.tag(30, WireType.Varint).bool(message.bindingHeal);
        /* int32 litany_of_light = 31; */
        if (message.litanyOfLight !== 0)
            writer.tag(31, WireType.Varint).int32(message.litanyOfLight);
        /* bool spirit_of_redemption = 32; */
        if (message.spiritOfRedemption !== false)
            writer.tag(32, WireType.Varint).bool(message.spiritOfRedemption);
        /* int32 spiritual_guidance = 33; */
        if (message.spiritualGuidance !== 0)
            writer.tag(33, WireType.Varint).int32(message.spiritualGuidance);
        /* int32 spiritual_healing = 34; */
        if (message.spiritualHealing !== 0)
            writer.tag(34, WireType.Varint).int32(message.spiritualHealing);
        /* bool prayer_of_mending = 35; */
        if (message.prayerOfMending !== false)
            writer.tag(35, WireType.Varint).bool(message.prayerOfMending);
        /* int32 shadow_focus = 36; */
        if (message.shadowFocus !== 0)
            writer.tag(36, WireType.Varint).int32(message.shadowFocus);
        /* int32 blackout = 37; */
        if (message.blackout !== 0)
            writer.tag(37, WireType.Varint).int32(message.blackout);
        /* int32 spirit_tap = 38; */
        if (message.spiritTap !== 0)
            writer.tag(38, WireType.Varint).int32(message.spiritTap);
        /* int32 shadow_affinity = 39; */
        if (message.shadowAffinity !== 0)
            writer.tag(39, WireType.Varint).int32(message.shadowAffinity);
        /* int32 improved_shadow_word_pain = 40; */
        if (message.improvedShadowWordPain !== 0)
            writer.tag(40, WireType.Varint).int32(message.improvedShadowWordPain);
        /* int32 shadow_reach = 41; */
        if (message.shadowReach !== 0)
            writer.tag(41, WireType.Varint).int32(message.shadowReach);
        /* int32 improved_mind_blast = 42; */
        if (message.improvedMindBlast !== 0)
            writer.tag(42, WireType.Varint).int32(message.improvedMindBlast);
        /* int32 improved_psychic_scream = 43; */
        if (message.improvedPsychicScream !== 0)
            writer.tag(43, WireType.Varint).int32(message.improvedPsychicScream);
        /* bool mind_flay = 44; */
        if (message.mindFlay !== false)
            writer.tag(44, WireType.Varint).bool(message.mindFlay);
        /* int32 improved_mind_flay = 45; */
        if (message.improvedMindFlay !== 0)
            writer.tag(45, WireType.Varint).int32(message.improvedMindFlay);
        /* int32 improved_fade = 46; */
        if (message.improvedFade !== 0)
            writer.tag(46, WireType.Varint).int32(message.improvedFade);
        /* bool vampiric_embrace = 47; */
        if (message.vampiricEmbrace !== false)
            writer.tag(47, WireType.Varint).bool(message.vampiricEmbrace);
        /* int32 shadow_weaving = 48; */
        if (message.shadowWeaving !== 0)
            writer.tag(48, WireType.Varint).int32(message.shadowWeaving);
        /* bool silence = 49; */
        if (message.silence !== false)
            writer.tag(49, WireType.Varint).bool(message.silence);
        /* int32 devouring_contagion = 50; */
        if (message.devouringContagion !== 0)
            writer.tag(50, WireType.Varint).int32(message.devouringContagion);
        /* int32 early_demise = 51; */
        if (message.earlyDemise !== 0)
            writer.tag(51, WireType.Varint).int32(message.earlyDemise);
        /* int32 darkness = 52; */
        if (message.darkness !== 0)
            writer.tag(52, WireType.Varint).int32(message.darkness);
        /* bool shadowform = 53; */
        if (message.shadowform !== false)
            writer.tag(53, WireType.Varint).bool(message.shadowform);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.PriestTalents
 */
export const PriestTalents = new PriestTalents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ShadowPriest$Type extends MessageType<ShadowPriest> {
    constructor() {
        super("proto.ShadowPriest", [
            { no: 3, name: "options", kind: "message", T: () => ShadowPriest_Options }
        ]);
    }
    create(value?: PartialMessage<ShadowPriest>): ShadowPriest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ShadowPriest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ShadowPriest): ShadowPriest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.ShadowPriest.Options options */ 3:
                    message.options = ShadowPriest_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ShadowPriest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.ShadowPriest.Options options = 3; */
        if (message.options)
            ShadowPriest_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ShadowPriest
 */
export const ShadowPriest = new ShadowPriest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ShadowPriest_Rotation$Type extends MessageType<ShadowPriest_Rotation> {
    constructor() {
        super("proto.ShadowPriest.Rotation", []);
    }
    create(value?: PartialMessage<ShadowPriest_Rotation>): ShadowPriest_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ShadowPriest_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ShadowPriest_Rotation): ShadowPriest_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ShadowPriest_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ShadowPriest.Rotation
 */
export const ShadowPriest_Rotation = new ShadowPriest_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ShadowPriest_Options$Type extends MessageType<ShadowPriest_Options> {
    constructor() {
        super("proto.ShadowPriest.Options", [
            { no: 1, name: "use_shadowfiend", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "armor", kind: "enum", T: () => ["proto.ShadowPriest.Options.Armor", ShadowPriest_Options_Armor] },
            { no: 4, name: "use_mind_blast", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "power_infusion_target", kind: "message", T: () => UnitReference },
            { no: 6, name: "latency", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ShadowPriest_Options>): ShadowPriest_Options {
        const message = { useShadowfiend: false, armor: 0, useMindBlast: false, latency: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ShadowPriest_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ShadowPriest_Options): ShadowPriest_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool use_shadowfiend */ 1:
                    message.useShadowfiend = reader.bool();
                    break;
                case /* proto.ShadowPriest.Options.Armor armor */ 2:
                    message.armor = reader.int32();
                    break;
                case /* bool use_mind_blast */ 4:
                    message.useMindBlast = reader.bool();
                    break;
                case /* proto.UnitReference power_infusion_target */ 5:
                    message.powerInfusionTarget = UnitReference.internalBinaryRead(reader, reader.uint32(), options, message.powerInfusionTarget);
                    break;
                case /* double latency = 6 [deprecated = true];*/ 6:
                    message.latency = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ShadowPriest_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool use_shadowfiend = 1; */
        if (message.useShadowfiend !== false)
            writer.tag(1, WireType.Varint).bool(message.useShadowfiend);
        /* proto.ShadowPriest.Options.Armor armor = 2; */
        if (message.armor !== 0)
            writer.tag(2, WireType.Varint).int32(message.armor);
        /* bool use_mind_blast = 4; */
        if (message.useMindBlast !== false)
            writer.tag(4, WireType.Varint).bool(message.useMindBlast);
        /* proto.UnitReference power_infusion_target = 5; */
        if (message.powerInfusionTarget)
            UnitReference.internalBinaryWrite(message.powerInfusionTarget, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* double latency = 6 [deprecated = true]; */
        if (message.latency !== 0)
            writer.tag(6, WireType.Bit64).double(message.latency);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ShadowPriest.Options
 */
export const ShadowPriest_Options = new ShadowPriest_Options$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SmitePriest$Type extends MessageType<SmitePriest> {
    constructor() {
        super("proto.SmitePriest", [
            { no: 3, name: "options", kind: "message", T: () => SmitePriest_Options }
        ]);
    }
    create(value?: PartialMessage<SmitePriest>): SmitePriest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SmitePriest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SmitePriest): SmitePriest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.SmitePriest.Options options */ 3:
                    message.options = SmitePriest_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SmitePriest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.SmitePriest.Options options = 3; */
        if (message.options)
            SmitePriest_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.SmitePriest
 */
export const SmitePriest = new SmitePriest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SmitePriest_Rotation$Type extends MessageType<SmitePriest_Rotation> {
    constructor() {
        super("proto.SmitePriest.Rotation", []);
    }
    create(value?: PartialMessage<SmitePriest_Rotation>): SmitePriest_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SmitePriest_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SmitePriest_Rotation): SmitePriest_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: SmitePriest_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.SmitePriest.Rotation
 */
export const SmitePriest_Rotation = new SmitePriest_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SmitePriest_Options$Type extends MessageType<SmitePriest_Options> {
    constructor() {
        super("proto.SmitePriest.Options", [
            { no: 1, name: "armor", kind: "enum", T: () => ["proto.SmitePriest.Options.Armor", SmitePriest_Options_Armor] },
            { no: 2, name: "power_infusion_target", kind: "message", T: () => UnitReference }
        ]);
    }
    create(value?: PartialMessage<SmitePriest_Options>): SmitePriest_Options {
        const message = { armor: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SmitePriest_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SmitePriest_Options): SmitePriest_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.SmitePriest.Options.Armor armor */ 1:
                    message.armor = reader.int32();
                    break;
                case /* proto.UnitReference power_infusion_target */ 2:
                    message.powerInfusionTarget = UnitReference.internalBinaryRead(reader, reader.uint32(), options, message.powerInfusionTarget);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SmitePriest_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.SmitePriest.Options.Armor armor = 1; */
        if (message.armor !== 0)
            writer.tag(1, WireType.Varint).int32(message.armor);
        /* proto.UnitReference power_infusion_target = 2; */
        if (message.powerInfusionTarget)
            UnitReference.internalBinaryWrite(message.powerInfusionTarget, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.SmitePriest.Options
 */
export const SmitePriest_Options = new SmitePriest_Options$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealingPriest$Type extends MessageType<HealingPriest> {
    constructor() {
        super("proto.HealingPriest", [
            { no: 3, name: "options", kind: "message", T: () => HealingPriest_Options }
        ]);
    }
    create(value?: PartialMessage<HealingPriest>): HealingPriest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HealingPriest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealingPriest): HealingPriest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.HealingPriest.Options options */ 3:
                    message.options = HealingPriest_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealingPriest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.HealingPriest.Options options = 3; */
        if (message.options)
            HealingPriest_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.HealingPriest
 */
export const HealingPriest = new HealingPriest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealingPriest_Rotation$Type extends MessageType<HealingPriest_Rotation> {
    constructor() {
        super("proto.HealingPriest.Rotation", []);
    }
    create(value?: PartialMessage<HealingPriest_Rotation>): HealingPriest_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HealingPriest_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealingPriest_Rotation): HealingPriest_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: HealingPriest_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.HealingPriest.Rotation
 */
export const HealingPriest_Rotation = new HealingPriest_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealingPriest_Options$Type extends MessageType<HealingPriest_Options> {
    constructor() {
        super("proto.HealingPriest.Options", [
            { no: 2, name: "use_inner_fire", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 1, name: "power_infusion_target", kind: "message", T: () => UnitReference }
        ]);
    }
    create(value?: PartialMessage<HealingPriest_Options>): HealingPriest_Options {
        const message = { useInnerFire: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<HealingPriest_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealingPriest_Options): HealingPriest_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool use_inner_fire */ 2:
                    message.useInnerFire = reader.bool();
                    break;
                case /* proto.UnitReference power_infusion_target */ 1:
                    message.powerInfusionTarget = UnitReference.internalBinaryRead(reader, reader.uint32(), options, message.powerInfusionTarget);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealingPriest_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool use_inner_fire = 2; */
        if (message.useInnerFire !== false)
            writer.tag(2, WireType.Varint).bool(message.useInnerFire);
        /* proto.UnitReference power_infusion_target = 1; */
        if (message.powerInfusionTarget)
            UnitReference.internalBinaryWrite(message.powerInfusionTarget, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.HealingPriest.Options
 */
export const HealingPriest_Options = new HealingPriest_Options$Type();
