// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "rogue.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * DO NOT REMOVE THE COMMENTS
 * BEGIN GENERATED
 * RogueTalents message.
 *
 * @generated from protobuf message proto.RogueTalents
 */
export interface RogueTalents {
    /**
     * Assassination
     *
     * @generated from protobuf field: int32 improved_gouge = 1;
     */
    improvedGouge: number;
    /**
     * @generated from protobuf field: int32 remorseless_attacks = 2;
     */
    remorselessAttacks: number;
    /**
     * @generated from protobuf field: int32 malice = 3;
     */
    malice: number;
    /**
     * @generated from protobuf field: int32 ruthlessness = 4;
     */
    ruthlessness: number;
    /**
     * @generated from protobuf field: int32 murder = 5;
     */
    murder: number;
    /**
     * @generated from protobuf field: int32 improved_slice_and_dice = 6;
     */
    improvedSliceAndDice: number;
    /**
     * @generated from protobuf field: bool relentless_strikes = 7;
     */
    relentlessStrikes: boolean;
    /**
     * @generated from protobuf field: int32 improved_expose_armor = 8;
     */
    improvedExposeArmor: number;
    /**
     * @generated from protobuf field: int32 lethality = 9;
     */
    lethality: number;
    /**
     * @generated from protobuf field: int32 vile_poisons = 10;
     */
    vilePoisons: number;
    /**
     * @generated from protobuf field: bool cold_blood = 11;
     */
    coldBlood: boolean;
    /**
     * @generated from protobuf field: int32 improved_poisons = 12;
     */
    improvedPoisons: number;
    /**
     * @generated from protobuf field: int32 vigor = 13;
     */
    vigor: number;
    /**
     * @generated from protobuf field: bool mutilate = 14;
     */
    mutilate: boolean;
    /**
     * @generated from protobuf field: int32 improved_kidney_shot = 15;
     */
    improvedKidneyShot: number;
    /**
     * @generated from protobuf field: int32 seal_fate = 16;
     */
    sealFate: number;
    /**
     * @generated from protobuf field: bool venom = 17;
     */
    venom: boolean;
    /**
     * Combat
     *
     * @generated from protobuf field: int32 improved_eviscerate = 18;
     */
    improvedEviscerate: number;
    /**
     * @generated from protobuf field: int32 improved_sinister_strike = 19;
     */
    improvedSinisterStrike: number;
    /**
     * @generated from protobuf field: int32 lightning_reflexes = 20;
     */
    lightningReflexes: number;
    /**
     * @generated from protobuf field: int32 puncturing_wounds = 21;
     */
    puncturingWounds: number;
    /**
     * @generated from protobuf field: int32 deflection = 22;
     */
    deflection: number;
    /**
     * @generated from protobuf field: int32 precision = 23;
     */
    precision: number;
    /**
     * @generated from protobuf field: int32 endurance = 24;
     */
    endurance: number;
    /**
     * @generated from protobuf field: bool riposte = 25;
     */
    riposte: boolean;
    /**
     * @generated from protobuf field: int32 improved_sprint = 26;
     */
    improvedSprint: number;
    /**
     * @generated from protobuf field: int32 improved_kick = 27;
     */
    improvedKick: number;
    /**
     * @generated from protobuf field: bool flawless_execution = 28;
     */
    flawlessExecution: boolean;
    /**
     * @generated from protobuf field: int32 dual_wield_specialization = 29;
     */
    dualWieldSpecialization: number;
    /**
     * @generated from protobuf field: bool blade_flurry = 30;
     */
    bladeFlurry: boolean;
    /**
     * @generated from protobuf field: int32 hack_and_slash = 31;
     */
    hackAndSlash: number;
    /**
     * @generated from protobuf field: int32 weapon_expertise = 32;
     */
    weaponExpertise: number;
    /**
     * @generated from protobuf field: int32 aggression = 33;
     */
    aggression: number;
    /**
     * @generated from protobuf field: bool adrenaline_rush = 34;
     */
    adrenalineRush: boolean;
    /**
     * Subtlety
     *
     * @generated from protobuf field: int32 camouflage = 35;
     */
    camouflage: number;
    /**
     * @generated from protobuf field: int32 master_of_deception = 36;
     */
    masterOfDeception: number;
    /**
     * @generated from protobuf field: int32 opportunity = 37;
     */
    opportunity: number;
    /**
     * @generated from protobuf field: int32 setup = 38;
     */
    setup: number;
    /**
     * @generated from protobuf field: int32 elusiveness = 39;
     */
    elusiveness: number;
    /**
     * @generated from protobuf field: int32 dirty_tricks = 40;
     */
    dirtyTricks: number;
    /**
     * @generated from protobuf field: int32 improved_ambush = 41;
     */
    improvedAmbush: number;
    /**
     * @generated from protobuf field: int32 initiative = 42;
     */
    initiative: number;
    /**
     * @generated from protobuf field: bool ghostly_strike = 43;
     */
    ghostlyStrike: boolean;
    /**
     * @generated from protobuf field: int32 improved_distract = 44;
     */
    improvedDistract: number;
    /**
     * @generated from protobuf field: int32 heightened_senses = 45;
     */
    heightenedSenses: number;
    /**
     * @generated from protobuf field: bool premeditation = 46;
     */
    premeditation: boolean;
    /**
     * @generated from protobuf field: int32 serrated_blades = 47;
     */
    serratedBlades: number;
    /**
     * @generated from protobuf field: int32 dirty_deeds = 48;
     */
    dirtyDeeds: number;
    /**
     * @generated from protobuf field: bool preparation = 49;
     */
    preparation: boolean;
    /**
     * @generated from protobuf field: bool hemorrhage = 50;
     */
    hemorrhage: boolean;
    /**
     * @generated from protobuf field: int32 quietus = 51;
     */
    quietus: number;
    /**
     * @generated from protobuf field: int32 cutthroat = 52;
     */
    cutthroat: number;
    /**
     * @generated from protobuf field: bool thousand_cuts = 53;
     */
    thousandCuts: boolean;
}
// END GENERATED

/**
 * @generated from protobuf message proto.RogueOptions
 */
export interface RogueOptions {
}
/**
 * @generated from protobuf message proto.Rogue
 */
export interface Rogue {
    /**
     * @generated from protobuf field: proto.RogueOptions options = 2;
     */
    options?: RogueOptions;
}
/**
 * @generated from protobuf message proto.Rogue.Rotation
 */
export interface Rogue_Rotation {
}
/**
 * @generated from protobuf message proto.TankRogue
 */
export interface TankRogue {
    /**
     * @generated from protobuf field: proto.RogueOptions options = 2;
     */
    options?: RogueOptions;
}
/**
 * @generated from protobuf message proto.TankRogue.Rotation
 */
export interface TankRogue_Rotation {
}
// @generated message type with reflection information, may provide speed optimized methods
class RogueTalents$Type extends MessageType<RogueTalents> {
    constructor() {
        super("proto.RogueTalents", [
            { no: 1, name: "improved_gouge", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "remorseless_attacks", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "malice", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "ruthlessness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "murder", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "improved_slice_and_dice", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "relentless_strikes", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "improved_expose_armor", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "lethality", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "vile_poisons", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "cold_blood", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "improved_poisons", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "vigor", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "mutilate", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "improved_kidney_shot", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "seal_fate", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "venom", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "improved_eviscerate", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "improved_sinister_strike", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "lightning_reflexes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "puncturing_wounds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "deflection", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 23, name: "precision", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 24, name: "endurance", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 25, name: "riposte", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 26, name: "improved_sprint", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "improved_kick", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 28, name: "flawless_execution", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 29, name: "dual_wield_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 30, name: "blade_flurry", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 31, name: "hack_and_slash", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 32, name: "weapon_expertise", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 33, name: "aggression", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 34, name: "adrenaline_rush", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 35, name: "camouflage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 36, name: "master_of_deception", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 37, name: "opportunity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 38, name: "setup", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 39, name: "elusiveness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 40, name: "dirty_tricks", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 41, name: "improved_ambush", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 42, name: "initiative", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 43, name: "ghostly_strike", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 44, name: "improved_distract", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 45, name: "heightened_senses", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 46, name: "premeditation", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 47, name: "serrated_blades", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 48, name: "dirty_deeds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 49, name: "preparation", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 50, name: "hemorrhage", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 51, name: "quietus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 52, name: "cutthroat", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 53, name: "thousand_cuts", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<RogueTalents>): RogueTalents {
        const message = { improvedGouge: 0, remorselessAttacks: 0, malice: 0, ruthlessness: 0, murder: 0, improvedSliceAndDice: 0, relentlessStrikes: false, improvedExposeArmor: 0, lethality: 0, vilePoisons: 0, coldBlood: false, improvedPoisons: 0, vigor: 0, mutilate: false, improvedKidneyShot: 0, sealFate: 0, venom: false, improvedEviscerate: 0, improvedSinisterStrike: 0, lightningReflexes: 0, puncturingWounds: 0, deflection: 0, precision: 0, endurance: 0, riposte: false, improvedSprint: 0, improvedKick: 0, flawlessExecution: false, dualWieldSpecialization: 0, bladeFlurry: false, hackAndSlash: 0, weaponExpertise: 0, aggression: 0, adrenalineRush: false, camouflage: 0, masterOfDeception: 0, opportunity: 0, setup: 0, elusiveness: 0, dirtyTricks: 0, improvedAmbush: 0, initiative: 0, ghostlyStrike: false, improvedDistract: 0, heightenedSenses: 0, premeditation: false, serratedBlades: 0, dirtyDeeds: 0, preparation: false, hemorrhage: false, quietus: 0, cutthroat: 0, thousandCuts: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RogueTalents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RogueTalents): RogueTalents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 improved_gouge */ 1:
                    message.improvedGouge = reader.int32();
                    break;
                case /* int32 remorseless_attacks */ 2:
                    message.remorselessAttacks = reader.int32();
                    break;
                case /* int32 malice */ 3:
                    message.malice = reader.int32();
                    break;
                case /* int32 ruthlessness */ 4:
                    message.ruthlessness = reader.int32();
                    break;
                case /* int32 murder */ 5:
                    message.murder = reader.int32();
                    break;
                case /* int32 improved_slice_and_dice */ 6:
                    message.improvedSliceAndDice = reader.int32();
                    break;
                case /* bool relentless_strikes */ 7:
                    message.relentlessStrikes = reader.bool();
                    break;
                case /* int32 improved_expose_armor */ 8:
                    message.improvedExposeArmor = reader.int32();
                    break;
                case /* int32 lethality */ 9:
                    message.lethality = reader.int32();
                    break;
                case /* int32 vile_poisons */ 10:
                    message.vilePoisons = reader.int32();
                    break;
                case /* bool cold_blood */ 11:
                    message.coldBlood = reader.bool();
                    break;
                case /* int32 improved_poisons */ 12:
                    message.improvedPoisons = reader.int32();
                    break;
                case /* int32 vigor */ 13:
                    message.vigor = reader.int32();
                    break;
                case /* bool mutilate */ 14:
                    message.mutilate = reader.bool();
                    break;
                case /* int32 improved_kidney_shot */ 15:
                    message.improvedKidneyShot = reader.int32();
                    break;
                case /* int32 seal_fate */ 16:
                    message.sealFate = reader.int32();
                    break;
                case /* bool venom */ 17:
                    message.venom = reader.bool();
                    break;
                case /* int32 improved_eviscerate */ 18:
                    message.improvedEviscerate = reader.int32();
                    break;
                case /* int32 improved_sinister_strike */ 19:
                    message.improvedSinisterStrike = reader.int32();
                    break;
                case /* int32 lightning_reflexes */ 20:
                    message.lightningReflexes = reader.int32();
                    break;
                case /* int32 puncturing_wounds */ 21:
                    message.puncturingWounds = reader.int32();
                    break;
                case /* int32 deflection */ 22:
                    message.deflection = reader.int32();
                    break;
                case /* int32 precision */ 23:
                    message.precision = reader.int32();
                    break;
                case /* int32 endurance */ 24:
                    message.endurance = reader.int32();
                    break;
                case /* bool riposte */ 25:
                    message.riposte = reader.bool();
                    break;
                case /* int32 improved_sprint */ 26:
                    message.improvedSprint = reader.int32();
                    break;
                case /* int32 improved_kick */ 27:
                    message.improvedKick = reader.int32();
                    break;
                case /* bool flawless_execution */ 28:
                    message.flawlessExecution = reader.bool();
                    break;
                case /* int32 dual_wield_specialization */ 29:
                    message.dualWieldSpecialization = reader.int32();
                    break;
                case /* bool blade_flurry */ 30:
                    message.bladeFlurry = reader.bool();
                    break;
                case /* int32 hack_and_slash */ 31:
                    message.hackAndSlash = reader.int32();
                    break;
                case /* int32 weapon_expertise */ 32:
                    message.weaponExpertise = reader.int32();
                    break;
                case /* int32 aggression */ 33:
                    message.aggression = reader.int32();
                    break;
                case /* bool adrenaline_rush */ 34:
                    message.adrenalineRush = reader.bool();
                    break;
                case /* int32 camouflage */ 35:
                    message.camouflage = reader.int32();
                    break;
                case /* int32 master_of_deception */ 36:
                    message.masterOfDeception = reader.int32();
                    break;
                case /* int32 opportunity */ 37:
                    message.opportunity = reader.int32();
                    break;
                case /* int32 setup */ 38:
                    message.setup = reader.int32();
                    break;
                case /* int32 elusiveness */ 39:
                    message.elusiveness = reader.int32();
                    break;
                case /* int32 dirty_tricks */ 40:
                    message.dirtyTricks = reader.int32();
                    break;
                case /* int32 improved_ambush */ 41:
                    message.improvedAmbush = reader.int32();
                    break;
                case /* int32 initiative */ 42:
                    message.initiative = reader.int32();
                    break;
                case /* bool ghostly_strike */ 43:
                    message.ghostlyStrike = reader.bool();
                    break;
                case /* int32 improved_distract */ 44:
                    message.improvedDistract = reader.int32();
                    break;
                case /* int32 heightened_senses */ 45:
                    message.heightenedSenses = reader.int32();
                    break;
                case /* bool premeditation */ 46:
                    message.premeditation = reader.bool();
                    break;
                case /* int32 serrated_blades */ 47:
                    message.serratedBlades = reader.int32();
                    break;
                case /* int32 dirty_deeds */ 48:
                    message.dirtyDeeds = reader.int32();
                    break;
                case /* bool preparation */ 49:
                    message.preparation = reader.bool();
                    break;
                case /* bool hemorrhage */ 50:
                    message.hemorrhage = reader.bool();
                    break;
                case /* int32 quietus */ 51:
                    message.quietus = reader.int32();
                    break;
                case /* int32 cutthroat */ 52:
                    message.cutthroat = reader.int32();
                    break;
                case /* bool thousand_cuts */ 53:
                    message.thousandCuts = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RogueTalents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 improved_gouge = 1; */
        if (message.improvedGouge !== 0)
            writer.tag(1, WireType.Varint).int32(message.improvedGouge);
        /* int32 remorseless_attacks = 2; */
        if (message.remorselessAttacks !== 0)
            writer.tag(2, WireType.Varint).int32(message.remorselessAttacks);
        /* int32 malice = 3; */
        if (message.malice !== 0)
            writer.tag(3, WireType.Varint).int32(message.malice);
        /* int32 ruthlessness = 4; */
        if (message.ruthlessness !== 0)
            writer.tag(4, WireType.Varint).int32(message.ruthlessness);
        /* int32 murder = 5; */
        if (message.murder !== 0)
            writer.tag(5, WireType.Varint).int32(message.murder);
        /* int32 improved_slice_and_dice = 6; */
        if (message.improvedSliceAndDice !== 0)
            writer.tag(6, WireType.Varint).int32(message.improvedSliceAndDice);
        /* bool relentless_strikes = 7; */
        if (message.relentlessStrikes !== false)
            writer.tag(7, WireType.Varint).bool(message.relentlessStrikes);
        /* int32 improved_expose_armor = 8; */
        if (message.improvedExposeArmor !== 0)
            writer.tag(8, WireType.Varint).int32(message.improvedExposeArmor);
        /* int32 lethality = 9; */
        if (message.lethality !== 0)
            writer.tag(9, WireType.Varint).int32(message.lethality);
        /* int32 vile_poisons = 10; */
        if (message.vilePoisons !== 0)
            writer.tag(10, WireType.Varint).int32(message.vilePoisons);
        /* bool cold_blood = 11; */
        if (message.coldBlood !== false)
            writer.tag(11, WireType.Varint).bool(message.coldBlood);
        /* int32 improved_poisons = 12; */
        if (message.improvedPoisons !== 0)
            writer.tag(12, WireType.Varint).int32(message.improvedPoisons);
        /* int32 vigor = 13; */
        if (message.vigor !== 0)
            writer.tag(13, WireType.Varint).int32(message.vigor);
        /* bool mutilate = 14; */
        if (message.mutilate !== false)
            writer.tag(14, WireType.Varint).bool(message.mutilate);
        /* int32 improved_kidney_shot = 15; */
        if (message.improvedKidneyShot !== 0)
            writer.tag(15, WireType.Varint).int32(message.improvedKidneyShot);
        /* int32 seal_fate = 16; */
        if (message.sealFate !== 0)
            writer.tag(16, WireType.Varint).int32(message.sealFate);
        /* bool venom = 17; */
        if (message.venom !== false)
            writer.tag(17, WireType.Varint).bool(message.venom);
        /* int32 improved_eviscerate = 18; */
        if (message.improvedEviscerate !== 0)
            writer.tag(18, WireType.Varint).int32(message.improvedEviscerate);
        /* int32 improved_sinister_strike = 19; */
        if (message.improvedSinisterStrike !== 0)
            writer.tag(19, WireType.Varint).int32(message.improvedSinisterStrike);
        /* int32 lightning_reflexes = 20; */
        if (message.lightningReflexes !== 0)
            writer.tag(20, WireType.Varint).int32(message.lightningReflexes);
        /* int32 puncturing_wounds = 21; */
        if (message.puncturingWounds !== 0)
            writer.tag(21, WireType.Varint).int32(message.puncturingWounds);
        /* int32 deflection = 22; */
        if (message.deflection !== 0)
            writer.tag(22, WireType.Varint).int32(message.deflection);
        /* int32 precision = 23; */
        if (message.precision !== 0)
            writer.tag(23, WireType.Varint).int32(message.precision);
        /* int32 endurance = 24; */
        if (message.endurance !== 0)
            writer.tag(24, WireType.Varint).int32(message.endurance);
        /* bool riposte = 25; */
        if (message.riposte !== false)
            writer.tag(25, WireType.Varint).bool(message.riposte);
        /* int32 improved_sprint = 26; */
        if (message.improvedSprint !== 0)
            writer.tag(26, WireType.Varint).int32(message.improvedSprint);
        /* int32 improved_kick = 27; */
        if (message.improvedKick !== 0)
            writer.tag(27, WireType.Varint).int32(message.improvedKick);
        /* bool flawless_execution = 28; */
        if (message.flawlessExecution !== false)
            writer.tag(28, WireType.Varint).bool(message.flawlessExecution);
        /* int32 dual_wield_specialization = 29; */
        if (message.dualWieldSpecialization !== 0)
            writer.tag(29, WireType.Varint).int32(message.dualWieldSpecialization);
        /* bool blade_flurry = 30; */
        if (message.bladeFlurry !== false)
            writer.tag(30, WireType.Varint).bool(message.bladeFlurry);
        /* int32 hack_and_slash = 31; */
        if (message.hackAndSlash !== 0)
            writer.tag(31, WireType.Varint).int32(message.hackAndSlash);
        /* int32 weapon_expertise = 32; */
        if (message.weaponExpertise !== 0)
            writer.tag(32, WireType.Varint).int32(message.weaponExpertise);
        /* int32 aggression = 33; */
        if (message.aggression !== 0)
            writer.tag(33, WireType.Varint).int32(message.aggression);
        /* bool adrenaline_rush = 34; */
        if (message.adrenalineRush !== false)
            writer.tag(34, WireType.Varint).bool(message.adrenalineRush);
        /* int32 camouflage = 35; */
        if (message.camouflage !== 0)
            writer.tag(35, WireType.Varint).int32(message.camouflage);
        /* int32 master_of_deception = 36; */
        if (message.masterOfDeception !== 0)
            writer.tag(36, WireType.Varint).int32(message.masterOfDeception);
        /* int32 opportunity = 37; */
        if (message.opportunity !== 0)
            writer.tag(37, WireType.Varint).int32(message.opportunity);
        /* int32 setup = 38; */
        if (message.setup !== 0)
            writer.tag(38, WireType.Varint).int32(message.setup);
        /* int32 elusiveness = 39; */
        if (message.elusiveness !== 0)
            writer.tag(39, WireType.Varint).int32(message.elusiveness);
        /* int32 dirty_tricks = 40; */
        if (message.dirtyTricks !== 0)
            writer.tag(40, WireType.Varint).int32(message.dirtyTricks);
        /* int32 improved_ambush = 41; */
        if (message.improvedAmbush !== 0)
            writer.tag(41, WireType.Varint).int32(message.improvedAmbush);
        /* int32 initiative = 42; */
        if (message.initiative !== 0)
            writer.tag(42, WireType.Varint).int32(message.initiative);
        /* bool ghostly_strike = 43; */
        if (message.ghostlyStrike !== false)
            writer.tag(43, WireType.Varint).bool(message.ghostlyStrike);
        /* int32 improved_distract = 44; */
        if (message.improvedDistract !== 0)
            writer.tag(44, WireType.Varint).int32(message.improvedDistract);
        /* int32 heightened_senses = 45; */
        if (message.heightenedSenses !== 0)
            writer.tag(45, WireType.Varint).int32(message.heightenedSenses);
        /* bool premeditation = 46; */
        if (message.premeditation !== false)
            writer.tag(46, WireType.Varint).bool(message.premeditation);
        /* int32 serrated_blades = 47; */
        if (message.serratedBlades !== 0)
            writer.tag(47, WireType.Varint).int32(message.serratedBlades);
        /* int32 dirty_deeds = 48; */
        if (message.dirtyDeeds !== 0)
            writer.tag(48, WireType.Varint).int32(message.dirtyDeeds);
        /* bool preparation = 49; */
        if (message.preparation !== false)
            writer.tag(49, WireType.Varint).bool(message.preparation);
        /* bool hemorrhage = 50; */
        if (message.hemorrhage !== false)
            writer.tag(50, WireType.Varint).bool(message.hemorrhage);
        /* int32 quietus = 51; */
        if (message.quietus !== 0)
            writer.tag(51, WireType.Varint).int32(message.quietus);
        /* int32 cutthroat = 52; */
        if (message.cutthroat !== 0)
            writer.tag(52, WireType.Varint).int32(message.cutthroat);
        /* bool thousand_cuts = 53; */
        if (message.thousandCuts !== false)
            writer.tag(53, WireType.Varint).bool(message.thousandCuts);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RogueTalents
 */
export const RogueTalents = new RogueTalents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RogueOptions$Type extends MessageType<RogueOptions> {
    constructor() {
        super("proto.RogueOptions", []);
    }
    create(value?: PartialMessage<RogueOptions>): RogueOptions {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RogueOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RogueOptions): RogueOptions {
        return target ?? this.create();
    }
    internalBinaryWrite(message: RogueOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RogueOptions
 */
export const RogueOptions = new RogueOptions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rogue$Type extends MessageType<Rogue> {
    constructor() {
        super("proto.Rogue", [
            { no: 2, name: "options", kind: "message", T: () => RogueOptions }
        ]);
    }
    create(value?: PartialMessage<Rogue>): Rogue {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Rogue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rogue): Rogue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.RogueOptions options */ 2:
                    message.options = RogueOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Rogue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.RogueOptions options = 2; */
        if (message.options)
            RogueOptions.internalBinaryWrite(message.options, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.Rogue
 */
export const Rogue = new Rogue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rogue_Rotation$Type extends MessageType<Rogue_Rotation> {
    constructor() {
        super("proto.Rogue.Rotation", []);
    }
    create(value?: PartialMessage<Rogue_Rotation>): Rogue_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Rogue_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rogue_Rotation): Rogue_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: Rogue_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.Rogue.Rotation
 */
export const Rogue_Rotation = new Rogue_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TankRogue$Type extends MessageType<TankRogue> {
    constructor() {
        super("proto.TankRogue", [
            { no: 2, name: "options", kind: "message", T: () => RogueOptions }
        ]);
    }
    create(value?: PartialMessage<TankRogue>): TankRogue {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TankRogue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TankRogue): TankRogue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.RogueOptions options */ 2:
                    message.options = RogueOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TankRogue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.RogueOptions options = 2; */
        if (message.options)
            RogueOptions.internalBinaryWrite(message.options, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.TankRogue
 */
export const TankRogue = new TankRogue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TankRogue_Rotation$Type extends MessageType<TankRogue_Rotation> {
    constructor() {
        super("proto.TankRogue.Rotation", []);
    }
    create(value?: PartialMessage<TankRogue_Rotation>): TankRogue_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TankRogue_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TankRogue_Rotation): TankRogue_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: TankRogue_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.TankRogue.Rotation
 */
export const TankRogue_Rotation = new TankRogue_Rotation$Type();
