// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "shaman.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * DO NOT REMOVE THE COMMENTS
 * BEGIN GENERATED
 * ShamanTalents message.
 *
 * @generated from protobuf message proto.ShamanTalents
 */
export interface ShamanTalents {
    /**
     * Elemental
     *
     * @generated from protobuf field: int32 convection = 1;
     */
    convection: number;
    /**
     * @generated from protobuf field: int32 concussion = 2;
     */
    concussion: number;
    /**
     * @generated from protobuf field: int32 elemental_warding = 3;
     */
    elementalWarding: number;
    /**
     * @generated from protobuf field: int32 reverberation = 4;
     */
    reverberation: number;
    /**
     * @generated from protobuf field: int32 call_of_flame = 5;
     */
    callOfFlame: number;
    /**
     * @generated from protobuf field: int32 elemental_devastation = 6;
     */
    elementalDevastation: number;
    /**
     * @generated from protobuf field: bool elemental_focus = 7;
     */
    elementalFocus: boolean;
    /**
     * @generated from protobuf field: int32 elemental_fury = 8;
     */
    elementalFury: number;
    /**
     * @generated from protobuf field: int32 improved_fire_nova = 9;
     */
    improvedFireNova: number;
    /**
     * @generated from protobuf field: int32 eye_of_the_storm = 10;
     */
    eyeOfTheStorm: number;
    /**
     * @generated from protobuf field: bool call_of_thunder = 11;
     */
    callOfThunder: boolean;
    /**
     * @generated from protobuf field: int32 elemental_reach = 12;
     */
    elementalReach: number;
    /**
     * @generated from protobuf field: int32 lightning_overload = 13;
     */
    lightningOverload: number;
    /**
     * @generated from protobuf field: bool earthbound = 14;
     */
    earthbound: boolean;
    /**
     * @generated from protobuf field: int32 elemental_alacrity = 15;
     */
    elementalAlacrity: number;
    /**
     * @generated from protobuf field: bool lava_burst = 16;
     */
    lavaBurst: boolean;
    /**
     * Enhancement
     *
     * @generated from protobuf field: int32 earths_grasp = 17;
     */
    earthsGrasp: number;
    /**
     * @generated from protobuf field: int32 thundering_strikes = 18;
     */
    thunderingStrikes: number;
    /**
     * @generated from protobuf field: int32 ancestral_knowledge = 19;
     */
    ancestralKnowledge: number;
    /**
     * @generated from protobuf field: int32 guardian_totems = 20;
     */
    guardianTotems: number;
    /**
     * @generated from protobuf field: int32 mental_dexterity = 21;
     */
    mentalDexterity: number;
    /**
     * @generated from protobuf field: int32 improved_ghost_wolf = 22;
     */
    improvedGhostWolf: number;
    /**
     * @generated from protobuf field: int32 improved_lightning_shield = 23;
     */
    improvedLightningShield: number;
    /**
     * @generated from protobuf field: int32 elemental_weapons = 24;
     */
    elementalWeapons: number;
    /**
     * @generated from protobuf field: bool shamanistic_focus = 25;
     */
    shamanisticFocus: boolean;
    /**
     * @generated from protobuf field: int32 anticipation = 26;
     */
    anticipation: number;
    /**
     * @generated from protobuf field: int32 toughness = 27;
     */
    toughness: number;
    /**
     * @generated from protobuf field: int32 flurry = 28;
     */
    flurry: number;
    /**
     * @generated from protobuf field: bool stormstrike = 29;
     */
    stormstrike: boolean;
    /**
     * @generated from protobuf field: bool spirit_weapons = 30;
     */
    spiritWeapons: boolean;
    /**
     * @generated from protobuf field: int32 mental_quickness = 31;
     */
    mentalQuickness: number;
    /**
     * @generated from protobuf field: int32 improved_stormstrike = 32;
     */
    improvedStormstrike: number;
    /**
     * @generated from protobuf field: int32 maelstrom_weapon = 33;
     */
    maelstromWeapon: number;
    /**
     * @generated from protobuf field: bool rage_of_the_farseer = 34;
     */
    rageOfTheFarseer: boolean;
    /**
     * Restoration
     *
     * @generated from protobuf field: int32 improved_healing_wave = 35;
     */
    improvedHealingWave: number;
    /**
     * @generated from protobuf field: int32 totemic_focus = 36;
     */
    totemicFocus: number;
    /**
     * @generated from protobuf field: int32 mindfulness = 37;
     */
    mindfulness: number;
    /**
     * @generated from protobuf field: int32 natural_grace = 38;
     */
    naturalGrace: number;
    /**
     * @generated from protobuf field: int32 tidal_focus = 39;
     */
    tidalFocus: number;
    /**
     * @generated from protobuf field: int32 improved_reincarnation = 40;
     */
    improvedReincarnation: number;
    /**
     * @generated from protobuf field: int32 ancestral_healing = 41;
     */
    ancestralHealing: number;
    /**
     * @generated from protobuf field: int32 healing_focus = 42;
     */
    healingFocus: number;
    /**
     * @generated from protobuf field: bool water_shield = 43;
     */
    waterShield: boolean;
    /**
     * @generated from protobuf field: int32 tidal_mastery = 44;
     */
    tidalMastery: number;
    /**
     * @generated from protobuf field: int32 restorative_totems = 45;
     */
    restorativeTotems: number;
    /**
     * @generated from protobuf field: bool mana_tide_totem = 46;
     */
    manaTideTotem: boolean;
    /**
     * @generated from protobuf field: int32 healing_way = 47;
     */
    healingWay: number;
    /**
     * @generated from protobuf field: bool natures_swiftness = 48;
     */
    naturesSwiftness: boolean;
    /**
     * @generated from protobuf field: int32 purification = 49;
     */
    purification: number;
    /**
     * @generated from protobuf field: bool riptide = 50;
     */
    riptide: boolean;
}
/**
 * Deprecated on 2024-02-08. Use APL totems instead
 *
 * @generated from protobuf message proto.ShamanTotems
 */
export interface ShamanTotems {
    /**
     * @generated from protobuf field: proto.EarthTotem earth = 1;
     */
    earth: EarthTotem;
    /**
     * @generated from protobuf field: proto.AirTotem air = 2;
     */
    air: AirTotem;
    /**
     * @generated from protobuf field: proto.FireTotem fire = 3;
     */
    fire: FireTotem;
    /**
     * @generated from protobuf field: proto.WaterTotem water = 4;
     */
    water: WaterTotem;
    /**
     * If set, will use mana tide when appropriate.
     *
     * @generated from protobuf field: bool use_mana_tide = 5;
     */
    useManaTide: boolean;
    /**
     * If set, any time a 2-minute totem is about to expire, will recall and
     * replace all totems.
     *
     * @generated from protobuf field: bool recall_totems = 8;
     */
    recallTotems: boolean;
    /**
     * If set will use fire totems as an MCD instead of manually controlling when to place them.
     *
     * @generated from protobuf field: bool use_fire_mcd = 9;
     */
    useFireMcd: boolean;
    /**
     * Bonus spell power for fire elemental snapshotting.
     *
     * @generated from protobuf field: int32 bonus_spellpower = 10;
     */
    bonusSpellpower: number;
    /**
     * Snapshot fire elemental using Tier 10 4 set bonus.
     *
     * @generated from protobuf field: bool enh_tier_ten_bonus = 11;
     */
    enhTierTenBonus: boolean;
}
/**
 * Not used here, but used by APL
 *
 * @generated from protobuf enum proto.ShamanTotems.TotemType
 */
export enum ShamanTotems_TotemType {
    /**
     * @generated from protobuf enum value: TypeUnknown = 0;
     */
    TypeUnknown = 0,
    /**
     * @generated from protobuf enum value: Earth = 1;
     */
    Earth = 1,
    /**
     * @generated from protobuf enum value: Air = 2;
     */
    Air = 2,
    /**
     * @generated from protobuf enum value: Fire = 3;
     */
    Fire = 3,
    /**
     * @generated from protobuf enum value: Water = 4;
     */
    Water = 4
}
/**
 * @generated from protobuf message proto.ElementalShaman
 */
export interface ElementalShaman {
    /**
     * @generated from protobuf field: proto.ElementalShaman.Options options = 3;
     */
    options?: ElementalShaman_Options;
}
/**
 * @generated from protobuf message proto.ElementalShaman.Rotation
 */
export interface ElementalShaman_Rotation {
}
/**
 * NextIndex: 6
 *
 * @generated from protobuf message proto.ElementalShaman.Options
 */
export interface ElementalShaman_Options {
}
/**
 * @generated from protobuf message proto.EnhancementShaman
 */
export interface EnhancementShaman {
    /**
     * @generated from protobuf field: proto.EnhancementShaman.Options options = 3;
     */
    options?: EnhancementShaman_Options;
}
/**
 * @generated from protobuf message proto.EnhancementShaman.Rotation
 */
export interface EnhancementShaman_Rotation {
}
/**
 * NextIndex: 7
 *
 * @generated from protobuf message proto.EnhancementShaman.Options
 */
export interface EnhancementShaman_Options {
    /**
     * @generated from protobuf field: proto.ShamanSyncType sync_type = 3;
     */
    syncType: ShamanSyncType;
}
/**
 * @generated from protobuf message proto.RestorationShaman
 */
export interface RestorationShaman {
    /**
     * @generated from protobuf field: proto.RestorationShaman.Options options = 3;
     */
    options?: RestorationShaman_Options;
}
/**
 * @generated from protobuf message proto.RestorationShaman.Rotation
 */
export interface RestorationShaman_Rotation {
}
/**
 * NextIndex: 8
 *
 * @generated from protobuf message proto.RestorationShaman.Options
 */
export interface RestorationShaman_Options {
    /**
     * @generated from protobuf field: int32 earth_shield_p_p_m = 5;
     */
    earthShieldPPM: number;
    /**
     * @deprecated
     * @generated from protobuf field: proto.ShamanTotems totems = 6 [deprecated = true];
     */
    totems?: ShamanTotems;
}
// END GENERATED

/**
 * @generated from protobuf enum proto.EarthTotem
 */
export enum EarthTotem {
    /**
     * @generated from protobuf enum value: NoEarthTotem = 0;
     */
    NoEarthTotem = 0,
    /**
     * @generated from protobuf enum value: StrengthOfEarthTotem = 1;
     */
    StrengthOfEarthTotem = 1,
    /**
     * @generated from protobuf enum value: TremorTotem = 2;
     */
    TremorTotem = 2,
    /**
     * @generated from protobuf enum value: StoneskinTotem = 3;
     */
    StoneskinTotem = 3
}
/**
 * @generated from protobuf enum proto.AirTotem
 */
export enum AirTotem {
    /**
     * @generated from protobuf enum value: NoAirTotem = 0;
     */
    NoAirTotem = 0,
    /**
     * @generated from protobuf enum value: WindfuryTotem = 1;
     */
    WindfuryTotem = 1,
    /**
     * @generated from protobuf enum value: GraceOfAirTotem = 2;
     */
    GraceOfAirTotem = 2
}
/**
 * @generated from protobuf enum proto.FireTotem
 */
export enum FireTotem {
    /**
     * @generated from protobuf enum value: NoFireTotem = 0;
     */
    NoFireTotem = 0,
    /**
     * @generated from protobuf enum value: MagmaTotem = 1;
     */
    MagmaTotem = 1,
    /**
     * @generated from protobuf enum value: SearingTotem = 2;
     */
    SearingTotem = 2,
    /**
     * @generated from protobuf enum value: FireNovaTotem = 3;
     */
    FireNovaTotem = 3
}
/**
 * @generated from protobuf enum proto.WaterTotem
 */
export enum WaterTotem {
    /**
     * @generated from protobuf enum value: NoWaterTotem = 0;
     */
    NoWaterTotem = 0,
    /**
     * @generated from protobuf enum value: ManaSpringTotem = 1;
     */
    ManaSpringTotem = 1,
    /**
     * @generated from protobuf enum value: HealingStreamTotem = 2;
     */
    HealingStreamTotem = 2
}
/**
 * @generated from protobuf enum proto.ShamanSyncType
 */
export enum ShamanSyncType {
    /**
     * @generated from protobuf enum value: NoSync = 0;
     */
    NoSync = 0,
    /**
     * @generated from protobuf enum value: SyncMainhandOffhandSwings = 1;
     */
    SyncMainhandOffhandSwings = 1,
    /**
     * @generated from protobuf enum value: DelayOffhandSwings = 2;
     */
    DelayOffhandSwings = 2,
    /**
     * @generated from protobuf enum value: Auto = 3;
     */
    Auto = 3
}
/**
 * @generated from protobuf enum proto.ShamanHealSpell
 */
export enum ShamanHealSpell {
    /**
     * @generated from protobuf enum value: AutoHeal = 0;
     */
    AutoHeal = 0,
    /**
     * @generated from protobuf enum value: HealingWave = 1;
     */
    HealingWave = 1,
    /**
     * @generated from protobuf enum value: LesserHealingWave = 2;
     */
    LesserHealingWave = 2,
    /**
     * @generated from protobuf enum value: ChainHeal = 3;
     */
    ChainHeal = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ShamanTalents$Type extends MessageType<ShamanTalents> {
    constructor() {
        super("proto.ShamanTalents", [
            { no: 1, name: "convection", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "concussion", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "elemental_warding", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "reverberation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "call_of_flame", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "elemental_devastation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "elemental_focus", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "elemental_fury", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "improved_fire_nova", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "eye_of_the_storm", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "call_of_thunder", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "elemental_reach", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "lightning_overload", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "earthbound", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "elemental_alacrity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "lava_burst", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 17, name: "earths_grasp", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 18, name: "thundering_strikes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "ancestral_knowledge", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "guardian_totems", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "mental_dexterity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "improved_ghost_wolf", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 23, name: "improved_lightning_shield", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 24, name: "elemental_weapons", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 25, name: "shamanistic_focus", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 26, name: "anticipation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "toughness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 28, name: "flurry", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 29, name: "stormstrike", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 30, name: "spirit_weapons", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 31, name: "mental_quickness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 32, name: "improved_stormstrike", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 33, name: "maelstrom_weapon", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 34, name: "rage_of_the_farseer", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 35, name: "improved_healing_wave", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 36, name: "totemic_focus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 37, name: "mindfulness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 38, name: "natural_grace", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 39, name: "tidal_focus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 40, name: "improved_reincarnation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 41, name: "ancestral_healing", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 42, name: "healing_focus", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 43, name: "water_shield", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 44, name: "tidal_mastery", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 45, name: "restorative_totems", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 46, name: "mana_tide_totem", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 47, name: "healing_way", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 48, name: "natures_swiftness", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 49, name: "purification", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 50, name: "riptide", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ShamanTalents>): ShamanTalents {
        const message = { convection: 0, concussion: 0, elementalWarding: 0, reverberation: 0, callOfFlame: 0, elementalDevastation: 0, elementalFocus: false, elementalFury: 0, improvedFireNova: 0, eyeOfTheStorm: 0, callOfThunder: false, elementalReach: 0, lightningOverload: 0, earthbound: false, elementalAlacrity: 0, lavaBurst: false, earthsGrasp: 0, thunderingStrikes: 0, ancestralKnowledge: 0, guardianTotems: 0, mentalDexterity: 0, improvedGhostWolf: 0, improvedLightningShield: 0, elementalWeapons: 0, shamanisticFocus: false, anticipation: 0, toughness: 0, flurry: 0, stormstrike: false, spiritWeapons: false, mentalQuickness: 0, improvedStormstrike: 0, maelstromWeapon: 0, rageOfTheFarseer: false, improvedHealingWave: 0, totemicFocus: 0, mindfulness: 0, naturalGrace: 0, tidalFocus: 0, improvedReincarnation: 0, ancestralHealing: 0, healingFocus: 0, waterShield: false, tidalMastery: 0, restorativeTotems: 0, manaTideTotem: false, healingWay: 0, naturesSwiftness: false, purification: 0, riptide: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ShamanTalents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ShamanTalents): ShamanTalents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 convection */ 1:
                    message.convection = reader.int32();
                    break;
                case /* int32 concussion */ 2:
                    message.concussion = reader.int32();
                    break;
                case /* int32 elemental_warding */ 3:
                    message.elementalWarding = reader.int32();
                    break;
                case /* int32 reverberation */ 4:
                    message.reverberation = reader.int32();
                    break;
                case /* int32 call_of_flame */ 5:
                    message.callOfFlame = reader.int32();
                    break;
                case /* int32 elemental_devastation */ 6:
                    message.elementalDevastation = reader.int32();
                    break;
                case /* bool elemental_focus */ 7:
                    message.elementalFocus = reader.bool();
                    break;
                case /* int32 elemental_fury */ 8:
                    message.elementalFury = reader.int32();
                    break;
                case /* int32 improved_fire_nova */ 9:
                    message.improvedFireNova = reader.int32();
                    break;
                case /* int32 eye_of_the_storm */ 10:
                    message.eyeOfTheStorm = reader.int32();
                    break;
                case /* bool call_of_thunder */ 11:
                    message.callOfThunder = reader.bool();
                    break;
                case /* int32 elemental_reach */ 12:
                    message.elementalReach = reader.int32();
                    break;
                case /* int32 lightning_overload */ 13:
                    message.lightningOverload = reader.int32();
                    break;
                case /* bool earthbound */ 14:
                    message.earthbound = reader.bool();
                    break;
                case /* int32 elemental_alacrity */ 15:
                    message.elementalAlacrity = reader.int32();
                    break;
                case /* bool lava_burst */ 16:
                    message.lavaBurst = reader.bool();
                    break;
                case /* int32 earths_grasp */ 17:
                    message.earthsGrasp = reader.int32();
                    break;
                case /* int32 thundering_strikes */ 18:
                    message.thunderingStrikes = reader.int32();
                    break;
                case /* int32 ancestral_knowledge */ 19:
                    message.ancestralKnowledge = reader.int32();
                    break;
                case /* int32 guardian_totems */ 20:
                    message.guardianTotems = reader.int32();
                    break;
                case /* int32 mental_dexterity */ 21:
                    message.mentalDexterity = reader.int32();
                    break;
                case /* int32 improved_ghost_wolf */ 22:
                    message.improvedGhostWolf = reader.int32();
                    break;
                case /* int32 improved_lightning_shield */ 23:
                    message.improvedLightningShield = reader.int32();
                    break;
                case /* int32 elemental_weapons */ 24:
                    message.elementalWeapons = reader.int32();
                    break;
                case /* bool shamanistic_focus */ 25:
                    message.shamanisticFocus = reader.bool();
                    break;
                case /* int32 anticipation */ 26:
                    message.anticipation = reader.int32();
                    break;
                case /* int32 toughness */ 27:
                    message.toughness = reader.int32();
                    break;
                case /* int32 flurry */ 28:
                    message.flurry = reader.int32();
                    break;
                case /* bool stormstrike */ 29:
                    message.stormstrike = reader.bool();
                    break;
                case /* bool spirit_weapons */ 30:
                    message.spiritWeapons = reader.bool();
                    break;
                case /* int32 mental_quickness */ 31:
                    message.mentalQuickness = reader.int32();
                    break;
                case /* int32 improved_stormstrike */ 32:
                    message.improvedStormstrike = reader.int32();
                    break;
                case /* int32 maelstrom_weapon */ 33:
                    message.maelstromWeapon = reader.int32();
                    break;
                case /* bool rage_of_the_farseer */ 34:
                    message.rageOfTheFarseer = reader.bool();
                    break;
                case /* int32 improved_healing_wave */ 35:
                    message.improvedHealingWave = reader.int32();
                    break;
                case /* int32 totemic_focus */ 36:
                    message.totemicFocus = reader.int32();
                    break;
                case /* int32 mindfulness */ 37:
                    message.mindfulness = reader.int32();
                    break;
                case /* int32 natural_grace */ 38:
                    message.naturalGrace = reader.int32();
                    break;
                case /* int32 tidal_focus */ 39:
                    message.tidalFocus = reader.int32();
                    break;
                case /* int32 improved_reincarnation */ 40:
                    message.improvedReincarnation = reader.int32();
                    break;
                case /* int32 ancestral_healing */ 41:
                    message.ancestralHealing = reader.int32();
                    break;
                case /* int32 healing_focus */ 42:
                    message.healingFocus = reader.int32();
                    break;
                case /* bool water_shield */ 43:
                    message.waterShield = reader.bool();
                    break;
                case /* int32 tidal_mastery */ 44:
                    message.tidalMastery = reader.int32();
                    break;
                case /* int32 restorative_totems */ 45:
                    message.restorativeTotems = reader.int32();
                    break;
                case /* bool mana_tide_totem */ 46:
                    message.manaTideTotem = reader.bool();
                    break;
                case /* int32 healing_way */ 47:
                    message.healingWay = reader.int32();
                    break;
                case /* bool natures_swiftness */ 48:
                    message.naturesSwiftness = reader.bool();
                    break;
                case /* int32 purification */ 49:
                    message.purification = reader.int32();
                    break;
                case /* bool riptide */ 50:
                    message.riptide = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ShamanTalents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 convection = 1; */
        if (message.convection !== 0)
            writer.tag(1, WireType.Varint).int32(message.convection);
        /* int32 concussion = 2; */
        if (message.concussion !== 0)
            writer.tag(2, WireType.Varint).int32(message.concussion);
        /* int32 elemental_warding = 3; */
        if (message.elementalWarding !== 0)
            writer.tag(3, WireType.Varint).int32(message.elementalWarding);
        /* int32 reverberation = 4; */
        if (message.reverberation !== 0)
            writer.tag(4, WireType.Varint).int32(message.reverberation);
        /* int32 call_of_flame = 5; */
        if (message.callOfFlame !== 0)
            writer.tag(5, WireType.Varint).int32(message.callOfFlame);
        /* int32 elemental_devastation = 6; */
        if (message.elementalDevastation !== 0)
            writer.tag(6, WireType.Varint).int32(message.elementalDevastation);
        /* bool elemental_focus = 7; */
        if (message.elementalFocus !== false)
            writer.tag(7, WireType.Varint).bool(message.elementalFocus);
        /* int32 elemental_fury = 8; */
        if (message.elementalFury !== 0)
            writer.tag(8, WireType.Varint).int32(message.elementalFury);
        /* int32 improved_fire_nova = 9; */
        if (message.improvedFireNova !== 0)
            writer.tag(9, WireType.Varint).int32(message.improvedFireNova);
        /* int32 eye_of_the_storm = 10; */
        if (message.eyeOfTheStorm !== 0)
            writer.tag(10, WireType.Varint).int32(message.eyeOfTheStorm);
        /* bool call_of_thunder = 11; */
        if (message.callOfThunder !== false)
            writer.tag(11, WireType.Varint).bool(message.callOfThunder);
        /* int32 elemental_reach = 12; */
        if (message.elementalReach !== 0)
            writer.tag(12, WireType.Varint).int32(message.elementalReach);
        /* int32 lightning_overload = 13; */
        if (message.lightningOverload !== 0)
            writer.tag(13, WireType.Varint).int32(message.lightningOverload);
        /* bool earthbound = 14; */
        if (message.earthbound !== false)
            writer.tag(14, WireType.Varint).bool(message.earthbound);
        /* int32 elemental_alacrity = 15; */
        if (message.elementalAlacrity !== 0)
            writer.tag(15, WireType.Varint).int32(message.elementalAlacrity);
        /* bool lava_burst = 16; */
        if (message.lavaBurst !== false)
            writer.tag(16, WireType.Varint).bool(message.lavaBurst);
        /* int32 earths_grasp = 17; */
        if (message.earthsGrasp !== 0)
            writer.tag(17, WireType.Varint).int32(message.earthsGrasp);
        /* int32 thundering_strikes = 18; */
        if (message.thunderingStrikes !== 0)
            writer.tag(18, WireType.Varint).int32(message.thunderingStrikes);
        /* int32 ancestral_knowledge = 19; */
        if (message.ancestralKnowledge !== 0)
            writer.tag(19, WireType.Varint).int32(message.ancestralKnowledge);
        /* int32 guardian_totems = 20; */
        if (message.guardianTotems !== 0)
            writer.tag(20, WireType.Varint).int32(message.guardianTotems);
        /* int32 mental_dexterity = 21; */
        if (message.mentalDexterity !== 0)
            writer.tag(21, WireType.Varint).int32(message.mentalDexterity);
        /* int32 improved_ghost_wolf = 22; */
        if (message.improvedGhostWolf !== 0)
            writer.tag(22, WireType.Varint).int32(message.improvedGhostWolf);
        /* int32 improved_lightning_shield = 23; */
        if (message.improvedLightningShield !== 0)
            writer.tag(23, WireType.Varint).int32(message.improvedLightningShield);
        /* int32 elemental_weapons = 24; */
        if (message.elementalWeapons !== 0)
            writer.tag(24, WireType.Varint).int32(message.elementalWeapons);
        /* bool shamanistic_focus = 25; */
        if (message.shamanisticFocus !== false)
            writer.tag(25, WireType.Varint).bool(message.shamanisticFocus);
        /* int32 anticipation = 26; */
        if (message.anticipation !== 0)
            writer.tag(26, WireType.Varint).int32(message.anticipation);
        /* int32 toughness = 27; */
        if (message.toughness !== 0)
            writer.tag(27, WireType.Varint).int32(message.toughness);
        /* int32 flurry = 28; */
        if (message.flurry !== 0)
            writer.tag(28, WireType.Varint).int32(message.flurry);
        /* bool stormstrike = 29; */
        if (message.stormstrike !== false)
            writer.tag(29, WireType.Varint).bool(message.stormstrike);
        /* bool spirit_weapons = 30; */
        if (message.spiritWeapons !== false)
            writer.tag(30, WireType.Varint).bool(message.spiritWeapons);
        /* int32 mental_quickness = 31; */
        if (message.mentalQuickness !== 0)
            writer.tag(31, WireType.Varint).int32(message.mentalQuickness);
        /* int32 improved_stormstrike = 32; */
        if (message.improvedStormstrike !== 0)
            writer.tag(32, WireType.Varint).int32(message.improvedStormstrike);
        /* int32 maelstrom_weapon = 33; */
        if (message.maelstromWeapon !== 0)
            writer.tag(33, WireType.Varint).int32(message.maelstromWeapon);
        /* bool rage_of_the_farseer = 34; */
        if (message.rageOfTheFarseer !== false)
            writer.tag(34, WireType.Varint).bool(message.rageOfTheFarseer);
        /* int32 improved_healing_wave = 35; */
        if (message.improvedHealingWave !== 0)
            writer.tag(35, WireType.Varint).int32(message.improvedHealingWave);
        /* int32 totemic_focus = 36; */
        if (message.totemicFocus !== 0)
            writer.tag(36, WireType.Varint).int32(message.totemicFocus);
        /* int32 mindfulness = 37; */
        if (message.mindfulness !== 0)
            writer.tag(37, WireType.Varint).int32(message.mindfulness);
        /* int32 natural_grace = 38; */
        if (message.naturalGrace !== 0)
            writer.tag(38, WireType.Varint).int32(message.naturalGrace);
        /* int32 tidal_focus = 39; */
        if (message.tidalFocus !== 0)
            writer.tag(39, WireType.Varint).int32(message.tidalFocus);
        /* int32 improved_reincarnation = 40; */
        if (message.improvedReincarnation !== 0)
            writer.tag(40, WireType.Varint).int32(message.improvedReincarnation);
        /* int32 ancestral_healing = 41; */
        if (message.ancestralHealing !== 0)
            writer.tag(41, WireType.Varint).int32(message.ancestralHealing);
        /* int32 healing_focus = 42; */
        if (message.healingFocus !== 0)
            writer.tag(42, WireType.Varint).int32(message.healingFocus);
        /* bool water_shield = 43; */
        if (message.waterShield !== false)
            writer.tag(43, WireType.Varint).bool(message.waterShield);
        /* int32 tidal_mastery = 44; */
        if (message.tidalMastery !== 0)
            writer.tag(44, WireType.Varint).int32(message.tidalMastery);
        /* int32 restorative_totems = 45; */
        if (message.restorativeTotems !== 0)
            writer.tag(45, WireType.Varint).int32(message.restorativeTotems);
        /* bool mana_tide_totem = 46; */
        if (message.manaTideTotem !== false)
            writer.tag(46, WireType.Varint).bool(message.manaTideTotem);
        /* int32 healing_way = 47; */
        if (message.healingWay !== 0)
            writer.tag(47, WireType.Varint).int32(message.healingWay);
        /* bool natures_swiftness = 48; */
        if (message.naturesSwiftness !== false)
            writer.tag(48, WireType.Varint).bool(message.naturesSwiftness);
        /* int32 purification = 49; */
        if (message.purification !== 0)
            writer.tag(49, WireType.Varint).int32(message.purification);
        /* bool riptide = 50; */
        if (message.riptide !== false)
            writer.tag(50, WireType.Varint).bool(message.riptide);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ShamanTalents
 */
export const ShamanTalents = new ShamanTalents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ShamanTotems$Type extends MessageType<ShamanTotems> {
    constructor() {
        super("proto.ShamanTotems", [
            { no: 1, name: "earth", kind: "enum", T: () => ["proto.EarthTotem", EarthTotem] },
            { no: 2, name: "air", kind: "enum", T: () => ["proto.AirTotem", AirTotem] },
            { no: 3, name: "fire", kind: "enum", T: () => ["proto.FireTotem", FireTotem] },
            { no: 4, name: "water", kind: "enum", T: () => ["proto.WaterTotem", WaterTotem] },
            { no: 5, name: "use_mana_tide", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "recall_totems", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "use_fire_mcd", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "bonus_spellpower", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "enh_tier_ten_bonus", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ShamanTotems>): ShamanTotems {
        const message = { earth: 0, air: 0, fire: 0, water: 0, useManaTide: false, recallTotems: false, useFireMcd: false, bonusSpellpower: 0, enhTierTenBonus: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ShamanTotems>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ShamanTotems): ShamanTotems {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.EarthTotem earth */ 1:
                    message.earth = reader.int32();
                    break;
                case /* proto.AirTotem air */ 2:
                    message.air = reader.int32();
                    break;
                case /* proto.FireTotem fire */ 3:
                    message.fire = reader.int32();
                    break;
                case /* proto.WaterTotem water */ 4:
                    message.water = reader.int32();
                    break;
                case /* bool use_mana_tide */ 5:
                    message.useManaTide = reader.bool();
                    break;
                case /* bool recall_totems */ 8:
                    message.recallTotems = reader.bool();
                    break;
                case /* bool use_fire_mcd */ 9:
                    message.useFireMcd = reader.bool();
                    break;
                case /* int32 bonus_spellpower */ 10:
                    message.bonusSpellpower = reader.int32();
                    break;
                case /* bool enh_tier_ten_bonus */ 11:
                    message.enhTierTenBonus = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ShamanTotems, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.EarthTotem earth = 1; */
        if (message.earth !== 0)
            writer.tag(1, WireType.Varint).int32(message.earth);
        /* proto.AirTotem air = 2; */
        if (message.air !== 0)
            writer.tag(2, WireType.Varint).int32(message.air);
        /* proto.FireTotem fire = 3; */
        if (message.fire !== 0)
            writer.tag(3, WireType.Varint).int32(message.fire);
        /* proto.WaterTotem water = 4; */
        if (message.water !== 0)
            writer.tag(4, WireType.Varint).int32(message.water);
        /* bool use_mana_tide = 5; */
        if (message.useManaTide !== false)
            writer.tag(5, WireType.Varint).bool(message.useManaTide);
        /* bool recall_totems = 8; */
        if (message.recallTotems !== false)
            writer.tag(8, WireType.Varint).bool(message.recallTotems);
        /* bool use_fire_mcd = 9; */
        if (message.useFireMcd !== false)
            writer.tag(9, WireType.Varint).bool(message.useFireMcd);
        /* int32 bonus_spellpower = 10; */
        if (message.bonusSpellpower !== 0)
            writer.tag(10, WireType.Varint).int32(message.bonusSpellpower);
        /* bool enh_tier_ten_bonus = 11; */
        if (message.enhTierTenBonus !== false)
            writer.tag(11, WireType.Varint).bool(message.enhTierTenBonus);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ShamanTotems
 */
export const ShamanTotems = new ShamanTotems$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ElementalShaman$Type extends MessageType<ElementalShaman> {
    constructor() {
        super("proto.ElementalShaman", [
            { no: 3, name: "options", kind: "message", T: () => ElementalShaman_Options }
        ]);
    }
    create(value?: PartialMessage<ElementalShaman>): ElementalShaman {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ElementalShaman>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ElementalShaman): ElementalShaman {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.ElementalShaman.Options options */ 3:
                    message.options = ElementalShaman_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ElementalShaman, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.ElementalShaman.Options options = 3; */
        if (message.options)
            ElementalShaman_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ElementalShaman
 */
export const ElementalShaman = new ElementalShaman$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ElementalShaman_Rotation$Type extends MessageType<ElementalShaman_Rotation> {
    constructor() {
        super("proto.ElementalShaman.Rotation", []);
    }
    create(value?: PartialMessage<ElementalShaman_Rotation>): ElementalShaman_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ElementalShaman_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ElementalShaman_Rotation): ElementalShaman_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ElementalShaman_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ElementalShaman.Rotation
 */
export const ElementalShaman_Rotation = new ElementalShaman_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ElementalShaman_Options$Type extends MessageType<ElementalShaman_Options> {
    constructor() {
        super("proto.ElementalShaman.Options", []);
    }
    create(value?: PartialMessage<ElementalShaman_Options>): ElementalShaman_Options {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ElementalShaman_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ElementalShaman_Options): ElementalShaman_Options {
        return target ?? this.create();
    }
    internalBinaryWrite(message: ElementalShaman_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.ElementalShaman.Options
 */
export const ElementalShaman_Options = new ElementalShaman_Options$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnhancementShaman$Type extends MessageType<EnhancementShaman> {
    constructor() {
        super("proto.EnhancementShaman", [
            { no: 3, name: "options", kind: "message", T: () => EnhancementShaman_Options }
        ]);
    }
    create(value?: PartialMessage<EnhancementShaman>): EnhancementShaman {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<EnhancementShaman>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnhancementShaman): EnhancementShaman {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.EnhancementShaman.Options options */ 3:
                    message.options = EnhancementShaman_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnhancementShaman, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.EnhancementShaman.Options options = 3; */
        if (message.options)
            EnhancementShaman_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.EnhancementShaman
 */
export const EnhancementShaman = new EnhancementShaman$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnhancementShaman_Rotation$Type extends MessageType<EnhancementShaman_Rotation> {
    constructor() {
        super("proto.EnhancementShaman.Rotation", []);
    }
    create(value?: PartialMessage<EnhancementShaman_Rotation>): EnhancementShaman_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<EnhancementShaman_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnhancementShaman_Rotation): EnhancementShaman_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: EnhancementShaman_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.EnhancementShaman.Rotation
 */
export const EnhancementShaman_Rotation = new EnhancementShaman_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnhancementShaman_Options$Type extends MessageType<EnhancementShaman_Options> {
    constructor() {
        super("proto.EnhancementShaman.Options", [
            { no: 3, name: "sync_type", kind: "enum", T: () => ["proto.ShamanSyncType", ShamanSyncType] }
        ]);
    }
    create(value?: PartialMessage<EnhancementShaman_Options>): EnhancementShaman_Options {
        const message = { syncType: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<EnhancementShaman_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnhancementShaman_Options): EnhancementShaman_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.ShamanSyncType sync_type */ 3:
                    message.syncType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnhancementShaman_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.ShamanSyncType sync_type = 3; */
        if (message.syncType !== 0)
            writer.tag(3, WireType.Varint).int32(message.syncType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.EnhancementShaman.Options
 */
export const EnhancementShaman_Options = new EnhancementShaman_Options$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestorationShaman$Type extends MessageType<RestorationShaman> {
    constructor() {
        super("proto.RestorationShaman", [
            { no: 3, name: "options", kind: "message", T: () => RestorationShaman_Options }
        ]);
    }
    create(value?: PartialMessage<RestorationShaman>): RestorationShaman {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RestorationShaman>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestorationShaman): RestorationShaman {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.RestorationShaman.Options options */ 3:
                    message.options = RestorationShaman_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RestorationShaman, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.RestorationShaman.Options options = 3; */
        if (message.options)
            RestorationShaman_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RestorationShaman
 */
export const RestorationShaman = new RestorationShaman$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestorationShaman_Rotation$Type extends MessageType<RestorationShaman_Rotation> {
    constructor() {
        super("proto.RestorationShaman.Rotation", []);
    }
    create(value?: PartialMessage<RestorationShaman_Rotation>): RestorationShaman_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RestorationShaman_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestorationShaman_Rotation): RestorationShaman_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: RestorationShaman_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RestorationShaman.Rotation
 */
export const RestorationShaman_Rotation = new RestorationShaman_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestorationShaman_Options$Type extends MessageType<RestorationShaman_Options> {
    constructor() {
        super("proto.RestorationShaman.Options", [
            { no: 5, name: "earth_shield_p_p_m", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "totems", kind: "message", T: () => ShamanTotems }
        ]);
    }
    create(value?: PartialMessage<RestorationShaman_Options>): RestorationShaman_Options {
        const message = { earthShieldPPM: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RestorationShaman_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestorationShaman_Options): RestorationShaman_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 earth_shield_p_p_m */ 5:
                    message.earthShieldPPM = reader.int32();
                    break;
                case /* proto.ShamanTotems totems = 6 [deprecated = true];*/ 6:
                    message.totems = ShamanTotems.internalBinaryRead(reader, reader.uint32(), options, message.totems);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RestorationShaman_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 earth_shield_p_p_m = 5; */
        if (message.earthShieldPPM !== 0)
            writer.tag(5, WireType.Varint).int32(message.earthShieldPPM);
        /* proto.ShamanTotems totems = 6 [deprecated = true]; */
        if (message.totems)
            ShamanTotems.internalBinaryWrite(message.totems, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.RestorationShaman.Options
 */
export const RestorationShaman_Options = new RestorationShaman_Options$Type();
