// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "warlock.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * DO NOT REMOVE THE COMMENTS
 * BEGIN GENERATED
 * WarlockTalents message.
 *
 * @generated from protobuf message proto.WarlockTalents
 */
export interface WarlockTalents {
    /**
     * Affliction
     *
     * @generated from protobuf field: int32 improved_life_tap = 1;
     */
    improvedLifeTap: number;
    /**
     * @generated from protobuf field: int32 suppression = 2;
     */
    suppression: number;
    /**
     * @generated from protobuf field: int32 improved_corruption = 3;
     */
    improvedCorruption: number;
    /**
     * @generated from protobuf field: int32 malediction = 4;
     */
    malediction: number;
    /**
     * @generated from protobuf field: int32 soul_harvesting = 5;
     */
    soulHarvesting: number;
    /**
     * @generated from protobuf field: int32 improved_drains = 6;
     */
    improvedDrains: number;
    /**
     * @generated from protobuf field: int32 improved_bane_of_agony = 7;
     */
    improvedBaneOfAgony: number;
    /**
     * @generated from protobuf field: int32 fel_concentration = 8;
     */
    felConcentration: number;
    /**
     * @generated from protobuf field: bool amplify_curse = 9;
     */
    amplifyCurse: boolean;
    /**
     * @generated from protobuf field: int32 pandemic = 10;
     */
    pandemic: number;
    /**
     * @generated from protobuf field: int32 malevolence = 11;
     */
    malevolence: number;
    /**
     * @generated from protobuf field: int32 nightfall = 12;
     */
    nightfall: number;
    /**
     * @generated from protobuf field: bool curse_of_exhaustion = 13;
     */
    curseOfExhaustion: boolean;
    /**
     * @generated from protobuf field: bool siphon_life = 14;
     */
    siphonLife: boolean;
    /**
     * @generated from protobuf field: int32 soul_siphon = 15;
     */
    soulSiphon: number;
    /**
     * @generated from protobuf field: int32 shadow_mastery = 16;
     */
    shadowMastery: number;
    /**
     * @generated from protobuf field: bool wrack = 17;
     */
    wrack: boolean;
    /**
     * Demonology
     *
     * @generated from protobuf field: int32 improved_health_funnel = 18;
     */
    improvedHealthFunnel: number;
    /**
     * @generated from protobuf field: int32 improved_imp = 19;
     */
    improvedImp: number;
    /**
     * @generated from protobuf field: int32 demonic_embrace = 20;
     */
    demonicEmbrace: number;
    /**
     * @generated from protobuf field: int32 unholy_power = 21;
     */
    unholyPower: number;
    /**
     * @generated from protobuf field: int32 demonic_aegis = 22;
     */
    demonicAegis: number;
    /**
     * @generated from protobuf field: int32 improved_voidwalker = 23;
     */
    improvedVoidwalker: number;
    /**
     * @generated from protobuf field: int32 fel_vitality = 24;
     */
    felVitality: number;
    /**
     * @generated from protobuf field: int32 demonic_energies = 25;
     */
    demonicEnergies: number;
    /**
     * @generated from protobuf field: int32 improved_sayaad = 26;
     */
    improvedSayaad: number;
    /**
     * @generated from protobuf field: bool demonic_sacrifice = 27;
     */
    demonicSacrifice: boolean;
    /**
     * @generated from protobuf field: int32 master_summoner = 28;
     */
    masterSummoner: number;
    /**
     * @generated from protobuf field: int32 decimation = 29;
     */
    decimation: number;
    /**
     * @generated from protobuf field: bool fel_domination = 30;
     */
    felDomination: boolean;
    /**
     * @generated from protobuf field: int32 demonic_brand = 31;
     */
    demonicBrand: number;
    /**
     * @generated from protobuf field: int32 improved_felhunter = 32;
     */
    improvedFelhunter: number;
    /**
     * @generated from protobuf field: bool soul_link = 33;
     */
    soulLink: boolean;
    /**
     * @generated from protobuf field: int32 demonic_knowledge = 34;
     */
    demonicKnowledge: number;
    /**
     * @generated from protobuf field: int32 master_demonologist = 35;
     */
    masterDemonologist: number;
    /**
     * @generated from protobuf field: bool demonic_pact = 36;
     */
    demonicPact: boolean;
    /**
     * Destruction
     *
     * @generated from protobuf field: int32 destructive_reach = 37;
     */
    destructiveReach: number;
    /**
     * @generated from protobuf field: int32 improved_shadow_bolt = 38;
     */
    improvedShadowBolt: number;
    /**
     * @generated from protobuf field: int32 bane = 39;
     */
    bane: number;
    /**
     * @generated from protobuf field: int32 molten_skin = 40;
     */
    moltenSkin: number;
    /**
     * @generated from protobuf field: int32 cataclysm = 41;
     */
    cataclysm: number;
    /**
     * @generated from protobuf field: int32 aftermath = 42;
     */
    aftermath: number;
    /**
     * @generated from protobuf field: int32 ruin = 43;
     */
    ruin: number;
    /**
     * @generated from protobuf field: bool shadowburn = 44;
     */
    shadowburn: boolean;
    /**
     * @generated from protobuf field: int32 intensity = 45;
     */
    intensity: number;
    /**
     * @generated from protobuf field: int32 agonizing_flames = 46;
     */
    agonizingFlames: number;
    /**
     * @generated from protobuf field: bool conflagrate = 47;
     */
    conflagrate: boolean;
    /**
     * @generated from protobuf field: int32 pyroclasm = 48;
     */
    pyroclasm: number;
    /**
     * @generated from protobuf field: bool bane_of_havoc = 49;
     */
    baneOfHavoc: boolean;
    /**
     * @generated from protobuf field: int32 fire_and_brimstone = 50;
     */
    fireAndBrimstone: number;
    /**
     * @generated from protobuf field: int32 shadow_and_flame = 51;
     */
    shadowAndFlame: number;
    /**
     * @generated from protobuf field: bool incinerate = 52;
     */
    incinerate: boolean;
}
/**
 * END GENERATED
 *
 * @generated from protobuf message proto.WarlockRotation
 */
export interface WarlockRotation {
}
/**
 * @generated from protobuf message proto.WarlockOptions
 */
export interface WarlockOptions {
    /**
     * @generated from protobuf field: proto.WarlockOptions.Armor armor = 1;
     */
    armor: WarlockOptions_Armor;
    /**
     * @generated from protobuf field: proto.WarlockOptions.Summon summon = 2;
     */
    summon: WarlockOptions_Summon;
    /**
     * @generated from protobuf field: proto.WarlockOptions.WeaponImbue weapon_imbue = 3;
     */
    weaponImbue: WarlockOptions_WeaponImbue;
    /**
     * @generated from protobuf field: proto.WarlockOptions.MaxFireboltRank max_firebolt_rank = 4;
     */
    maxFireboltRank: WarlockOptions_MaxFireboltRank;
    /**
     * @generated from protobuf field: bool pet_pool_mana = 5;
     */
    petPoolMana: boolean;
    /**
     * Demon sacrificed before the pull, needs Demonic Pact to be used together with a summoned demon.
     *
     * @generated from protobuf field: proto.WarlockOptions.Summon sacrifice = 6;
     */
    sacrifice: WarlockOptions_Summon;
}
/**
 * @generated from protobuf enum proto.WarlockOptions.Summon
 */
export enum WarlockOptions_Summon {
    /**
     * @generated from protobuf enum value: NoSummon = 0;
     */
    NoSummon = 0,
    /**
     * @generated from protobuf enum value: Imp = 1;
     */
    Imp = 1,
    /**
     * @generated from protobuf enum value: Voidwalker = 2;
     */
    Voidwalker = 2,
    /**
     * @generated from protobuf enum value: Succubus = 3;
     */
    Succubus = 3,
    /**
     * @generated from protobuf enum value: Felhunter = 4;
     */
    Felhunter = 4
}
/**
 * @generated from protobuf enum proto.WarlockOptions.Armor
 */
export enum WarlockOptions_Armor {
    /**
     * @generated from protobuf enum value: NoArmor = 0;
     */
    NoArmor = 0,
    /**
     * @generated from protobuf enum value: DemonArmor = 1;
     */
    DemonArmor = 1
}
/**
 * @generated from protobuf enum proto.WarlockOptions.WeaponImbue
 */
export enum WarlockOptions_WeaponImbue {
    /**
     * @generated from protobuf enum value: NoWeaponImbue = 0;
     */
    NoWeaponImbue = 0,
    /**
     * @generated from protobuf enum value: Spellstone = 1;
     */
    Spellstone = 1,
    /**
     * @generated from protobuf enum value: Firestone = 2;
     */
    Firestone = 2
}
/**
 * @generated from protobuf enum proto.WarlockOptions.MaxFireboltRank
 */
export enum WarlockOptions_MaxFireboltRank {
    /**
     * @generated from protobuf enum value: NoMaximum = 0;
     */
    NoMaximum = 0,
    /**
     * @generated from protobuf enum value: Rank1 = 1;
     */
    Rank1 = 1,
    /**
     * @generated from protobuf enum value: Rank2 = 2;
     */
    Rank2 = 2,
    /**
     * @generated from protobuf enum value: Rank3 = 3;
     */
    Rank3 = 3,
    /**
     * @generated from protobuf enum value: Rank4 = 4;
     */
    Rank4 = 4,
    /**
     * @generated from protobuf enum value: Rank5 = 5;
     */
    Rank5 = 5,
    /**
     * @generated from protobuf enum value: Rank6 = 6;
     */
    Rank6 = 6,
    /**
     * @generated from protobuf enum value: Rank7 = 7;
     */
    Rank7 = 7,
    /**
     * @generated from protobuf enum value: Rank8 = 8;
     */
    Rank8 = 8
}
/**
 * @generated from protobuf message proto.Warlock
 */
export interface Warlock {
    /**
     * @generated from protobuf field: proto.WarlockOptions options = 2;
     */
    options?: WarlockOptions;
}
/**
 * @generated from protobuf message proto.TankWarlock
 */
export interface TankWarlock {
    /**
     * @generated from protobuf field: proto.WarlockOptions options = 2;
     */
    options?: WarlockOptions;
}
// @generated message type with reflection information, may provide speed optimized methods
class WarlockTalents$Type extends MessageType<WarlockTalents> {
    constructor() {
        super("proto.WarlockTalents", [
            { no: 1, name: "improved_life_tap", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "suppression", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "improved_corruption", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "malediction", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "soul_harvesting", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "improved_drains", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "improved_bane_of_agony", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "fel_concentration", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "amplify_curse", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "pandemic", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "malevolence", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "nightfall", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "curse_of_exhaustion", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "siphon_life", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "soul_siphon", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "shadow_mastery", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "wrack", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "improved_health_funnel", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "improved_imp", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "demonic_embrace", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "unholy_power", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "demonic_aegis", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 23, name: "improved_voidwalker", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 24, name: "fel_vitality", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 25, name: "demonic_energies", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 26, name: "improved_sayaad", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "demonic_sacrifice", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 28, name: "master_summoner", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 29, name: "decimation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 30, name: "fel_domination", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 31, name: "demonic_brand", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 32, name: "improved_felhunter", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 33, name: "soul_link", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 34, name: "demonic_knowledge", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 35, name: "master_demonologist", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 36, name: "demonic_pact", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 37, name: "destructive_reach", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 38, name: "improved_shadow_bolt", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 39, name: "bane", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 40, name: "molten_skin", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 41, name: "cataclysm", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 42, name: "aftermath", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 43, name: "ruin", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 44, name: "shadowburn", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 45, name: "intensity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 46, name: "agonizing_flames", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 47, name: "conflagrate", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 48, name: "pyroclasm", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 49, name: "bane_of_havoc", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 50, name: "fire_and_brimstone", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 51, name: "shadow_and_flame", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 52, name: "incinerate", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<WarlockTalents>): WarlockTalents {
        const message = { improvedLifeTap: 0, suppression: 0, improvedCorruption: 0, malediction: 0, soulHarvesting: 0, improvedDrains: 0, improvedBaneOfAgony: 0, felConcentration: 0, amplifyCurse: false, pandemic: 0, malevolence: 0, nightfall: 0, curseOfExhaustion: false, siphonLife: false, soulSiphon: 0, shadowMastery: 0, wrack: false, improvedHealthFunnel: 0, improvedImp: 0, demonicEmbrace: 0, unholyPower: 0, demonicAegis: 0, improvedVoidwalker: 0, felVitality: 0, demonicEnergies: 0, improvedSayaad: 0, demonicSacrifice: false, masterSummoner: 0, decimation: 0, felDomination: false, demonicBrand: 0, improvedFelhunter: 0, soulLink: false, demonicKnowledge: 0, masterDemonologist: 0, demonicPact: false, destructiveReach: 0, improvedShadowBolt: 0, bane: 0, moltenSkin: 0, cataclysm: 0, aftermath: 0, ruin: 0, shadowburn: false, intensity: 0, agonizingFlames: 0, conflagrate: false, pyroclasm: 0, baneOfHavoc: false, fireAndBrimstone: 0, shadowAndFlame: 0, incinerate: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WarlockTalents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WarlockTalents): WarlockTalents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 improved_life_tap */ 1:
                    message.improvedLifeTap = reader.int32();
                    break;
                case /* int32 suppression */ 2:
                    message.suppression = reader.int32();
                    break;
                case /* int32 improved_corruption */ 3:
                    message.improvedCorruption = reader.int32();
                    break;
                case /* int32 malediction */ 4:
                    message.malediction = reader.int32();
                    break;
                case /* int32 soul_harvesting */ 5:
                    message.soulHarvesting = reader.int32();
                    break;
                case /* int32 improved_drains */ 6:
                    message.improvedDrains = reader.int32();
                    break;
                case /* int32 improved_bane_of_agony */ 7:
                    message.improvedBaneOfAgony = reader.int32();
                    break;
                case /* int32 fel_concentration */ 8:
                    message.felConcentration = reader.int32();
                    break;
                case /* bool amplify_curse */ 9:
                    message.amplifyCurse = reader.bool();
                    break;
                case /* int32 pandemic */ 10:
                    message.pandemic = reader.int32();
                    break;
                case /* int32 malevolence */ 11:
                    message.malevolence = reader.int32();
                    break;
                case /* int32 nightfall */ 12:
                    message.nightfall = reader.int32();
                    break;
                case /* bool curse_of_exhaustion */ 13:
                    message.curseOfExhaustion = reader.bool();
                    break;
                case /* bool siphon_life */ 14:
                    message.siphonLife = reader.bool();
                    break;
                case /* int32 soul_siphon */ 15:
                    message.soulSiphon = reader.int32();
                    break;
                case /* int32 shadow_mastery */ 16:
                    message.shadowMastery = reader.int32();
                    break;
                case /* bool wrack */ 17:
                    message.wrack = reader.bool();
                    break;
                case /* int32 improved_health_funnel */ 18:
                    message.improvedHealthFunnel = reader.int32();
                    break;
                case /* int32 improved_imp */ 19:
                    message.improvedImp = reader.int32();
                    break;
                case /* int32 demonic_embrace */ 20:
                    message.demonicEmbrace = reader.int32();
                    break;
                case /* int32 unholy_power */ 21:
                    message.unholyPower = reader.int32();
                    break;
                case /* int32 demonic_aegis */ 22:
                    message.demonicAegis = reader.int32();
                    break;
                case /* int32 improved_voidwalker */ 23:
                    message.improvedVoidwalker = reader.int32();
                    break;
                case /* int32 fel_vitality */ 24:
                    message.felVitality = reader.int32();
                    break;
                case /* int32 demonic_energies */ 25:
                    message.demonicEnergies = reader.int32();
                    break;
                case /* int32 improved_sayaad */ 26:
                    message.improvedSayaad = reader.int32();
                    break;
                case /* bool demonic_sacrifice */ 27:
                    message.demonicSacrifice = reader.bool();
                    break;
                case /* int32 master_summoner */ 28:
                    message.masterSummoner = reader.int32();
                    break;
                case /* int32 decimation */ 29:
                    message.decimation = reader.int32();
                    break;
                case /* bool fel_domination */ 30:
                    message.felDomination = reader.bool();
                    break;
                case /* int32 demonic_brand */ 31:
                    message.demonicBrand = reader.int32();
                    break;
                case /* int32 improved_felhunter */ 32:
                    message.improvedFelhunter = reader.int32();
                    break;
                case /* bool soul_link */ 33:
                    message.soulLink = reader.bool();
                    break;
                case /* int32 demonic_knowledge */ 34:
                    message.demonicKnowledge = reader.int32();
                    break;
                case /* int32 master_demonologist */ 35:
                    message.masterDemonologist = reader.int32();
                    break;
                case /* bool demonic_pact */ 36:
                    message.demonicPact = reader.bool();
                    break;
                case /* int32 destructive_reach */ 37:
                    message.destructiveReach = reader.int32();
                    break;
                case /* int32 improved_shadow_bolt */ 38:
                    message.improvedShadowBolt = reader.int32();
                    break;
                case /* int32 bane */ 39:
                    message.bane = reader.int32();
                    break;
                case /* int32 molten_skin */ 40:
                    message.moltenSkin = reader.int32();
                    break;
                case /* int32 cataclysm */ 41:
                    message.cataclysm = reader.int32();
                    break;
                case /* int32 aftermath */ 42:
                    message.aftermath = reader.int32();
                    break;
                case /* int32 ruin */ 43:
                    message.ruin = reader.int32();
                    break;
                case /* bool shadowburn */ 44:
                    message.shadowburn = reader.bool();
                    break;
                case /* int32 intensity */ 45:
                    message.intensity = reader.int32();
                    break;
                case /* int32 agonizing_flames */ 46:
                    message.agonizingFlames = reader.int32();
                    break;
                case /* bool conflagrate */ 47:
                    message.conflagrate = reader.bool();
                    break;
                case /* int32 pyroclasm */ 48:
                    message.pyroclasm = reader.int32();
                    break;
                case /* bool bane_of_havoc */ 49:
                    message.baneOfHavoc = reader.bool();
                    break;
                case /* int32 fire_and_brimstone */ 50:
                    message.fireAndBrimstone = reader.int32();
                    break;
                case /* int32 shadow_and_flame */ 51:
                    message.shadowAndFlame = reader.int32();
                    break;
                case /* bool incinerate */ 52:
                    message.incinerate = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WarlockTalents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 improved_life_tap = 1; */
        if (message.improvedLifeTap !== 0)
            writer.tag(1, WireType.Varint).int32(message.improvedLifeTap);
        /* int32 suppression = 2; */
        if (message.suppression !== 0)
            writer.tag(2, WireType.Varint).int32(message.suppression);
        /* int32 improved_corruption = 3; */
        if (message.improvedCorruption !== 0)
            writer.tag(3, WireType.Varint).int32(message.improvedCorruption);
        /* int32 malediction = 4; */
        if (message.malediction !== 0)
            writer.tag(4, WireType.Varint).int32(message.malediction);
        /* int32 soul_harvesting = 5; */
        if (message.soulHarvesting !== 0)
            writer.tag(5, WireType.Varint).int32(message.soulHarvesting);
        /* int32 improved_drains = 6; */
        if (message.improvedDrains !== 0)
            writer.tag(6, WireType.Varint).int32(message.improvedDrains);
        /* int32 improved_bane_of_agony = 7; */
        if (message.improvedBaneOfAgony !== 0)
            writer.tag(7, WireType.Varint).int32(message.improvedBaneOfAgony);
        /* int32 fel_concentration = 8; */
        if (message.felConcentration !== 0)
            writer.tag(8, WireType.Varint).int32(message.felConcentration);
        /* bool amplify_curse = 9; */
        if (message.amplifyCurse !== false)
            writer.tag(9, WireType.Varint).bool(message.amplifyCurse);
        /* int32 pandemic = 10; */
        if (message.pandemic !== 0)
            writer.tag(10, WireType.Varint).int32(message.pandemic);
        /* int32 malevolence = 11; */
        if (message.malevolence !== 0)
            writer.tag(11, WireType.Varint).int32(message.malevolence);
        /* int32 nightfall = 12; */
        if (message.nightfall !== 0)
            writer.tag(12, WireType.Varint).int32(message.nightfall);
        /* bool curse_of_exhaustion = 13; */
        if (message.curseOfExhaustion !== false)
            writer.tag(13, WireType.Varint).bool(message.curseOfExhaustion);
        /* bool siphon_life = 14; */
        if (message.siphonLife !== false)
            writer.tag(14, WireType.Varint).bool(message.siphonLife);
        /* int32 soul_siphon = 15; */
        if (message.soulSiphon !== 0)
            writer.tag(15, WireType.Varint).int32(message.soulSiphon);
        /* int32 shadow_mastery = 16; */
        if (message.shadowMastery !== 0)
            writer.tag(16, WireType.Varint).int32(message.shadowMastery);
        /* bool wrack = 17; */
        if (message.wrack !== false)
            writer.tag(17, WireType.Varint).bool(message.wrack);
        /* int32 improved_health_funnel = 18; */
        if (message.improvedHealthFunnel !== 0)
            writer.tag(18, WireType.Varint).int32(message.improvedHealthFunnel);
        /* int32 improved_imp = 19; */
        if (message.improvedImp !== 0)
            writer.tag(19, WireType.Varint).int32(message.improvedImp);
        /* int32 demonic_embrace = 20; */
        if (message.demonicEmbrace !== 0)
            writer.tag(20, WireType.Varint).int32(message.demonicEmbrace);
        /* int32 unholy_power = 21; */
        if (message.unholyPower !== 0)
            writer.tag(21, WireType.Varint).int32(message.unholyPower);
        /* int32 demonic_aegis = 22; */
        if (message.demonicAegis !== 0)
            writer.tag(22, WireType.Varint).int32(message.demonicAegis);
        /* int32 improved_voidwalker = 23; */
        if (message.improvedVoidwalker !== 0)
            writer.tag(23, WireType.Varint).int32(message.improvedVoidwalker);
        /* int32 fel_vitality = 24; */
        if (message.felVitality !== 0)
            writer.tag(24, WireType.Varint).int32(message.felVitality);
        /* int32 demonic_energies = 25; */
        if (message.demonicEnergies !== 0)
            writer.tag(25, WireType.Varint).int32(message.demonicEnergies);
        /* int32 improved_sayaad = 26; */
        if (message.improvedSayaad !== 0)
            writer.tag(26, WireType.Varint).int32(message.improvedSayaad);
        /* bool demonic_sacrifice = 27; */
        if (message.demonicSacrifice !== false)
            writer.tag(27, WireType.Varint).bool(message.demonicSacrifice);
        /* int32 master_summoner = 28; */
        if (message.masterSummoner !== 0)
            writer.tag(28, WireType.Varint).int32(message.masterSummoner);
        /* int32 decimation = 29; */
        if (message.decimation !== 0)
            writer.tag(29, WireType.Varint).int32(message.decimation);
        /* bool fel_domination = 30; */
        if (message.felDomination !== false)
            writer.tag(30, WireType.Varint).bool(message.felDomination);
        /* int32 demonic_brand = 31; */
        if (message.demonicBrand !== 0)
            writer.tag(31, WireType.Varint).int32(message.demonicBrand);
        /* int32 improved_felhunter = 32; */
        if (message.improvedFelhunter !== 0)
            writer.tag(32, WireType.Varint).int32(message.improvedFelhunter);
        /* bool soul_link = 33; */
        if (message.soulLink !== false)
            writer.tag(33, WireType.Varint).bool(message.soulLink);
        /* int32 demonic_knowledge = 34; */
        if (message.demonicKnowledge !== 0)
            writer.tag(34, WireType.Varint).int32(message.demonicKnowledge);
        /* int32 master_demonologist = 35; */
        if (message.masterDemonologist !== 0)
            writer.tag(35, WireType.Varint).int32(message.masterDemonologist);
        /* bool demonic_pact = 36; */
        if (message.demonicPact !== false)
            writer.tag(36, WireType.Varint).bool(message.demonicPact);
        /* int32 destructive_reach = 37; */
        if (message.destructiveReach !== 0)
            writer.tag(37, WireType.Varint).int32(message.destructiveReach);
        /* int32 improved_shadow_bolt = 38; */
        if (message.improvedShadowBolt !== 0)
            writer.tag(38, WireType.Varint).int32(message.improvedShadowBolt);
        /* int32 bane = 39; */
        if (message.bane !== 0)
            writer.tag(39, WireType.Varint).int32(message.bane);
        /* int32 molten_skin = 40; */
        if (message.moltenSkin !== 0)
            writer.tag(40, WireType.Varint).int32(message.moltenSkin);
        /* int32 cataclysm = 41; */
        if (message.cataclysm !== 0)
            writer.tag(41, WireType.Varint).int32(message.cataclysm);
        /* int32 aftermath = 42; */
        if (message.aftermath !== 0)
            writer.tag(42, WireType.Varint).int32(message.aftermath);
        /* int32 ruin = 43; */
        if (message.ruin !== 0)
            writer.tag(43, WireType.Varint).int32(message.ruin);
        /* bool shadowburn = 44; */
        if (message.shadowburn !== false)
            writer.tag(44, WireType.Varint).bool(message.shadowburn);
        /* int32 intensity = 45; */
        if (message.intensity !== 0)
            writer.tag(45, WireType.Varint).int32(message.intensity);
        /* int32 agonizing_flames = 46; */
        if (message.agonizingFlames !== 0)
            writer.tag(46, WireType.Varint).int32(message.agonizingFlames);
        /* bool conflagrate = 47; */
        if (message.conflagrate !== false)
            writer.tag(47, WireType.Varint).bool(message.conflagrate);
        /* int32 pyroclasm = 48; */
        if (message.pyroclasm !== 0)
            writer.tag(48, WireType.Varint).int32(message.pyroclasm);
        /* bool bane_of_havoc = 49; */
        if (message.baneOfHavoc !== false)
            writer.tag(49, WireType.Varint).bool(message.baneOfHavoc);
        /* int32 fire_and_brimstone = 50; */
        if (message.fireAndBrimstone !== 0)
            writer.tag(50, WireType.Varint).int32(message.fireAndBrimstone);
        /* int32 shadow_and_flame = 51; */
        if (message.shadowAndFlame !== 0)
            writer.tag(51, WireType.Varint).int32(message.shadowAndFlame);
        /* bool incinerate = 52; */
        if (message.incinerate !== false)
            writer.tag(52, WireType.Varint).bool(message.incinerate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.WarlockTalents
 */
export const WarlockTalents = new WarlockTalents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WarlockRotation$Type extends MessageType<WarlockRotation> {
    constructor() {
        super("proto.WarlockRotation", []);
    }
    create(value?: PartialMessage<WarlockRotation>): WarlockRotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WarlockRotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WarlockRotation): WarlockRotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: WarlockRotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.WarlockRotation
 */
export const WarlockRotation = new WarlockRotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WarlockOptions$Type extends MessageType<WarlockOptions> {
    constructor() {
        super("proto.WarlockOptions", [
            { no: 1, name: "armor", kind: "enum", T: () => ["proto.WarlockOptions.Armor", WarlockOptions_Armor] },
            { no: 2, name: "summon", kind: "enum", T: () => ["proto.WarlockOptions.Summon", WarlockOptions_Summon] },
            { no: 3, name: "weapon_imbue", kind: "enum", T: () => ["proto.WarlockOptions.WeaponImbue", WarlockOptions_WeaponImbue] },
            { no: 4, name: "max_firebolt_rank", kind: "enum", T: () => ["proto.WarlockOptions.MaxFireboltRank", WarlockOptions_MaxFireboltRank] },
            { no: 5, name: "pet_pool_mana", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "sacrifice", kind: "enum", T: () => ["proto.WarlockOptions.Summon", WarlockOptions_Summon] }
        ]);
    }
    create(value?: PartialMessage<WarlockOptions>): WarlockOptions {
        const message = { armor: 0, summon: 0, weaponImbue: 0, maxFireboltRank: 0, petPoolMana: false, sacrifice: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WarlockOptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WarlockOptions): WarlockOptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.WarlockOptions.Armor armor */ 1:
                    message.armor = reader.int32();
                    break;
                case /* proto.WarlockOptions.Summon summon */ 2:
                    message.summon = reader.int32();
                    break;
                case /* proto.WarlockOptions.WeaponImbue weapon_imbue */ 3:
                    message.weaponImbue = reader.int32();
                    break;
                case /* proto.WarlockOptions.MaxFireboltRank max_firebolt_rank */ 4:
                    message.maxFireboltRank = reader.int32();
                    break;
                case /* bool pet_pool_mana */ 5:
                    message.petPoolMana = reader.bool();
                    break;
                case /* proto.WarlockOptions.Summon sacrifice */ 6:
                    message.sacrifice = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WarlockOptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.WarlockOptions.Armor armor = 1; */
        if (message.armor !== 0)
            writer.tag(1, WireType.Varint).int32(message.armor);
        /* proto.WarlockOptions.Summon summon = 2; */
        if (message.summon !== 0)
            writer.tag(2, WireType.Varint).int32(message.summon);
        /* proto.WarlockOptions.WeaponImbue weapon_imbue = 3; */
        if (message.weaponImbue !== 0)
            writer.tag(3, WireType.Varint).int32(message.weaponImbue);
        /* proto.WarlockOptions.MaxFireboltRank max_firebolt_rank = 4; */
        if (message.maxFireboltRank !== 0)
            writer.tag(4, WireType.Varint).int32(message.maxFireboltRank);
        /* bool pet_pool_mana = 5; */
        if (message.petPoolMana !== false)
            writer.tag(5, WireType.Varint).bool(message.petPoolMana);
        /* proto.WarlockOptions.Summon sacrifice = 6; */
        if (message.sacrifice !== 0)
            writer.tag(6, WireType.Varint).int32(message.sacrifice);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.WarlockOptions
 */
export const WarlockOptions = new WarlockOptions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Warlock$Type extends MessageType<Warlock> {
    constructor() {
        super("proto.Warlock", [
            { no: 2, name: "options", kind: "message", T: () => WarlockOptions }
        ]);
    }
    create(value?: PartialMessage<Warlock>): Warlock {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Warlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Warlock): Warlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.WarlockOptions options */ 2:
                    message.options = WarlockOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Warlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.WarlockOptions options = 2; */
        if (message.options)
            WarlockOptions.internalBinaryWrite(message.options, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.Warlock
 */
export const Warlock = new Warlock$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TankWarlock$Type extends MessageType<TankWarlock> {
    constructor() {
        super("proto.TankWarlock", [
            { no: 2, name: "options", kind: "message", T: () => WarlockOptions }
        ]);
    }
    create(value?: PartialMessage<TankWarlock>): TankWarlock {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TankWarlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TankWarlock): TankWarlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.WarlockOptions options */ 2:
                    message.options = WarlockOptions.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TankWarlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.WarlockOptions options = 2; */
        if (message.options)
            WarlockOptions.internalBinaryWrite(message.options, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.TankWarlock
 */
export const TankWarlock = new TankWarlock$Type();
