// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "warrior.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * DO NOT REMOVE THE COMMENTS
 * BEGIN GENERATED
 * WarriorTalents message.
 *
 * @generated from protobuf message proto.WarriorTalents
 */
export interface WarriorTalents {
    /**
     * Arms
     *
     * @generated from protobuf field: int32 improved_heroic_strike = 1;
     */
    improvedHeroicStrike: number;
    /**
     * @generated from protobuf field: int32 deflection = 2;
     */
    deflection: number;
    /**
     * @generated from protobuf field: int32 improved_rend = 3;
     */
    improvedRend: number;
    /**
     * @generated from protobuf field: int32 improved_charge = 4;
     */
    improvedCharge: number;
    /**
     * @generated from protobuf field: int32 improved_tactical_mastery = 5;
     */
    improvedTacticalMastery: number;
    /**
     * @generated from protobuf field: int32 improved_overpower = 6;
     */
    improvedOverpower: number;
    /**
     * @generated from protobuf field: bool anger_management = 7;
     */
    angerManagement: boolean;
    /**
     * @generated from protobuf field: int32 deep_wounds = 8;
     */
    deepWounds: number;
    /**
     * @generated from protobuf field: bool spearing_strike = 9;
     */
    spearingStrike: boolean;
    /**
     * @generated from protobuf field: int32 two_handed_weapon_specialization = 10;
     */
    twoHandedWeaponSpecialization: number;
    /**
     * @generated from protobuf field: int32 impale = 11;
     */
    impale: number;
    /**
     * @generated from protobuf field: int32 bloodthrill = 12;
     */
    bloodthrill: number;
    /**
     * @generated from protobuf field: bool sweeping_strikes = 13;
     */
    sweepingStrikes: boolean;
    /**
     * @generated from protobuf field: int32 weaponmaster = 14;
     */
    weaponmaster: number;
    /**
     * @generated from protobuf field: int32 improved_slam = 15;
     */
    improvedSlam: number;
    /**
     * @generated from protobuf field: int32 improved_hamstring = 16;
     */
    improvedHamstring: number;
    /**
     * @generated from protobuf field: bool mortal_strike = 17;
     */
    mortalStrike: boolean;
    /**
     * Fury
     *
     * @generated from protobuf field: int32 booming_voice = 18;
     */
    boomingVoice: number;
    /**
     * @generated from protobuf field: int32 cruelty = 19;
     */
    cruelty: number;
    /**
     * @generated from protobuf field: int32 iron_will = 20;
     */
    ironWill: number;
    /**
     * @generated from protobuf field: int32 unbridled_wrath = 21;
     */
    unbridledWrath: number;
    /**
     * @generated from protobuf field: int32 improved_cleave = 22;
     */
    improvedCleave: number;
    /**
     * @generated from protobuf field: bool piercing_howl = 23;
     */
    piercingHowl: boolean;
    /**
     * @generated from protobuf field: int32 blood_craze = 24;
     */
    bloodCraze: number;
    /**
     * @generated from protobuf field: int32 boundless_rage = 25;
     */
    boundlessRage: number;
    /**
     * @generated from protobuf field: int32 dual_wield_specialization = 26;
     */
    dualWieldSpecialization: number;
    /**
     * @generated from protobuf field: bool raging_blows = 27;
     */
    ragingBlows: boolean;
    /**
     * @generated from protobuf field: int32 enrage = 28;
     */
    enrage: number;
    /**
     * @generated from protobuf field: int32 improved_execute = 29;
     */
    improvedExecute: number;
    /**
     * @generated from protobuf field: int32 precision = 30;
     */
    precision: number;
    /**
     * @generated from protobuf field: bool death_wish = 31;
     */
    deathWish: boolean;
    /**
     * @generated from protobuf field: int32 improved_intercept = 32;
     */
    improvedIntercept: number;
    /**
     * @generated from protobuf field: int32 improved_berserker_rage = 33;
     */
    improvedBerserkerRage: number;
    /**
     * @generated from protobuf field: int32 flurry = 34;
     */
    flurry: number;
    /**
     * @generated from protobuf field: bool bloodthirst = 35;
     */
    bloodthirst: boolean;
    /**
     * Protection
     *
     * @generated from protobuf field: int32 shield_specialization = 36;
     */
    shieldSpecialization: number;
    /**
     * @generated from protobuf field: int32 anticipation = 37;
     */
    anticipation: number;
    /**
     * @generated from protobuf field: int32 improved_bloodrage = 38;
     */
    improvedBloodrage: number;
    /**
     * @generated from protobuf field: int32 toughness = 39;
     */
    toughness: number;
    /**
     * @generated from protobuf field: int32 improved_thunder_clap = 40;
     */
    improvedThunderClap: number;
    /**
     * @generated from protobuf field: bool last_stand = 41;
     */
    lastStand: boolean;
    /**
     * @generated from protobuf field: int32 master_of_defense = 42;
     */
    masterOfDefense: number;
    /**
     * @generated from protobuf field: int32 improved_revenge = 43;
     */
    improvedRevenge: number;
    /**
     * @generated from protobuf field: int32 defiance = 44;
     */
    defiance: number;
    /**
     * @generated from protobuf field: int32 improved_sunder_armor = 45;
     */
    improvedSunderArmor: number;
    /**
     * @generated from protobuf field: int32 improved_disarm = 46;
     */
    improvedDisarm: number;
    /**
     * @generated from protobuf field: bool vanguard = 47;
     */
    vanguard: boolean;
    /**
     * @generated from protobuf field: int32 improved_shield_wall = 48;
     */
    improvedShieldWall: number;
    /**
     * @generated from protobuf field: bool concussion_blow = 49;
     */
    concussionBlow: boolean;
    /**
     * @generated from protobuf field: int32 improved_shield_bash = 50;
     */
    improvedShieldBash: number;
    /**
     * @generated from protobuf field: int32 bastion = 51;
     */
    bastion: number;
    /**
     * @generated from protobuf field: int32 focused_rage = 52;
     */
    focusedRage: number;
    /**
     * @generated from protobuf field: bool shield_slam = 53;
     */
    shieldSlam: boolean;
}
/**
 * @generated from protobuf message proto.Warrior
 */
export interface Warrior {
    /**
     * @generated from protobuf field: proto.Warrior.Options options = 3;
     */
    options?: Warrior_Options;
}
/**
 * @generated from protobuf message proto.Warrior.Rotation
 */
export interface Warrior_Rotation {
}
/**
 * @generated from protobuf message proto.Warrior.Options
 */
export interface Warrior_Options {
    /**
     * @generated from protobuf field: double starting_rage = 1;
     */
    startingRage: number;
    /**
     * @generated from protobuf field: bool stance_snapshot = 6;
     */
    stanceSnapshot: boolean;
    /**
     * @generated from protobuf field: int32 queue_delay = 8;
     */
    queueDelay: number;
    /**
     * @generated from protobuf field: proto.WarriorShout shout = 3;
     */
    shout: WarriorShout;
    /**
     * @generated from protobuf field: proto.WarriorStance stance = 7;
     */
    stance: WarriorStance;
}
/**
 * @generated from protobuf message proto.TankWarrior
 */
export interface TankWarrior {
    /**
     * @generated from protobuf field: proto.TankWarrior.Options options = 3;
     */
    options?: TankWarrior_Options;
}
/**
 * @generated from protobuf message proto.TankWarrior.Rotation
 */
export interface TankWarrior_Rotation {
}
/**
 * @generated from protobuf message proto.TankWarrior.Options
 */
export interface TankWarrior_Options {
    /**
     * @generated from protobuf field: double starting_rage = 1;
     */
    startingRage: number;
    /**
     * @generated from protobuf field: bool stance_snapshot = 6;
     */
    stanceSnapshot: boolean;
    /**
     * @generated from protobuf field: int32 queue_delay = 8;
     */
    queueDelay: number;
    /**
     * @generated from protobuf field: proto.WarriorShout shout = 3;
     */
    shout: WarriorShout;
    /**
     * @generated from protobuf field: proto.WarriorStance stance = 7;
     */
    stance: WarriorStance;
}
// END GENERATED

/**
 * @generated from protobuf enum proto.WarriorShout
 */
export enum WarriorShout {
    /**
     * @generated from protobuf enum value: WarriorShoutNone = 0;
     */
    WarriorShoutNone = 0,
    /**
     * @generated from protobuf enum value: WarriorShoutBattle = 1;
     */
    WarriorShoutBattle = 1,
    /**
     * @generated from protobuf enum value: WarriorShoutCommanding = 2;
     */
    WarriorShoutCommanding = 2
}
/**
 * @generated from protobuf enum proto.WarriorStance
 */
export enum WarriorStance {
    /**
     * @generated from protobuf enum value: WarriorStanceNone = 0;
     */
    WarriorStanceNone = 0,
    /**
     * @generated from protobuf enum value: WarriorStanceBattle = 1;
     */
    WarriorStanceBattle = 1,
    /**
     * @generated from protobuf enum value: WarriorStanceDefensive = 2;
     */
    WarriorStanceDefensive = 2,
    /**
     * @generated from protobuf enum value: WarriorStanceBerserker = 3;
     */
    WarriorStanceBerserker = 3,
    /**
     * @generated from protobuf enum value: WarriorStanceGladiator = 4;
     */
    WarriorStanceGladiator = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class WarriorTalents$Type extends MessageType<WarriorTalents> {
    constructor() {
        super("proto.WarriorTalents", [
            { no: 1, name: "improved_heroic_strike", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "deflection", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "improved_rend", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "improved_charge", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "improved_tactical_mastery", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "improved_overpower", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "anger_management", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "deep_wounds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "spearing_strike", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "two_handed_weapon_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "impale", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "bloodthrill", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "sweeping_strikes", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "weaponmaster", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 15, name: "improved_slam", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "improved_hamstring", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "mortal_strike", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "booming_voice", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "cruelty", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "iron_will", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "unbridled_wrath", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "improved_cleave", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 23, name: "piercing_howl", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 24, name: "blood_craze", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 25, name: "boundless_rage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 26, name: "dual_wield_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "raging_blows", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 28, name: "enrage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 29, name: "improved_execute", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 30, name: "precision", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 31, name: "death_wish", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 32, name: "improved_intercept", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 33, name: "improved_berserker_rage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 34, name: "flurry", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 35, name: "bloodthirst", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 36, name: "shield_specialization", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 37, name: "anticipation", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 38, name: "improved_bloodrage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 39, name: "toughness", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 40, name: "improved_thunder_clap", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 41, name: "last_stand", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 42, name: "master_of_defense", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 43, name: "improved_revenge", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 44, name: "defiance", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 45, name: "improved_sunder_armor", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 46, name: "improved_disarm", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 47, name: "vanguard", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 48, name: "improved_shield_wall", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 49, name: "concussion_blow", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 50, name: "improved_shield_bash", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 51, name: "bastion", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 52, name: "focused_rage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 53, name: "shield_slam", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<WarriorTalents>): WarriorTalents {
        const message = { improvedHeroicStrike: 0, deflection: 0, improvedRend: 0, improvedCharge: 0, improvedTacticalMastery: 0, improvedOverpower: 0, angerManagement: false, deepWounds: 0, spearingStrike: false, twoHandedWeaponSpecialization: 0, impale: 0, bloodthrill: 0, sweepingStrikes: false, weaponmaster: 0, improvedSlam: 0, improvedHamstring: 0, mortalStrike: false, boomingVoice: 0, cruelty: 0, ironWill: 0, unbridledWrath: 0, improvedCleave: 0, piercingHowl: false, bloodCraze: 0, boundlessRage: 0, dualWieldSpecialization: 0, ragingBlows: false, enrage: 0, improvedExecute: 0, precision: 0, deathWish: false, improvedIntercept: 0, improvedBerserkerRage: 0, flurry: 0, bloodthirst: false, shieldSpecialization: 0, anticipation: 0, improvedBloodrage: 0, toughness: 0, improvedThunderClap: 0, lastStand: false, masterOfDefense: 0, improvedRevenge: 0, defiance: 0, improvedSunderArmor: 0, improvedDisarm: 0, vanguard: false, improvedShieldWall: 0, concussionBlow: false, improvedShieldBash: 0, bastion: 0, focusedRage: 0, shieldSlam: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WarriorTalents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WarriorTalents): WarriorTalents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 improved_heroic_strike */ 1:
                    message.improvedHeroicStrike = reader.int32();
                    break;
                case /* int32 deflection */ 2:
                    message.deflection = reader.int32();
                    break;
                case /* int32 improved_rend */ 3:
                    message.improvedRend = reader.int32();
                    break;
                case /* int32 improved_charge */ 4:
                    message.improvedCharge = reader.int32();
                    break;
                case /* int32 improved_tactical_mastery */ 5:
                    message.improvedTacticalMastery = reader.int32();
                    break;
                case /* int32 improved_overpower */ 6:
                    message.improvedOverpower = reader.int32();
                    break;
                case /* bool anger_management */ 7:
                    message.angerManagement = reader.bool();
                    break;
                case /* int32 deep_wounds */ 8:
                    message.deepWounds = reader.int32();
                    break;
                case /* bool spearing_strike */ 9:
                    message.spearingStrike = reader.bool();
                    break;
                case /* int32 two_handed_weapon_specialization */ 10:
                    message.twoHandedWeaponSpecialization = reader.int32();
                    break;
                case /* int32 impale */ 11:
                    message.impale = reader.int32();
                    break;
                case /* int32 bloodthrill */ 12:
                    message.bloodthrill = reader.int32();
                    break;
                case /* bool sweeping_strikes */ 13:
                    message.sweepingStrikes = reader.bool();
                    break;
                case /* int32 weaponmaster */ 14:
                    message.weaponmaster = reader.int32();
                    break;
                case /* int32 improved_slam */ 15:
                    message.improvedSlam = reader.int32();
                    break;
                case /* int32 improved_hamstring */ 16:
                    message.improvedHamstring = reader.int32();
                    break;
                case /* bool mortal_strike */ 17:
                    message.mortalStrike = reader.bool();
                    break;
                case /* int32 booming_voice */ 18:
                    message.boomingVoice = reader.int32();
                    break;
                case /* int32 cruelty */ 19:
                    message.cruelty = reader.int32();
                    break;
                case /* int32 iron_will */ 20:
                    message.ironWill = reader.int32();
                    break;
                case /* int32 unbridled_wrath */ 21:
                    message.unbridledWrath = reader.int32();
                    break;
                case /* int32 improved_cleave */ 22:
                    message.improvedCleave = reader.int32();
                    break;
                case /* bool piercing_howl */ 23:
                    message.piercingHowl = reader.bool();
                    break;
                case /* int32 blood_craze */ 24:
                    message.bloodCraze = reader.int32();
                    break;
                case /* int32 boundless_rage */ 25:
                    message.boundlessRage = reader.int32();
                    break;
                case /* int32 dual_wield_specialization */ 26:
                    message.dualWieldSpecialization = reader.int32();
                    break;
                case /* bool raging_blows */ 27:
                    message.ragingBlows = reader.bool();
                    break;
                case /* int32 enrage */ 28:
                    message.enrage = reader.int32();
                    break;
                case /* int32 improved_execute */ 29:
                    message.improvedExecute = reader.int32();
                    break;
                case /* int32 precision */ 30:
                    message.precision = reader.int32();
                    break;
                case /* bool death_wish */ 31:
                    message.deathWish = reader.bool();
                    break;
                case /* int32 improved_intercept */ 32:
                    message.improvedIntercept = reader.int32();
                    break;
                case /* int32 improved_berserker_rage */ 33:
                    message.improvedBerserkerRage = reader.int32();
                    break;
                case /* int32 flurry */ 34:
                    message.flurry = reader.int32();
                    break;
                case /* bool bloodthirst */ 35:
                    message.bloodthirst = reader.bool();
                    break;
                case /* int32 shield_specialization */ 36:
                    message.shieldSpecialization = reader.int32();
                    break;
                case /* int32 anticipation */ 37:
                    message.anticipation = reader.int32();
                    break;
                case /* int32 improved_bloodrage */ 38:
                    message.improvedBloodrage = reader.int32();
                    break;
                case /* int32 toughness */ 39:
                    message.toughness = reader.int32();
                    break;
                case /* int32 improved_thunder_clap */ 40:
                    message.improvedThunderClap = reader.int32();
                    break;
                case /* bool last_stand */ 41:
                    message.lastStand = reader.bool();
                    break;
                case /* int32 master_of_defense */ 42:
                    message.masterOfDefense = reader.int32();
                    break;
                case /* int32 improved_revenge */ 43:
                    message.improvedRevenge = reader.int32();
                    break;
                case /* int32 defiance */ 44:
                    message.defiance = reader.int32();
                    break;
                case /* int32 improved_sunder_armor */ 45:
                    message.improvedSunderArmor = reader.int32();
                    break;
                case /* int32 improved_disarm */ 46:
                    message.improvedDisarm = reader.int32();
                    break;
                case /* bool vanguard */ 47:
                    message.vanguard = reader.bool();
                    break;
                case /* int32 improved_shield_wall */ 48:
                    message.improvedShieldWall = reader.int32();
                    break;
                case /* bool concussion_blow */ 49:
                    message.concussionBlow = reader.bool();
                    break;
                case /* int32 improved_shield_bash */ 50:
                    message.improvedShieldBash = reader.int32();
                    break;
                case /* int32 bastion */ 51:
                    message.bastion = reader.int32();
                    break;
                case /* int32 focused_rage */ 52:
                    message.focusedRage = reader.int32();
                    break;
                case /* bool shield_slam */ 53:
                    message.shieldSlam = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WarriorTalents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 improved_heroic_strike = 1; */
        if (message.improvedHeroicStrike !== 0)
            writer.tag(1, WireType.Varint).int32(message.improvedHeroicStrike);
        /* int32 deflection = 2; */
        if (message.deflection !== 0)
            writer.tag(2, WireType.Varint).int32(message.deflection);
        /* int32 improved_rend = 3; */
        if (message.improvedRend !== 0)
            writer.tag(3, WireType.Varint).int32(message.improvedRend);
        /* int32 improved_charge = 4; */
        if (message.improvedCharge !== 0)
            writer.tag(4, WireType.Varint).int32(message.improvedCharge);
        /* int32 improved_tactical_mastery = 5; */
        if (message.improvedTacticalMastery !== 0)
            writer.tag(5, WireType.Varint).int32(message.improvedTacticalMastery);
        /* int32 improved_overpower = 6; */
        if (message.improvedOverpower !== 0)
            writer.tag(6, WireType.Varint).int32(message.improvedOverpower);
        /* bool anger_management = 7; */
        if (message.angerManagement !== false)
            writer.tag(7, WireType.Varint).bool(message.angerManagement);
        /* int32 deep_wounds = 8; */
        if (message.deepWounds !== 0)
            writer.tag(8, WireType.Varint).int32(message.deepWounds);
        /* bool spearing_strike = 9; */
        if (message.spearingStrike !== false)
            writer.tag(9, WireType.Varint).bool(message.spearingStrike);
        /* int32 two_handed_weapon_specialization = 10; */
        if (message.twoHandedWeaponSpecialization !== 0)
            writer.tag(10, WireType.Varint).int32(message.twoHandedWeaponSpecialization);
        /* int32 impale = 11; */
        if (message.impale !== 0)
            writer.tag(11, WireType.Varint).int32(message.impale);
        /* int32 bloodthrill = 12; */
        if (message.bloodthrill !== 0)
            writer.tag(12, WireType.Varint).int32(message.bloodthrill);
        /* bool sweeping_strikes = 13; */
        if (message.sweepingStrikes !== false)
            writer.tag(13, WireType.Varint).bool(message.sweepingStrikes);
        /* int32 weaponmaster = 14; */
        if (message.weaponmaster !== 0)
            writer.tag(14, WireType.Varint).int32(message.weaponmaster);
        /* int32 improved_slam = 15; */
        if (message.improvedSlam !== 0)
            writer.tag(15, WireType.Varint).int32(message.improvedSlam);
        /* int32 improved_hamstring = 16; */
        if (message.improvedHamstring !== 0)
            writer.tag(16, WireType.Varint).int32(message.improvedHamstring);
        /* bool mortal_strike = 17; */
        if (message.mortalStrike !== false)
            writer.tag(17, WireType.Varint).bool(message.mortalStrike);
        /* int32 booming_voice = 18; */
        if (message.boomingVoice !== 0)
            writer.tag(18, WireType.Varint).int32(message.boomingVoice);
        /* int32 cruelty = 19; */
        if (message.cruelty !== 0)
            writer.tag(19, WireType.Varint).int32(message.cruelty);
        /* int32 iron_will = 20; */
        if (message.ironWill !== 0)
            writer.tag(20, WireType.Varint).int32(message.ironWill);
        /* int32 unbridled_wrath = 21; */
        if (message.unbridledWrath !== 0)
            writer.tag(21, WireType.Varint).int32(message.unbridledWrath);
        /* int32 improved_cleave = 22; */
        if (message.improvedCleave !== 0)
            writer.tag(22, WireType.Varint).int32(message.improvedCleave);
        /* bool piercing_howl = 23; */
        if (message.piercingHowl !== false)
            writer.tag(23, WireType.Varint).bool(message.piercingHowl);
        /* int32 blood_craze = 24; */
        if (message.bloodCraze !== 0)
            writer.tag(24, WireType.Varint).int32(message.bloodCraze);
        /* int32 boundless_rage = 25; */
        if (message.boundlessRage !== 0)
            writer.tag(25, WireType.Varint).int32(message.boundlessRage);
        /* int32 dual_wield_specialization = 26; */
        if (message.dualWieldSpecialization !== 0)
            writer.tag(26, WireType.Varint).int32(message.dualWieldSpecialization);
        /* bool raging_blows = 27; */
        if (message.ragingBlows !== false)
            writer.tag(27, WireType.Varint).bool(message.ragingBlows);
        /* int32 enrage = 28; */
        if (message.enrage !== 0)
            writer.tag(28, WireType.Varint).int32(message.enrage);
        /* int32 improved_execute = 29; */
        if (message.improvedExecute !== 0)
            writer.tag(29, WireType.Varint).int32(message.improvedExecute);
        /* int32 precision = 30; */
        if (message.precision !== 0)
            writer.tag(30, WireType.Varint).int32(message.precision);
        /* bool death_wish = 31; */
        if (message.deathWish !== false)
            writer.tag(31, WireType.Varint).bool(message.deathWish);
        /* int32 improved_intercept = 32; */
        if (message.improvedIntercept !== 0)
            writer.tag(32, WireType.Varint).int32(message.improvedIntercept);
        /* int32 improved_berserker_rage = 33; */
        if (message.improvedBerserkerRage !== 0)
            writer.tag(33, WireType.Varint).int32(message.improvedBerserkerRage);
        /* int32 flurry = 34; */
        if (message.flurry !== 0)
            writer.tag(34, WireType.Varint).int32(message.flurry);
        /* bool bloodthirst = 35; */
        if (message.bloodthirst !== false)
            writer.tag(35, WireType.Varint).bool(message.bloodthirst);
        /* int32 shield_specialization = 36; */
        if (message.shieldSpecialization !== 0)
            writer.tag(36, WireType.Varint).int32(message.shieldSpecialization);
        /* int32 anticipation = 37; */
        if (message.anticipation !== 0)
            writer.tag(37, WireType.Varint).int32(message.anticipation);
        /* int32 improved_bloodrage = 38; */
        if (message.improvedBloodrage !== 0)
            writer.tag(38, WireType.Varint).int32(message.improvedBloodrage);
        /* int32 toughness = 39; */
        if (message.toughness !== 0)
            writer.tag(39, WireType.Varint).int32(message.toughness);
        /* int32 improved_thunder_clap = 40; */
        if (message.improvedThunderClap !== 0)
            writer.tag(40, WireType.Varint).int32(message.improvedThunderClap);
        /* bool last_stand = 41; */
        if (message.lastStand !== false)
            writer.tag(41, WireType.Varint).bool(message.lastStand);
        /* int32 master_of_defense = 42; */
        if (message.masterOfDefense !== 0)
            writer.tag(42, WireType.Varint).int32(message.masterOfDefense);
        /* int32 improved_revenge = 43; */
        if (message.improvedRevenge !== 0)
            writer.tag(43, WireType.Varint).int32(message.improvedRevenge);
        /* int32 defiance = 44; */
        if (message.defiance !== 0)
            writer.tag(44, WireType.Varint).int32(message.defiance);
        /* int32 improved_sunder_armor = 45; */
        if (message.improvedSunderArmor !== 0)
            writer.tag(45, WireType.Varint).int32(message.improvedSunderArmor);
        /* int32 improved_disarm = 46; */
        if (message.improvedDisarm !== 0)
            writer.tag(46, WireType.Varint).int32(message.improvedDisarm);
        /* bool vanguard = 47; */
        if (message.vanguard !== false)
            writer.tag(47, WireType.Varint).bool(message.vanguard);
        /* int32 improved_shield_wall = 48; */
        if (message.improvedShieldWall !== 0)
            writer.tag(48, WireType.Varint).int32(message.improvedShieldWall);
        /* bool concussion_blow = 49; */
        if (message.concussionBlow !== false)
            writer.tag(49, WireType.Varint).bool(message.concussionBlow);
        /* int32 improved_shield_bash = 50; */
        if (message.improvedShieldBash !== 0)
            writer.tag(50, WireType.Varint).int32(message.improvedShieldBash);
        /* int32 bastion = 51; */
        if (message.bastion !== 0)
            writer.tag(51, WireType.Varint).int32(message.bastion);
        /* int32 focused_rage = 52; */
        if (message.focusedRage !== 0)
            writer.tag(52, WireType.Varint).int32(message.focusedRage);
        /* bool shield_slam = 53; */
        if (message.shieldSlam !== false)
            writer.tag(53, WireType.Varint).bool(message.shieldSlam);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.WarriorTalents
 */
export const WarriorTalents = new WarriorTalents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Warrior$Type extends MessageType<Warrior> {
    constructor() {
        super("proto.Warrior", [
            { no: 3, name: "options", kind: "message", T: () => Warrior_Options }
        ]);
    }
    create(value?: PartialMessage<Warrior>): Warrior {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Warrior>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Warrior): Warrior {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.Warrior.Options options */ 3:
                    message.options = Warrior_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Warrior, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.Warrior.Options options = 3; */
        if (message.options)
            Warrior_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.Warrior
 */
export const Warrior = new Warrior$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Warrior_Rotation$Type extends MessageType<Warrior_Rotation> {
    constructor() {
        super("proto.Warrior.Rotation", []);
    }
    create(value?: PartialMessage<Warrior_Rotation>): Warrior_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Warrior_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Warrior_Rotation): Warrior_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: Warrior_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.Warrior.Rotation
 */
export const Warrior_Rotation = new Warrior_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Warrior_Options$Type extends MessageType<Warrior_Options> {
    constructor() {
        super("proto.Warrior.Options", [
            { no: 1, name: "starting_rage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "stance_snapshot", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "queue_delay", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "shout", kind: "enum", T: () => ["proto.WarriorShout", WarriorShout] },
            { no: 7, name: "stance", kind: "enum", T: () => ["proto.WarriorStance", WarriorStance] }
        ]);
    }
    create(value?: PartialMessage<Warrior_Options>): Warrior_Options {
        const message = { startingRage: 0, stanceSnapshot: false, queueDelay: 0, shout: 0, stance: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Warrior_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Warrior_Options): Warrior_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double starting_rage */ 1:
                    message.startingRage = reader.double();
                    break;
                case /* bool stance_snapshot */ 6:
                    message.stanceSnapshot = reader.bool();
                    break;
                case /* int32 queue_delay */ 8:
                    message.queueDelay = reader.int32();
                    break;
                case /* proto.WarriorShout shout */ 3:
                    message.shout = reader.int32();
                    break;
                case /* proto.WarriorStance stance */ 7:
                    message.stance = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Warrior_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double starting_rage = 1; */
        if (message.startingRage !== 0)
            writer.tag(1, WireType.Bit64).double(message.startingRage);
        /* bool stance_snapshot = 6; */
        if (message.stanceSnapshot !== false)
            writer.tag(6, WireType.Varint).bool(message.stanceSnapshot);
        /* int32 queue_delay = 8; */
        if (message.queueDelay !== 0)
            writer.tag(8, WireType.Varint).int32(message.queueDelay);
        /* proto.WarriorShout shout = 3; */
        if (message.shout !== 0)
            writer.tag(3, WireType.Varint).int32(message.shout);
        /* proto.WarriorStance stance = 7; */
        if (message.stance !== 0)
            writer.tag(7, WireType.Varint).int32(message.stance);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.Warrior.Options
 */
export const Warrior_Options = new Warrior_Options$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TankWarrior$Type extends MessageType<TankWarrior> {
    constructor() {
        super("proto.TankWarrior", [
            { no: 3, name: "options", kind: "message", T: () => TankWarrior_Options }
        ]);
    }
    create(value?: PartialMessage<TankWarrior>): TankWarrior {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TankWarrior>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TankWarrior): TankWarrior {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.TankWarrior.Options options */ 3:
                    message.options = TankWarrior_Options.internalBinaryRead(reader, reader.uint32(), options, message.options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TankWarrior, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.TankWarrior.Options options = 3; */
        if (message.options)
            TankWarrior_Options.internalBinaryWrite(message.options, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.TankWarrior
 */
export const TankWarrior = new TankWarrior$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TankWarrior_Rotation$Type extends MessageType<TankWarrior_Rotation> {
    constructor() {
        super("proto.TankWarrior.Rotation", []);
    }
    create(value?: PartialMessage<TankWarrior_Rotation>): TankWarrior_Rotation {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TankWarrior_Rotation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TankWarrior_Rotation): TankWarrior_Rotation {
        return target ?? this.create();
    }
    internalBinaryWrite(message: TankWarrior_Rotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.TankWarrior.Rotation
 */
export const TankWarrior_Rotation = new TankWarrior_Rotation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TankWarrior_Options$Type extends MessageType<TankWarrior_Options> {
    constructor() {
        super("proto.TankWarrior.Options", [
            { no: 1, name: "starting_rage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "stance_snapshot", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "queue_delay", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "shout", kind: "enum", T: () => ["proto.WarriorShout", WarriorShout] },
            { no: 7, name: "stance", kind: "enum", T: () => ["proto.WarriorStance", WarriorStance] }
        ]);
    }
    create(value?: PartialMessage<TankWarrior_Options>): TankWarrior_Options {
        const message = { startingRage: 0, stanceSnapshot: false, queueDelay: 0, shout: 0, stance: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TankWarrior_Options>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TankWarrior_Options): TankWarrior_Options {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double starting_rage */ 1:
                    message.startingRage = reader.double();
                    break;
                case /* bool stance_snapshot */ 6:
                    message.stanceSnapshot = reader.bool();
                    break;
                case /* int32 queue_delay */ 8:
                    message.queueDelay = reader.int32();
                    break;
                case /* proto.WarriorShout shout */ 3:
                    message.shout = reader.int32();
                    break;
                case /* proto.WarriorStance stance */ 7:
                    message.stance = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TankWarrior_Options, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double starting_rage = 1; */
        if (message.startingRage !== 0)
            writer.tag(1, WireType.Bit64).double(message.startingRage);
        /* bool stance_snapshot = 6; */
        if (message.stanceSnapshot !== false)
            writer.tag(6, WireType.Varint).bool(message.stanceSnapshot);
        /* int32 queue_delay = 8; */
        if (message.queueDelay !== 0)
            writer.tag(8, WireType.Varint).int32(message.queueDelay);
        /* proto.WarriorShout shout = 3; */
        if (message.shout !== 0)
            writer.tag(3, WireType.Varint).int32(message.shout);
        /* proto.WarriorStance stance = 7; */
        if (message.stance !== 0)
            writer.tag(7, WireType.Varint).int32(message.stance);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.TankWarrior.Options
 */
export const TankWarrior_Options = new TankWarrior_Options$Type();
